### ISSUE TITLE
Errori validazione XSD del metadata

### ISSUE THREAD

**Issue by angeloimm** [italia/spid-saml-check#100]
Stiamo costruendo un SW per la gestione dei Soggetti Aggregatori di tipo full per servizi pubblici. Abbiamo generato il metadata come indicato nel documento "obblighi_dei_gestori_e_dei_titolari.pdf" e stiamo passando alla fase di check tramite spid-saml-checker. 
In fase di validazione XSD del metadata  ottengo gli errori che potete vedere nella immagine allegata. Il metadata creato mi sembra essere compliant alle specifiche tecniche indicate. Lo allego per completezza.
![Screenshot from 2021-01-14 19-46-27](https://user-images.githubusercontent.com/6228922/104727455-a5b64080-5735-11eb-8082-474ce4c380dc.png)
[sp-metadata-ente-UUUID-formattato.zip](https://github.com/italia/spid-saml-check/files/5820443/sp-metadata-ente-UUUID-formattato.zip)

**Comment by angeloimm** [comment]
buondì a tutti. Stiamo continuando ad ottenere errori di validazione del metdata nel caso di soggetto aggregatore full. Il metadata mi sembra essere compliant con quanto descritto dalle specifiche tecniche (abbiamo aggiunto anche i tag che dovrebbero essere facoltativi). Qualcuno sa dirmi se è possibile usare lo spid saml check per questa validazione dello schema o se è il metadata errato? In quest'ultimo caso non riusciamo a capire dove sia l'errore. Per completezza allego sia il metadata che la schermata dello spd-saml-checker. Grazie 1000
[elementi.zip](https://github.com/italia/spid-saml-check/files/5866572/elementi.zip)

**Comment by rdndnl** [comment]
Buongiorno anche noi abbiamo lo stesso problema.
Ho notato una incongruenza (o almeno lo sembra a me) tra le specifiche e le indicazioni fornite per il collaudo sulle quali probabilmente è stato impostato il test.

Seguendo le specifiche dell'[Avviso n. 19 - Regole tecniche aggregatori v. 4](https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n19v4-regole_tecniche_aggregatori_0.pdf), da metà della pagina 9 si legge:

> Il tag Extensions il cui tag antenato ContactPerson possiede l’attributo spid:entityType valorizzato con spid:aggregated contiene uno (e solo uno) dei seguenti tag “vuoti,” da utilizzarsi alternativamente a seconda della tipologia dell’Aggregato:
> 1. Public   — P.A., così come individuata nell'Avviso SPID N.28/2020;
> 2. PublicOperator  — Gestore, così come definito dal presente Avviso;
> 3. Private   — soggetto privato, così come definito dal presente Avviso;

mentre nell'[Avviso n. 22 - Struttura certificato collaudo Aggregatori. v.3](https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n22v3-metadata_collaudo.pdf) non si fa riferimento né nel testo, né nell'esempio, alla necessità di inserire il tag \<spid:Public/\> (ipotizzando un aggregatore/aggregato pubblico) come apparentemente è richiesto nelle specifiche.

Pertanto anch'io chiedo se dobbiamo ignorare tale errore dello strumento di verifica oppure sono sbagliate le specifiche?
