### ISSUE TITLE
Request Strict Validation: Signature Error

### ISSUE THREAD

**Issue by MarcoBevilacqua** [italia/spid-saml-check#101]
Ciao, 

stiamo provando ad ottenere l'accreditamento come aggregatore di servizi e per prima cosa abbiamo messo su una implementazione "basica" del login SPID con il link al validator. (il metadata è reperibile a https://spid.progettiesoluzioni.it/metadata). 
L'implementazione è stata fatta con l'SDK Laravel https://github.com/italia/spid-laravel

Non riuscendo a reperire informazioni su come dovrebbe agire il validatore "ufficiale" di AgID ho provato ad utilizzare SAML-Check per ottenere il controllo dei requisiti in locale. I Metadata di cui sopra vengono validati correttamente ma quando provo a validare la SAML request (Strict) ottengo un errore di cui invio screenshot:

![image](https://user-images.githubusercontent.com/3083440/105517328-357c6180-5cd7-11eb-87d8-ef47985ae307.png)

Effettivamente la request che viene inviata al validatore non contiene l'elemento signature, anche se il package Laravel firma correttamente la request e invia tutti i parametri (RelayState, Signature, SigAlg)

Questa è la request ricevuta da SAML-CHECK

`<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="ONELOGIN_62886899b9cd4fd7867746cdae040d47cf97e8a3" Version="2.0" ForceAuthn="true" IssueInstant="2021-01-22T16:24:29Z" Destination="https://localhost:8080" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" AssertionConsumerServiceURL="https://spid.progettiesoluzioni.it/spid/acs" AttributeConsumingServiceIndex="1">
    <saml:Issuer NameQualifier="https://spid.progettiesoluzioni.it/pub-ag-full/TEST" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">    
        https://spid.progettiesoluzioni.it/pub-ag-full/TEST
    </saml:Issuer>
    <samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient"/>
    <samlp:RequestedAuthnContext Comparison="minimum">
        <saml:AuthnContextClassRef>
            https://www.spid.gov.it/SpidL1
        </saml:AuthnContextClassRef>
    </samlp:RequestedAuthnContext>    
</samlp:AuthnRequest>`

Sono sicuro di aver mancato qualcosa ma non riesco a capire cosa. 
Grazie a chi potrà darmi una mano

**Comment by rdndnl** [comment]
Dal messaggio di errore pare che lo script che effettua i test abbia i fine riga "DOS/Windows" (\r\n) piuttosto che quelli Unix (\n), mandando in crisi l'interprete comandi di Linux.
Forse quegli script sono stati aperti per errore con un editor di testo Windows?
Effettua nuovamente un clone dal repository ed avvia il container docker senza fare modifiche ai file.

**Comment by damikael** [comment]
Nel caso si continui a riscontrare l'errore si potrà aprire una nuova issue.
