### ISSUE TITLE
spid-saml-check: errore nel scaricare i metadata SP

### ISSUE THREAD

**Issue by nicolastorgato** [italia/spid-saml-check#109]
Ciao, quando arrivo al punto in cui bisogna scaricare i metadata del proprio SP, ricevo il seguente errore: 

--2021-02-08 16:49:49-- https://urp.provincia.treviso.it/spid/module.php/saml/sp/metadata.php/default-sp Resolving urp.provincia.treviso.it (urp.provincia.treviso.it)... 172.x.x.x Connecting to urp.provincia.treviso.it (urp.provincia.treviso.it)|172.x.x.x|:443... failed: No route to host.

L'URL che inserisco è quello in cui sono esposti i nostri metadata, ovvero questo: https://urp.provincia.treviso.it/spid/module.php/saml/sp/metadata.php/default-sp

Ho fatto tutti i passi precedenti correttamente. Che URL dovrei inserire? Non è chiaro dalla documentazione.

Grazie

**Comment by damikael** [comment]
Verificare che sia effettivamente possibile effettuare il download del metadata dalla propria rete

**Comment by nicolastorgato** [comment]
Sì, il metadata è scaricabile, sembra ci sia un problema di routing nella libreria. C'è un modo per fare il debug per questo problema? Grazie

**Comment by nicolastorgato** [comment]
Sì, il metadata è scaricabile. Per caso sai come viene visto il container di docker verso l'esterno? C'è la possibilità di configurazione della rete? Indirizzo IP?
