### ISSUE TITLE
Errore buid spid-saml-check

### ISSUE THREAD

**Issue by davidegallesio** [italia/spid-saml-check#110]
Buongiorno,
ho riscontrato e risolto questo problema nel build di spid-saml-check:

il comando
$ docker build -t spid-saml-check .
mi va in errore (dopo qualche minuto) sull’istruzione del dockerfile:

_RUN cd /spid-saml-check/spid-validator &&
cd client && npm install --silent && cd … &&
cd server && npm install --silent && cd … &&
npm run build_

e nel log vedo il messaggio che non dice nulla:

executor failed running [/bin/sh -c cd /spid-saml-check/spid-validator && cd client && npm install --silent && cd … && cd server && npm install --silent && cd … && npm run build]: exit code: 1

Ho risolto sostituendo nel _dockerfile_ presente nella cartella clonata _spid-saml-check_ il comando

_RUN cd /spid-saml-check/spid-validator &&
cd client && npm install --silent && cd … &&
cd server && npm install --silent && cd … &&
npm run build_

con

_RUN cd /spid-saml-check/spid-validator &&
cd client && npm install --verbose 2 && cd … &&
cd server && npm install --verbose 2 && cd … &&
npm run build_

Quindi è stato evidente che il nostro firewall bloccava l’accesso all’indirizzo _https://registry.npmjs.org/_ necessario all’installazione.

Modificate le impostazioni del firewall sono riuscito ad installare il container.

@michele.damico perché nel dockerfile ufficiale su git non mettete _verbose 2_ invece che _silent_ ?

Grazie

**Comment by damikael** [comment]
Buongiorno @davidegallesio ,
in effetti è utile per capire eventuali problemi di installazione delle dipendenze, come nel tuo caso.
Se vuoi puoi proporre tu stesso una PR.

Grazie

**Comment by deligant** [comment]
Ho un errore in fase di compilazine del docker
Err:1 http://deb.debian.org/debian buster InRelease
  Temporary failure resolving 'deb.debian.org'
Err:2 http://security.debian.org/debian-security buster/updates InRelease
  Temporary failure resolving 'security.debian.org'
Err:3 http://deb.debian.org/debian buster-updates InRelease
  Temporary failure resolving 'deb.debian.org'
Reading package lists...
W: Failed to fetch http://deb.debian.org/debian/dists/buster/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://security.debian.org/debian-security/dists/buster/updates/InRelease  Temporary failure resolving 'security.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/buster-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package wget
E: Unable to locate package curl
E: Unable to locate package unzip
E: Unable to locate package gcc
E: Unable to locate package libxml2-utils
E: Unable to locate package openssl
E: Unable to locate package python3
E: Unable to locate package python3-pip
E: Unable to locate package xmlsec1
E: Unable to locate package apache2
The command '/bin/sh -c apt-get update     && apt-get install -y         wget         curl         unzip         gcc         libxml2-utils         openssl         python3         python3-pip         xmlsec1         apache2' returned a non-zero code: 100

**Comment by deligant** [comment]
Scusate se commento il mio errore... La soluzione abbastanza semplice è la seguente per ubuntu
- verificare che il firewall faccia dialogare il network del docker con l'esterno
- inserire il DNS hardcoded nella configurazione globale del docker, come segnalato in questo post: https://stackoverflow.com/questions/24832972/docker-apt-get-update-fails/51089399#51089399
