### ISSUE TITLE
Test if the XSD validates and if the signature is valid

### ISSUE THREAD

**Issue by WEMAPP** [italia/spid-saml-check#111]
Buonasera,
sto ricevendo questo errore nella valutazione della richiesta.
Potreste darmi qualche suggerimento per la risoluzione? 
Grazie

The AuthnRequest must validate against XSD and must have a validsignature stdout: Validating XSD... FAIL stderr: base64: invalid input stderr:/tmp/tmp.RiWhGTL7Mx:1: parser error : Document is empty stderr: ^

**Comment by damikael** [comment]
Buongiorno,
occorre verificare che la Request inviata sia valida e firmata correttamente.
Da quanto riportato sembrerebbe che il messaggio xml della Request sia vuoto (parser error : Document is empty)

**Comment by fume** [comment]
Salve,
con l'ultima versione dello spid-saml-check anche io ho problemi nel superare il test "strict : Test if the XSD validates and if the signature is valid"

l'errore è il seguente

The AuthnRequest must validate against XSD and must have a valid signature stderr: ./script/check-request-xsd-and-signature.sh: line 17: $'\r': command not found stderr: ./script/check-request-xsd-and-signature.sh: line 19: $'\r': command not found stderr: ./script/check-request-xsd-and-signature.sh: line 22: $'\r': command not found stderr: ./script/check-request-xsd-and-signature.sh: line 25: $'\r': command not found stderr: cat: './data/http___*******_omitted_********'$'\r''/SAMLRequest.authn'$'\r''.request.txt': No such file or directory stderr: ./script/check-request-xsd-and-signature.sh: line 70: syntax error near unexpected token `elif' stderr: ./script/check-request-xsd-and-signature.sh: line 70: ` elif [ "${CTX}" == "logout" ]; then '

salta all'occhio **syntax error near unexpected token** , che fa pensare ad un errore nello script sh. Potreste cortesemente verificare? Non vorrei che la validazione ufficiale fallisca per lo stesso motivo.

Verificando con altri tool online (https://www.samltool.com/validate_authn_req.php) la richiesta risulta correttamente firmata

**Comment by WEMAPP** [comment]
Salve a tutti
Abbiamo trovato l'errore ed era un errore molto banale.
Il problema che il form request inviava, per un mero errore di battitura, un carattere "=" alla fine della stringa in base 64. 
Stranamente tutti i controlli andavano a buon fine tranne che quello.
Quindi, per noi il problema era che il base64 non era corretto.
Saluti

**Comment by fume** [comment]
ciao @WEMAPP ,
puoi dirmi la versione dello spid-saml-check che stai utilizzando? Anche il commit git è sufficiente.

Io con l'ultima versione ad oggi (5f4363ffe) continuo ad avere problemi con la validazione della signature della SAMLRequest benchè questa sia corretta (verificata con svariati tool, esito sempre ok)

**Comment by fume** [comment]
@damikael è possibile avere un riscontro sull'errore citato qualche messaggio fa? (https://github.com/italia/spid-saml-check/issues/111#issuecomment-779360207)

**Comment by fume** [comment]
hi @damikael ,
i tried an old version of the spid-saml-check image and the SAME EXACT SAMLRequest is validated successfully. I don't know which version the older image is but i do know that the image was built 3 months ago.

Given that your package.json is using the ^ syntax for dependencies version and there is no package-lock.json, every time we build the spid-saml-check image the result could be different even if your source-code didn't change

**Comment by matteo2411** [comment]
Ci sono novità circa questa issue? Io ho lo stesso problema con l'ultima versione

**Comment by ambra886** [comment]
Anche io sto riscontrando lo stesso problema, sto sviluppando l'SP in Java e ho messo su dei test unitari che mi validano la firma e mi risultano tutti passati. Ho verificato la firma dell'authnrequest https://tools.chilkat.io/xmlDsigVerify.cshtml e risulta valida.
Con l'ultima versione del spid-saml-check il test non viene superato con l'errore:
`The AuthnRequest must validate against XSD and must have a valid signature
stderr: ./script/check-request-xsd-and-signature.sh: line 17: $'\r': command not found
stderr: ./script/check-request-xsd-and-signature.sh: line 19: $'\r': command not found
stderr: ./script/check-request-xsd-and-signature.sh: line 22: $'\r': command not found
stderr: ./script/check-request-xsd-and-signature.sh: line 25: $'\r': command not found
stderr: cat: './data/http___192_168_0_111'$'\r''/SAMLRequest.authn'$'\r''.request.txt': No such file or directory
stderr: ./script/check-request-xsd-and-signature.sh: line 70: syntax error near unexpected token `elif'
stderr: ./script/check-request-xsd-and-signature.sh: line 70: `    elif [ "${CTX}" == "logout" ]; then
': false`

**Comment by matteo2411** [comment]
@ambra886 io ho risolto, il problema sembra relativo a Windows che quando va a importarmi il progetto con i vari file .sh aggiunge spazi in più. Convertendo il file check-request-xsd-and-signature.sh (ed eventuali altri che vanno in errore) con dos2unix ho risolto e la validazione va a buon fine.

**Comment by fume** [comment]
grazie @matteo2411, farò un ulteriore tentativo seguendo il tuo suggerimento.

**Comment by ambra886** [comment]
Grazie @matteo2411 eseguendo il container su sistema linux tutto ha funzionato correttamente

**Comment by fume** [comment]
> @ambra886 io ho risolto, il problema sembra relativo a Windows che quando va a importarmi il progetto con i vari file .sh aggiunge spazi in più. Convertendo il file check-request-xsd-and-signature.sh (ed eventuali altri che vanno in errore) con dos2unix ho risolto e la validazione va a buon fine.

Ciao @matteo2411, @ambra886  se vi può interessare ho ottenuto lo stesso risultato sfruttando VSCode: è stato sufficiente aprire i file incriminati e "forzare" il Line Ending a LF (unix like) anzichè CRLF (Windows Like), come potete vedere dallo screenshot sotto.

![image](https://user-images.githubusercontent.com/2969850/112616865-8833e000-8e24-11eb-9998-7402ad7e69c5.png)


Grazie di nuovo @matteo2411 per la dritta.
ciao ciao,
