### ISSUE TITLE
Check Response - Error NoState

### ISSUE THREAD

**Issue by nicolastorgato** [italia/spid-saml-check#112]
Buongiorno, dopo aver scaricato correttamente il metadata, sto procedendo con i test ma, nella sezione Check Response, quando clicco su "Invia Response al Service Provider", nella pagina che si apre ricevo il seguente errore: 

Informazioni di stato perse. SimpleSAML_Error_NoState: NOSTATE.
Sembra essere un problema nella gestione delle sessioni, sapete per caso dirmi come risolverlo?
 
Altre volte invece mi viene ritornato: "Eccezione non gestita", con il relativo messaggio di errore, che effettivamente corrisponde al relativo test (ad esempio: Response ID mancante). E' giusto che si comporti così? Significa che il test è andato a buon fine? Corrisponde al vostro cosiddetto "KO"?

Grazie!

**Comment by damikael** [comment]
Buongiorno,
il problema relativo alla perdita di sessione sul SP dipende dal software che implementa il SP, in questo caso SimpleSAMLphp. Occorre capire se il problema si verifica in modo sistematico oppure randomico. Nel caso fosse randomico potrebbe dipendere da eccessivo tempo trascorso tra l'invio della Request e la ricezione della Response. Se invece è sistematico dipende da come sono gestite le sessioni e se la sessione è sovrascritta dopo l'invio della Request.

Nel caso di eccezione, se il messaggio ricevuto sul SP è conforme all'esito atteso indicato per la relativa Response sul Validator, il test si può considerare superato.

**Comment by nicolastorgato** [comment]
Okei. E se la risposta prevista dal Validator è KO, ma l'SP mi ritorna un messaggio positivo con tutti i relativi attributi corretti?

**Comment by damikael** [comment]
Il test deve essere considerato come non superato, in quanto il SP permette correttamente l'accesso al servizio mentre invece dovrebbe negarlo (Esempio: se la Response è firmata con un certificato diverso da quello dell'IdP, il SP non deve permettere l'accesso al servizio)

**Comment by nicolastorgato** [comment]
Scusa se ti disturbodi nuovo...Ho effettuato i test della Response e circa la metà dei test non sono stati superati. Ora cosa dovrei fare? Come faccio a fare in modo che i test vengano superati?

**Comment by damikael** [comment]
Occorre intervenire sull'implementazione del SP perchè gestisca correttamente i casi

**Comment by damikael** [comment]
Se utilizzi SimpleSAMLphp, potresti valutare di utilizzare [spid-php](https://github.com/italia/spid-php)
