### ISSUE TITLE
The entityID attribute must be a valid HTTPS url

### ISSUE THREAD

**Issue by fume** [italia/spid-saml-check#114]
Non c'è traccia di tale vincolo sulle regole tecniche. Inoltre, essendo l'entityID un URI e non un URL, che motivo c'è di forzarlo in https?

**Comment by fume** [comment]
up

**Comment by damikael** [comment]
L'EntityID deve essere una URL, preferibilmente HTTPS, corrispondente ad un dominio appartenente all'ente. 
A breve seguirà un avviso specifico. 
Il test sarà modificato per verificare che l'EntityID sia in forma di URL, non necessariamente HTTPS.
