### ISSUE TITLE
Validazione SP Metadata: strict : Test the compliance of SingleLogoutService element(s)

### ISSUE THREAD

**Issue by deligant** [italia/spid-saml-check#115]
![image](https://user-images.githubusercontent.com/6317497/108840007-0c9d0400-75d6-11eb-8bb1-f0becf51391b.png)

Credo che la frase non sia corretta ma che faccia il check dell'HTTPS: l'url è validissima ma in http (sono ancora in fase di test in locale)!

**Comment by mauromol** [comment]
Concordo, anche io ho notato questo problema.

**Comment by damikael** [comment]
Moved to https://github.com/italia/spid-sp-test/issues/52
