### ISSUE TITLE
Validazione Metadata SP: strict : Test the compliance of AttributeConsumingService element(s)

### ISSUE THREAD

**Issue by deligant** [italia/spid-saml-check#116]
![image](https://user-images.githubusercontent.com/6317497/108840280-6bfb1400-75d6-11eb-871f-72dcf8cba725.png)
Sono verifiche riguardanti i "domicile*", attributi esistenti e a quanto visto inseriti nell'ultimo git ma probabilmente ancora mancanti nell'XSD

**Comment by damikael** [comment]
Risolto con la release:
https://github.com/italia/spid-saml-check/releases/tag/v.1.6.0
