### ISSUE TITLE
SimpleSAML_Error_Error: UNHANDLEDEXCEPTION

### ISSUE THREAD

**Issue by AlessandraB19** [italia/spid-saml-check#119]
Durante l'esecuzione dei test legati alla Response, ho il seguente riscontro:
test 01 Response corretta con esito SimpleSAML_Error_Error: UNHANDLEDEXCEPTION e dai log del SP ho l'output che segue:

[php7:notice] [pid 10892] PHP Notice:  Undefined offset: 0 in /home/spid/spid-php/setup/simplesamlphp/saml2/src/SAML2/Response.php on line 47, referer: http://localhost:8080/
[php7:notice] [pid 10892] PHP Notice:  Trying to get property 'nodeValue' of non-object in /home/spid/spid-php/setup/simplesamlphp/saml2/src/SAML2/Response.php on line 47, referer: http://localhost:8080/
[php7:notice] [pid 10892] PHP Notice:  Trying to access array offset on value of type null in /home/spid/spid-php/setup/simplesamlphp/saml2/src/SAML2/Response.php on line 98, referer: http://localhost:8080/
[pid 10892]  PHP Notice:  Trying to access array offset on value of type null in /home/spid/spid-php/setup/simplesamlphp/saml2/src/SAML2/Response.php on line 99, referer: http://localhost:8080/

Prima di procedere con gli altri test vorrei capire se l'esito negativo è riconducibile a tale warning

**Comment by damikael** [comment]
Il problema è inerente l'implementazione del SP.
