### ISSUE TITLE
Errore Check XSD aggiungendo tag PublicServicesFullOperator

### ISSUE THREAD

**Issue by infoFactorySRL** [italia/spid-saml-check#122]
Dopo aver inviato il metada per la validazione AGID ci è pervenuta la sequente richiesta:

Inoltre, essendo voi gestori di pubblico servizio, dovete essere conformi all’**Avviso SPID n. 19 v.4** (https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n19v4-regole_tecniche_aggregatori_0.pdf) ed in particolare:
1.       l’entityID deve contenere il codice attività pub-op-full
2.       il tag ContactPerson deve avere l’attributo spid:entityType valorizzato come spid:aggregator e deve contenere, nel tag Extensions, il tag vuoto PublicServicesFullOperator

Dopo aver aggiunto il tag richiesto ed aver eseguito la validazione tramite XSD  questo è il risultato
the metadata must validate against the XSD stderr: ./data/https___64e1f4223730_ngrok_io_spid_pub_op_full_/sp-metadata.xml:45: element PublicServicesFullOperator: Schemas validity error : Element '{https://spid.gov.it/saml-extensions}PublicServicesFullOperator': This element is not expected. Expected is ( {https://spid.gov.it/invoicing-extensions}CessionarioCommittente ). stderr: ./data/https___64e1f4223730_ngrok_io_spid_pub_op_full_/sp-metadata.xml fails to validate

Sull abase dell'aviso n. 19 e dell'esempio in esso contenuto non vedo errori.
Vi allego anche il file del metadata da verificare:
?xml version="1.0"?>
<md:EntityDescriptor xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:spid="https://spid.gov.it/saml-extensions" entityID="https://64e1f4223730.ngrok.io/spid/pub-op-full/" ID="id-a8ylHyZtrCrGPPJ7v">
    <ds:Signature Id="Signature1">
        <ds:SignedInfo>
            <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
            <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
            <ds:Reference URI="#id-a8ylHyZtrCrGPPJ7v">
                <ds:Transforms>
                    <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                    <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
                </ds:Transforms>
                <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
                <ds:DigestValue>
                    gkPdVSAnm+yo25nqYiqgzcHih7UhzJLoKrYrRDoq0CQ=
                </ds:DigestValue>
            </ds:Reference>
        </ds:SignedInfo>
        <ds:SignatureValue>
            lZ9SS8Pch/g5R9Whx3b0+tKMCLB6P7HJOB9jAXM9mg9fTqaB7kUbea2MXR7MpVVZ
K6mn3O9qdasSkNbAZWUI0ik5PXG4yAX5dToQefffezJy/AYeeNCSnILIT9mNUOTg
1eGMvydSezjUwnfAyLIqZUKLhd/XSd7LoB/Pw9A23MYsZwHnUw+UbDStoo5EBiS1
1HWQDQhypgG3YIkjkF5LZ1uBuKdzn51KpdDSPiS45+jUU5R/jVa2T2gggSsHEtdd
S+RmG0n13wXNtT3Set2HrOIjyPMJVLKjrRZ6SViMnM6B8Y54Nlh+nXZQT9Ybndrz
lL6DA1P54WYLaW4KO3w75g==
        </ds:SignatureValue>
        <ds:KeyInfo>
            <ds:X509Data>
                <ds:X509Certificate>
                    MIIDZzCCAk+gAwIBAgIUYe/NTf4M62lMgWHxxBx0o9nDo0EwDQYJKoZIhvcNAQELBQAwQzELMAkGA1UEBhMCSVQxDjAMBgNVBAgMBVVkaW5lMQ4wDAYDVQQHDAVVZGluZTEUMBIGA1UECgwLSW5mb2ZhY3RvcnkwHhcNMjEwMjE5MTY0OTIwWhcNMzEwMjE3MTY0OTIwWjBDMQswCQYDVQQGEwJJVDEOMAwGA1UECAwFVWRpbmUxDjAMBgNVBAcMBVVkaW5lMRQwEgYDVQQKDAtJbmZvZmFjdG9yeTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALHoeA5wtS9QXQ9kCrvKxE8OEa/xik2Qp7KwrzN/EjNfsQ8KyIIIv6OrYL3QSZZw4uTkYzHW+v4eB7Mal+NIIqCy2mJEBxoR7C+P0+Gj72RC35TDASVqzXT8/Lysnh5xdCeYfRUZe5LDaAoif8rDyVAPaI+2HkTvWhqPyP26hZrQrLm/EoEhmBPgW/4OcNb7/pWnx1QBd6y/G6aHPrETDHFDOeYEqe8OxE/1LcfvQDni2ScVcO8/LL13UeORcmUlR48zdozQJ1/JE/UWJ+aFBai9aeVX+CoHCwCqc3nDD2aoFqoDti4GGQLdAf9paVAWgoPTlNKtSDCC4w0hOLgSVp8CAwEAAaNTMFEwHQYDVR0OBBYEFKeDhgo8GRkkJwQ0fbyYlj2621b+MB8GA1UdIwQYMBaAFKeDhgo8GRkkJwQ0fbyYlj2621b+MA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAA3V/gqvPWueTzTdxdE4snG6+6s1XI5MU8PyxQVG5qERq4cNooGx+qesRX4wizYkvvxgZdYceaTxZMI7P6pWa3QO5bbZsZH0lOwZWGNeSwXoM95qxLsY5U6LcFFRojFrtRloCS2pELUM45j43UBLF7/5UQX75QNK2WgAueOcVN4EUNXhVD73alsokcNh16VKhKVjmHYaYFJiMnqlBPU0Bc9wfUobRORTvZxgTKPhJdgJ8oCrhPGDlcAc7AFMIsDNhgLIZjNeGPQ6lHAAVQXwcD7n8F12Gb/iZBOlLPYwpW8B0Fw4AeQ3T26fylvdc7576w7suDZseUHDw/hZvfoOJ0w=
                </ds:X509Certificate>
            </ds:X509Data>
        </ds:KeyInfo>
    </ds:Signature>
    <md:SPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol" AuthnRequestsSigned="true" WantAssertionsSigned="true">
        <md:KeyDescriptor use="signing">
            <ds:KeyInfo>
                <ds:X509Data>
                    <ds:X509Certificate>
                        MIIDZzCCAk+gAwIBAgIUYe/NTf4M62lMgWHxxBx0o9nDo0EwDQYJKoZIhvcNAQEL
BQAwQzELMAkGA1UEBhMCSVQxDjAMBgNVBAgMBVVkaW5lMQ4wDAYDVQQHDAVVZGlu
ZTEUMBIGA1UECgwLSW5mb2ZhY3RvcnkwHhcNMjEwMjE5MTY0OTIwWhcNMzEwMjE3
MTY0OTIwWjBDMQswCQYDVQQGEwJJVDEOMAwGA1UECAwFVWRpbmUxDjAMBgNVBAcM
BVVkaW5lMRQwEgYDVQQKDAtJbmZvZmFjdG9yeTCCASIwDQYJKoZIhvcNAQEBBQAD
ggEPADCCAQoCggEBALHoeA5wtS9QXQ9kCrvKxE8OEa/xik2Qp7KwrzN/EjNfsQ8K
yIIIv6OrYL3QSZZw4uTkYzHW+v4eB7Mal+NIIqCy2mJEBxoR7C+P0+Gj72RC35TD
ASVqzXT8/Lysnh5xdCeYfRUZe5LDaAoif8rDyVAPaI+2HkTvWhqPyP26hZrQrLm/
EoEhmBPgW/4OcNb7/pWnx1QBd6y/G6aHPrETDHFDOeYEqe8OxE/1LcfvQDni2ScV
cO8/LL13UeORcmUlR48zdozQJ1/JE/UWJ+aFBai9aeVX+CoHCwCqc3nDD2aoFqoD
ti4GGQLdAf9paVAWgoPTlNKtSDCC4w0hOLgSVp8CAwEAAaNTMFEwHQYDVR0OBBYE
FKeDhgo8GRkkJwQ0fbyYlj2621b+MB8GA1UdIwQYMBaAFKeDhgo8GRkkJwQ0fbyY
lj2621b+MA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAA3V/gqv
PWueTzTdxdE4snG6+6s1XI5MU8PyxQVG5qERq4cNooGx+qesRX4wizYkvvxgZdYc
eaTxZMI7P6pWa3QO5bbZsZH0lOwZWGNeSwXoM95qxLsY5U6LcFFRojFrtRloCS2p
ELUM45j43UBLF7/5UQX75QNK2WgAueOcVN4EUNXhVD73alsokcNh16VKhKVjmHYa
YFJiMnqlBPU0Bc9wfUobRORTvZxgTKPhJdgJ8oCrhPGDlcAc7AFMIsDNhgLIZjNe
GPQ6lHAAVQXwcD7n8F12Gb/iZBOlLPYwpW8B0Fw4AeQ3T26fylvdc7576w7suDZs
eUHDw/hZvfoOJ0w=

                    </ds:X509Certificate>
                </ds:X509Data>
            </ds:KeyInfo>
        </md:KeyDescriptor>
        <md:KeyDescriptor use="encryption">
            <ds:KeyInfo>
                <ds:X509Data>
                    <ds:X509Certificate>
                        MIIDZzCCAk+gAwIBAgIUYe/NTf4M62lMgWHxxBx0o9nDo0EwDQYJKoZIhvcNAQEL
BQAwQzELMAkGA1UEBhMCSVQxDjAMBgNVBAgMBVVkaW5lMQ4wDAYDVQQHDAVVZGlu
ZTEUMBIGA1UECgwLSW5mb2ZhY3RvcnkwHhcNMjEwMjE5MTY0OTIwWhcNMzEwMjE3
MTY0OTIwWjBDMQswCQYDVQQGEwJJVDEOMAwGA1UECAwFVWRpbmUxDjAMBgNVBAcM
BVVkaW5lMRQwEgYDVQQKDAtJbmZvZmFjdG9yeTCCASIwDQYJKoZIhvcNAQEBBQAD
ggEPADCCAQoCggEBALHoeA5wtS9QXQ9kCrvKxE8OEa/xik2Qp7KwrzN/EjNfsQ8K
yIIIv6OrYL3QSZZw4uTkYzHW+v4eB7Mal+NIIqCy2mJEBxoR7C+P0+Gj72RC35TD
ASVqzXT8/Lysnh5xdCeYfRUZe5LDaAoif8rDyVAPaI+2HkTvWhqPyP26hZrQrLm/
EoEhmBPgW/4OcNb7/pWnx1QBd6y/G6aHPrETDHFDOeYEqe8OxE/1LcfvQDni2ScV
cO8/LL13UeORcmUlR48zdozQJ1/JE/UWJ+aFBai9aeVX+CoHCwCqc3nDD2aoFqoD
ti4GGQLdAf9paVAWgoPTlNKtSDCC4w0hOLgSVp8CAwEAAaNTMFEwHQYDVR0OBBYE
FKeDhgo8GRkkJwQ0fbyYlj2621b+MB8GA1UdIwQYMBaAFKeDhgo8GRkkJwQ0fbyY
lj2621b+MA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAA3V/gqv
PWueTzTdxdE4snG6+6s1XI5MU8PyxQVG5qERq4cNooGx+qesRX4wizYkvvxgZdYc
eaTxZMI7P6pWa3QO5bbZsZH0lOwZWGNeSwXoM95qxLsY5U6LcFFRojFrtRloCS2p
ELUM45j43UBLF7/5UQX75QNK2WgAueOcVN4EUNXhVD73alsokcNh16VKhKVjmHYa
YFJiMnqlBPU0Bc9wfUobRORTvZxgTKPhJdgJ8oCrhPGDlcAc7AFMIsDNhgLIZjNe
GPQ6lHAAVQXwcD7n8F12Gb/iZBOlLPYwpW8B0Fw4AeQ3T26fylvdc7576w7suDZs
eUHDw/hZvfoOJ0w=

                    </ds:X509Certificate>
                </ds:X509Data>
            </ds:KeyInfo>
        </md:KeyDescriptor>
        <md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://64e1f4223730.ngrok.io/spid/ls/post/"/>
        <md:NameIDFormat>
            urn:oasis:names:tc:SAML:2.0:nameid-format:transient
        </md:NameIDFormat>
        <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://64e1f4223730.ngrok.io/spid/acs/" index="0" isDefault="true"/>
        <md:AttributeConsumingService index="0">
            <md:ServiceName xml:lang="it">
                https://64e1f4223730.ngrok.io/spid/metadata
            </md:ServiceName>
            <md:RequestedAttribute Name="spidCode" isRequired="true"/>
            <md:RequestedAttribute Name="name" isRequired="true"/>
            <md:RequestedAttribute Name="familyName" isRequired="true"/>
            <md:RequestedAttribute Name="fiscalNumber" isRequired="true"/>
            <md:RequestedAttribute Name="email" isRequired="true"/>
            <md:RequestedAttribute Name="gender" isRequired="false"/>
            <md:RequestedAttribute Name="companyName" isRequired="false"/>
            <md:RequestedAttribute Name="ivaCode" isRequired="false"/>
            <md:RequestedAttribute Name="digitalAddress" isRequired="false"/>
            <md:RequestedAttribute Name="dateOfBirth" isRequired="false"/>
            <md:RequestedAttribute Name="address" isRequired="false"/>
            <md:RequestedAttribute Name="mobilePhone" isRequired="false"/>
        </md:AttributeConsumingService>
    </md:SPSSODescriptor>
    <md:Organization>
        <md:OrganizationName xml:lang="it">
            Net spa
        </md:OrganizationName>
        <md:OrganizationDisplayName xml:lang="it">
            Net spa
        </md:OrganizationDisplayName>
        <md:OrganizationURL xml:lang="it">
            https://netaziendapulita.it/
        </md:OrganizationURL>
    </md:Organization>
    <md:ContactPerson contactType="other" spid:entityType="spid:aggregator">
        <md:Extensions>
            <spid:IPACode>
                ns_030
            </spid:IPACode>
            <spid:Public/>
            <spid:PublicServicesFullOperator/>
        </md:Extensions>
        <md:EmailAddress>
            net@netaziendapulita.it
        </md:EmailAddress>
        <md:TelephoneNumber>
            +390432206811
        </md:TelephoneNumber>
    </md:ContactPerson>
</md:EntityDescriptor>

**Comment by damikael** [comment]
Il problema non dovrebbe più presentarsi ora, tuttavia con la prossima migrazione dei controlli su spid-sp-test le verifiche saranno più stringenti.
