### ISSUE TITLE
Attributo companyFiscalNumber mancante nella lista degli attributi SPID richiedibili

### ISSUE THREAD

**Issue by AntonioGiovanniSchiavone** [italia/spid-saml-check#125]
Nella lista degli attributi SPID richiedibili  manca l'Attributo companyFiscalNumber, definito nell'[Avviso SPID n°15](https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n15-_rilascio_identita_uso_professionale.pdf) e richiedibile dagli Identity Provider che erogano [Identità per Persona Giuridica](https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n18_v.2-_autenticazione_persona_giuridica_o_uso_professionale_per_la_persona_giuridica.pdf).

**Comment by damikael** [comment]
Risolto con gli ultimi rilasci e con la PR proposta.
Grazie
