### ISSUE TITLE
Segnala un problema di stampa 

### ISSUE THREAD

**Issue by David-Jimenez-Bermejo** [italia/spid-saml-check#128]
Quando si effettuano le verifiche e si stampano i risultati con il pulsante "Stampa", se invece che su carta lo si ottiene in un file, nel file risultante vedo due problemi: 
- Quando si cambia pagina, le informazioni che dovrebbero apparire nelle intestazioni e nei piè di pagina vengono perse. Nell'immagine allegata puoi vedere cosa sto cercando di spiegare, va dal test 0 alla fine di una pagina al test 4 all'inizio della successiva mentre cerca di scrivere nell'intestazione e nel piè di pagina.
![falloPDF](https://user-images.githubusercontent.com/72555554/110792178-5a229d80-8273-11eb-85b6-4a1c3afb19d5.png)

- non ha il colore verde per "success" o rosso per "failure" tutto risulta bianco senza colore di sfondo

**Comment by damikael** [comment]
Se si utilizza Chrome, è possibile impostare tra le opzioni di stampa le seguenti configurazioni:
 - Stampa - **a colori** 
 - Opzioni - **Intestazioni e piè di pagina** NON selezionato
 - Opzioni - **Grafica in background** selezionato


![image](https://user-images.githubusercontent.com/31276401/122592249-55d10200-d064-11eb-8408-2f68c9e2c506.png)

![image](https://user-images.githubusercontent.com/31276401/122592404-831db000-d064-11eb-95e1-f63d45b2b02e.png)
