### ISSUE TITLE
Servizio SPID Validator disponibile pubblicamente su spid-validator.it

### ISSUE THREAD

**Issue by nicolabeghin** [italia/spid-saml-check#129]
Se può tornare utile, al seguente indirizzo è esposto pubblicamente il servizio `spid-saml-check`:

- **VALIDATOR** https://www.spid-validator.it (credenziali `validator`/`validator`)
- **METADATA** https://www.spid-validator.it/metadata.xml

Questo perchè non mi risulta esista un servizio ufficiale di validazione. In tale maniera:
* non c'è bisogno di buildare l'immagine
* è sempre possibile avere un servizio ready-to-use
* il servizio è periodicamente aggiornato con le ultime modifiche del repository

Viene ri-buildato periodicamente dai sorgenti del repository.

**Comment by AlessandraB19** [comment]
Salve, nell'utilizzare questo validator sto riscontrando un problema durante i test sulla Response: dopo aver inviato la richiesta si riceve la seguente eccezione SimpleSAML\Error\Error: UNHANDLEDEXCEPTION

Backtrace:
1 www/_include.php:17 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: Exception: Invalid SAML2 timestamp passed to xsDateTimeToTimestamp: 2021-04-09T11:44:37+02:00
Backtrace:
8 /home/spid/spid-php/vendor/simplesamlphp/saml2/src/SAML2/Utils.php:699 (SAML2\Utils::xsDateTimeToTimestamp)
7 /home/spid/spid-php/setup/simplesamlphp/saml2/src/SAML2/Message.php:168 (SAML2\Message::__construct)
6 /home/spid/spid-php/vendor/simplesamlphp/saml2/src/SAML2/StatusResponse.php:57 (SAML2\StatusResponse::__construct)
5 /home/spid/spid-php/setup/simplesamlphp/saml2/src/SAML2/Response.php:33 (SAML2\Response::__construct)
4 /home/spid/spid-php/setup/simplesamlphp/saml2/src/SAML2/Message.php:584 (SAML2\Message::fromXML)
3 /home/spid/spid-php/setup/simplesamlphp/saml2/src/SAML2/HTTPPost.php:90 (SAML2\HTTPPost::receive)
2 modules/saml/www/sp/saml2-acs.php:35 (require)
1 lib/SimpleSAML/Module.php:266 (SimpleSAML\Module::process)
0 www/module.php:10 (N/A)

**Comment by damikael** [comment]
@nicolabeghin verifica orario e timezone sul server che espone spid-validator.it

**Comment by nicolabeghin** [comment]
grazie @damikael su www.spid-validator.it viene usato la timezone CET (italiana) in seguito a PR https://github.com/italia/spid-saml-check/pull/131 dato che le richieste del SSO sono in CET e non UTC, essendo in Italia. 

Ho visto ora che hai chiuso la PR con messaggio
> Le regole tecniche SPID specificano che gli attributi IssueInstant devono essere espressi in UTC
che non conoscevo e infatti non capivo perchè trasformasse in UTC.

Capisco, rimuoverò la conversione in UTC ma solo in seguito ad aver capito come fare in modo di avere il SSO in UTC (è su CET perchè chiaramente parla anche con altri sistemi italiani su CET).

**Comment by fume** [comment]
@nicolabeghin , per essere più precisi è il protocollo SAML2 Core Oasis a definire che

> All SAML time values have the type xs:dateTime, which is built in to the W3C XML Schema Datatypes
specification [Schema2], and MUST be expressed in UTC form, with no time zone component. 

Questo serve proprio ad ovviare il problema di cui parli tu. Quindi se ci sono SP che usano altre timezone, sono loro a non essere compliant con le specifiche (a prescindere da SPID).

ciao ciao,

**Comment by nicolabeghin** [comment]
> @nicolabeghin , per essere più precisi è il protocollo SAML2 Core Oasis a definire che
> 
> > All SAML time values have the type xs:dateTime, which is built in to the W3C XML Schema Datatypes
> > specification [Schema2], and MUST be expressed in UTC form, with no time zone component.
> 
> Questo serve proprio ad ovviare il problema di cui parli tu. Quindi se ci sono SP che usano altre timezone, sono loro a non essere compliant con le specifiche (a prescindere da SPID).
> 
> ciao ciao,

grazie @fume , non conoscevo e onestamente sono ancora più confuso perchè stiamo usando [Keycloak](https://www.keycloak.org/) (un SSO di RedHat) che da quanto capisco utilizza la timezone corrente per popolare l'attributo `IssueInstant`, che quindi non è compatibile con quello UTC di `spid-saml-check`.
* https://github.com/keycloak/keycloak/blob/master/adapters/saml/core/src/main/java/org/keycloak/adapters/saml/SamlUtil.java#L113
* https://github.com/keycloak/keycloak/blob/master/saml-core/src/main/java/org/keycloak/saml/processing/core/saml/v2/util/XMLTimeUtil.java#L114

Indagherò ulteriormente, quel `MUST be expressed in UTC form` sembra sia oggetto di diatribe anche per chi ne capisce più di me ([1](https://lists.oasis-open.org/archives/saml-dev/201310/msg00001.html) e [2](https://groups.google.com/g/simplesamlphp/c/7m07m9gLzzA)) ma sicuramente per SPID non c'è dubbio e in generale usare una timezone fissa UTC risolverebbe i problemi di server con timezone differenti.

**Comment by wetfire2k** [comment]
Ciao @nicolabeghin io sto avendo problemi con il validatore. 
Sul mio server ho impostato come timezone Europe/Rome vado al check Response e mi trovo impostato come 
IssueInstant: 2021-06-08T16:30:49+02:00 che è l'orario corrente esatto.
Però il valore che arriva al server è spostato di due ore in avanti. Quindi falliscono i test ed ottengo questo messaggio:
`Received an assertion that is valid in the future. Check clock synchronization on IdP and SP.`
Cosa sbaglio?
Grazie.

**Comment by francescoBonez** [comment]
Ciao utilizzando questo validatore mi fallisce il check sulla 110 in quanto, solo per questa, l'IssueInstant è avanti di 2 ore.
Per le altre validazioni l'IssueInstant tornato è corretto

Francesco

**Comment by damikael** [comment]
@nicolabeghin esiste un canale dove indirizzare le segnalazioni specifiche relative alla tua installazione di spid-saml-check?

**Comment by damikael** [comment]
È disponibile l'ambiente ufficiale https://demo.spid.gov.it liberamente utilizzabile, che offre anche l'utilizzo in modalità "Validator".
Di seguito i riferimenti ai relativi metadata:

Metadata Idp Demo: https://demo.spid.gov.it/metadata.xml
Metadata IdP Validator: https://demo.spid.gov.it/validator/metadata.xml

**Comment by nicolabeghin** [comment]
@damikael ottimo, grazie!!

**Comment by foxbit19** [comment]
Penso che abbia senso riportare questa informazione nel readme del progetto. Posso preparare una PR.

**Comment by damikael** [comment]
Grazie @foxbit19 , 
tuttavia i riferimenti all'ambiente configurato online non sono strettamente correlati al progetto e potrebbero verosimilmente cambiare in futuro.
In ogni caso, sono già indicati alla procedura sul sito ufficiale spid.gov.it:
https://www.spid.gov.it/cos-e-spid/diventa-fornitore-di-servizi/procedura-tecnica/
