### ISSUE TITLE
Abilitare validazione completa - UI

### ISSUE THREAD

**Issue by matfur92** [italia/spid-saml-check#133]
Ciao,

**Descrizione:**
controllando i readme, mi sono accorto che la UI differisce da quella rappresentata negli screenshot.
In particolare facendo riferimento allo screen della documentazione:
![UI di riferimento](https://raw.githubusercontent.com/italia/spid-saml-check/master/gallery/4a.png)
nella UI da me in locale, al di sotto di Check Extra, non è presente nulla:
![screenDiffSamlCheckUI](https://user-images.githubusercontent.com/10245779/112106319-cf646b80-8bad-11eb-8cfd-4171a6efc4e6.png)

**Domande:**
1. Come faccio ad abilitare le sezioni Request, Response,Check Response e Report?
2. In riferimento a https://github.com/italia/spid-saml-check/blob/master/README.it.md : 
`Per utilizzare l'intero set di controlli (il vero e proprio SPID Validator), va scaricato il metadata SAML disponibile all'indirizzo http://localhost:8080/metadata.xml installandolo come un nuovo IdP presso la propria implementazione di SP. `
il comportamento descritto è sintomo che il metadata non è stato letto correttamente come IdP e quindi spid-saml-check non sta funzionando con l'intero set di controlli?

Grazie mille
Matteo

**Comment by nicolabeghin** [comment]
Ciao Matteo
devi importare il `metadata.xml` della tua istanza `spid-saml-check` nel tuo sistema di SSO, e tentare un login verso tale istanza. Quando riceve la richiesta in entrata, vedrai le sezioni request/response. Se può servire, puoi utilizzare www.spid-validator.it (istanza di spid-saml-check che ho esposto pubblicamente proprio per semplificare il tutto).

**Comment by damikael** [comment]
@matfur92 dopo aver configurato il metadata del Validator sul tuo SP in maniera analoga ad un IdP, occorre inviare la authentication request generata dal bottone "Entra con SPID" del tuo SP al Validator.
Il Validator riconosce la authentication request ricevuta e presenta, oltre alla sezione per la validazione del metadata, anche quelle per la validazione della request e delle response.
