### ISSUE TITLE
metadata per privati: element CessionarioCommittente: Schemas validity error 

### ISSUE THREAD

**Issue by StefSoge** [italia/spid-saml-check#136]
Buongiorno,

con un metadata per privati con la sezione billing attiva (<md:ContactPerson contactType="billing">), apparentemente corretto:

```
<md:Organization>
    <md:OrganizationName xml:lang="it">xxxINCxxx</md:OrganizationName>
    <md:OrganizationDisplayName xml:lang="it">xxxINCxxx -</md:OrganizationDisplayName>
    <md:OrganizationURL xml:lang="it">http://www.xxxINCxxx.it</md:OrganizationURL>
  </md:Organization>
  <md:ContactPerson contactType="other">
    <md:Extensions>
      <spid:VATNumber xmlns:spid="https://spid.gov.it/saml-extensions">IT12312312312</spid:VATNumber>
      <spid:Private xmlns:spid="https://spid.gov.it/saml-extensions"/>
    </md:Extensions>
    <md:Company>Mario  Rossi</md:Company>
    <md:EmailAddress>mailto:aRossi@xxxINCxxx.it</md:EmailAddress>
    <md:TelephoneNumber>+39 0700123123</md:TelephoneNumber>
  </md:ContactPerson>
  <md:ContactPerson contactType="billing">
    <md:Extensions>
      <fpa:CessionarioCommittente xmlns:fpa="https://spid.gov.it/invoicing-extensions">
        <fpa:DatiAnagrafici>
          <fpa:IdFiscaleIVA>
            <fpa:IdPaese>IT</fpa:IdPaese>
            <fpa:IdCodice>IT12312312312</fpa:IdCodice>
          </fpa:IdFiscaleIVA>
          <fpa:Anagrafica>
            <fpa:Denominazione>Mario  Rossi</fpa:Denominazione>
          </fpa:Anagrafica>
        </fpa:DatiAnagrafici>
        <fpa:Sede>
          <fpa:Indirizzo>via xxxxVIAxxxxx</fpa:Indirizzo>
          <fpa:NumeroCivico>14</fpa:NumeroCivico>
          <fpa:CAP>06100</fpa:CAP>
          <fpa:Comune>San giustino</fpa:Comune>
          <fpa:Provincia>PP</fpa:Provincia>
          <fpa:Nazione>IT</fpa:Nazione>
        </fpa:Sede>
      </fpa:CessionarioCommittente>
    </md:Extensions>
    <md:Company>Mario  Rossi</md:Company>
    <md:EmailAddress>mailto:aRossi@xxxINCxxx.it</md:EmailAddress>
    <md:TelephoneNumber>+39 0700123123</md:TelephoneNumber>
  </md:ContactPerson>
</md:EntityDescriptor>
```

 il check xsd di spid-saml-check  da questo errore:

> the metadata must validate against the XSD stderr: ./data/https___www_miosito_samlservice/sp-metadata.xml:63: element CessionarioCommittente: Schemas validity error : Element '{https://spid.gov.it/invoicing-extensions}CessionarioCommittente': This element is not expected. Expected is one of ( {https://spid.gov.it/saml-extensions}IPACode, {https://spid.gov.it/saml-extensions}VATNumber, {https://spid.gov.it/saml-extensions}FiscalCode, {https://spid.gov.it/saml-extensions}Public, {https://spid.gov.it/saml-extensions}Private ). stderr: ./data/https___www_miosito_samlservice/sp-metadata.xml fails to validate

**Comment by Gianluke** [comment]
Buongiorno,
mi accodo alla richiesta di chiarimento avendo riscontrato lo stesso problema in fase di aggiornamento e verifica dei metadati per privati con sezione billing.
Aggiungo che il la validazione XSD avviene con successo se invece si seleziona "Metadata deprecato (pre Avviso n.29)".

Grazie.

**Comment by damikael** [comment]
Il problema è stato corretto consentendo la validazione.
Su spid-sp-test, che sarà integrato in spid-saml-check, verranno inseriti controlli più stringenti.
