### ISSUE TITLE
Alcuni check imposti dal tool non vengono poi implementati dagli IdP reali

### ISSUE THREAD

**Issue by fume** [italia/spid-saml-check#137]
Alcuni dei check imposti dallo SPID Quality Assessment Document (https://www.spid.gov.it/assets/download/SPID_QAD.pdf) e, giustamente, verificati tramite il tool spid-saml-check, non corrispondono al comportamento reale degli IdP i quali, probabilmente, non sono sottoposti allo stesso tipo di verifiche.

Ad esempio il check 3.99, ovvero
> Assertion - Elemento AttributeStatement presente, con sottoelemento Attribute non specificato

con risultato atteso ERRORE, non viene rispettato da diversi IdP i quali ritornano Attribute senza valore. 
Di seguito un estratto della sezione AttributeStatement rilasciata dall'idp Sielte:
``` xml
<saml:Attribute Name="companyName"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                            >
                <saml:AttributeValue xsi:type="xs:string" />
            </saml:Attribute>
            <saml:Attribute Name="registeredOffice"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                            >
                <saml:AttributeValue xsi:type="xs:string" />
            </saml:Attribute>
            <saml:Attribute Name="ivaCode"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                            >
                <saml:AttributeValue xsi:type="xs:string" />
            </saml:Attribute>
```
Una risposta del genere causa ovviamente un errore, così come richiesto esplicitamente dal Quality Assessment Document.
Se i check del Quality Assessment document sono obbligatori per superare la validazione tecnica lato AGID, non è accettabile che poi gli IdP non rispettino le suddette regole altrimenti gli utenti otterranno sempre errori in fase di autenticazione.

Domanda: chi sta sbagliando? Sono errate le regole? E' errato il Quality Assessment Document? Sono errate le implementazioni degli IdP?

grazie, saluti

**Comment by damikael** [comment]
Buonasera @fume,
l'estratto di Response da te riportato è diverso rispetto al caso contemplato dal test, come puoi verificare tu stesso analizzando il template xml del test di Response n.99 mostrato da spid-saml-check, che riporto di seguito:

![image](https://user-images.githubusercontent.com/31276401/114412247-34a7ed00-9bad-11eb-97ff-45726183e3f6.png)

In particolare il check 3.99 (test Response spid-saml-check n.99) fanno riferimento ad un elemento Attribute non specificato ovvero mancante del sottoelemento AttributeValue, mentre nell'xml da te riportato l'elemento AttributeValue è sempre presente in ognuno dei tre elementi Attribute, eventualmente vuoto.

Tale comportamento è in linea con quanto previsto da SAML Core 2.0:
_If a SAML attribute includes an empty value, such as the empty string, the corresponding <AttributeValue> element MUST be empty (generally this is serialized as <AttributeValue/>)._

**Comment by fume** [comment]
ciao @damikael , hai perfettamente ragione, non avevo notato che fosse l'AttributeValue ad essere vuoto mentre nel test 3.99 effettivamente è l'element Attribute ad esserlo.

C'è da dire però che anche un elemento Attribute completamente vuoto è accettabile secondo specifica SAML, visto che lo schema è il seguente:
``` xml
<element name="Attribute" type="saml:AttributeType"/>
<complexType name="AttributeType">
<sequence>
<element ref="saml:AttributeValue" minOccurs="0" maxOccurs="unbounded"/>
</sequence>
<attribute name="Name" type="string" use="required"/>
<attribute name="NameFormat" type="anyURI" use="optional"/>
<attribute name="FriendlyName" type="string" use="optional"/>
<anyAttribute namespace="##other" processContents="lax"/>
</complexType>
```
Infatti, sempre la specifica SAML dice che:
> Within an <AttributeStatement>, if the SAML attribute exists but has no values, then the <AttributeValue> element MUST be omitted

Grazie per la celere risposta.
saluti

**Comment by damikael** [comment]
Vero, ma è anche scritto:

> The meaning of an <Attribute> element that contains no <AttributeValue> elements depends on its context.

Attributi che non hanno valore sarebbero attributi assertivi, la cui presenza (o non presenza) è il valore stesso.
In SPID non esistono attributi assertivi ma ogni attributo ha un valore, e la semantica è ben definita nella Tabella attributi SPID. 
Possono, tuttavia, tornare vuoti perché non forniti dall'utente in fase di registrazione oppure perché non si applicano per il tipo di identità digitale.

**Comment by fume** [comment]
grazie @damikael , tutto chiarissimo.

saluti

**Comment by damikael** [comment]
Grazie a te @fume

**Comment by mauromol** [comment]
> Vero, ma è anche scritto:
> 
> > The meaning of an  element that contains no  elements depends on its context.
> 
> Attributi che non hanno valore sarebbero attributi assertivi, la cui presenza (o non presenza) è il valore stesso.
> In SPID non esistono attributi assertivi ma ogni attributo ha un valore, e la semantica è ben definita nella Tabella attributi SPID.
> Possono, tuttavia, tornare vuoti perché non forniti dall'utente in fase di registrazione oppure perché non si applicano per il tipo di identità digitale.

@damikael nella risposta soprastante hai però omesso un dettaglio importante ;-)

Nella sezione 2.7.3.1 della specifica core di SAML 2.0 la frase completa è:

>The meaning of an `<Attribute>` element that contains no `<AttributeValue>` elements depends on
its context. **Within an `<AttributeStatement>`, if the SAML attribute exists but has no values, then the
`<AttributeValue>` element MUST be omitted.** Within a `<samlp:AttributeQuery>`, the absence of
values indicates that the requester is interested in any or all of the named attribute's values (see also
Section 3.3.2.3).

In sostanza, la specifica SAML richiede l'esatto contrario di quello che chiede il validatore in questo momento e la risposta soprastante di Sielte non sarebbe conforme (probabilmente la fanno così proprio per "accontentare" il validatore).
Peraltro, neppure nelle specifiche di SPID e negli avvisi (ti prego di correggermi se sbaglio) io vedo scritto da alcuna parte che l'`<AttributeValue>` debba obbligatoriamente essere presente. Io leggo solo questo, nelle regole tecniche originali:

> - può essere presente l’elemento `<AttributeStatement>` riportante gli attributi identificativi certificati dall’Identity provider. Tale elemento se presente dovrà comprendere:
>   - uno o più elementi di tipo `<Attribute>` relativi ad attributi che l’Identity Provider può rilasciare (cfr. Tabella attributi SPID) su richiesta del Service Provider espressa attraverso l’attributo `AttributeConsumingServiceIndex` quando presente nella
authnrequest;
>   -  per gli elementi `<AttributeValue>` si raccomanda l’uso dell’attributo `xsi:type` attualizzato come specificato nella Tabella attributi SPID;

Pertanto, sempre che non mi sia perso qualcosa, mi chiedo: ha senso aggiungere questo grattacapo inutile e questo ulteriore onere a SP e IdP per ottenere beneficio nullo (peraltro violando quanto dicono le specifiche SAML)?

**Comment by damikael** [comment]
@mauromol , non mi sembra di aver omesso qualcosa,
la parte che evidenzi "**Within an AttributeStatement, if the SAML attribute exists but has no values, then the AttributeValue element MUST be omitted**" era già stata richiamata da @fume mentre quanto relativo ad AttributeQuery non riguarda il nostro caso.
Come ho già risposto, l'AttributeValue deve essere omesso se la presenza dell'attributo indica di per sè il valore stesso, come nel caso di un attributo il cui valore si esprime come Vero/Falso, ma in SPID non esistono attributi di questo tipo, ogni attributo ha un valore che può essere al più vuoto, se non presente lato IdP. Infatti la Response sopra riportata è corretta.
Se così non fosse il SP potrebbe ottenere un set di attributi diverso da quello richiesto.
Non credo sia un grattacapo inutile, piuttosto permette ai SP di essere sicuri della propria implementazione a proprio beneficio e a beneficio degli utilizzatori finali del servizio.

**Comment by mauromol** [comment]
Ciao @damikael, ti ringrazio ancora per il tuo supporto puntuale.
Devo dire però che su questo punto continuo a non essere d'accordo, nonostante lo rispetti e (per forza di cose) debba adeguarmi.
La specifica dice chiaramente che, all'interno di un elemento `<AttributeStatement>` di una `<Assertion>`, se un attributo esiste ma non ha valore, allora l'`<AttributeValue>` va omesso. Facciamo un esempio concreto, sono un persona fisica ma non ho un cellulare (o non ho voluto fornirlo all'IdP in fase di registrazione): il mio SP richiede all'IdP l'attributo `mobilePhone` e l'IdP deve restituirmi un risultato. A mio parere, siamo proprio nel caso in cui l'attributo esiste (perché `mobilePhone` è ben noto ad entrambe le parti), ma è senza valore, dunque `<AttributeValue>` andrebbe omesso. Doverlo obbligatoriamente ricevere come "valore vuoto" anziché come "nessun valore" e dover restituire un errore in caso contrario per poter passare la validazione a mio parere non porta ad alcun reale beneficio e comunque io non trovo traccia di questo requisito nelle specifiche ufficiali (mi cospargo il capo di cenere e mi scuso preventivamente nel caso invece fosse scritto da qualche parte).
Qui siamo nel campo in cui dovrebbe essere l'implementazione sottostante di SAML (o persino il mero parser XML) che dovrebbe garantirmi che, conformemente alla specifica, in entrambi i casi suddetti mi arrivi un attributo senza valore (o valore vuoto). Paradossalmente sarebbe più rischioso accettare un valore vuoto (che può essere erroneamente confuso con un numero di telefono esistente, però di fatto non valido) piuttosto che "nessun valore", dove non c'è rischio di interpretazione.

Capisco il bisogno del rigore, però concedimi lo sfogo: non solo SPID introduce requisiti ulteriori (perlopiù inutili) rispetto alla già articolata e complessa specifica SAML; non solo SPID introduce alcuni requisiti che sono in contrasto con quanto stabilito dalla specifica SAML (e che richiedono di modificare tecnologie rodate e stra-collaudate esistenti che però chiaramente aderiscono alla standard internazionale); ma se pure il validatore si mette ad introdurre vincoli aggiuntivi fuori specifica (ed ancora una volta mi scuso se così non fosse) significa veramente volerci del male :-D

Spero possiate riconsiderare, a beneficio di chi verrà dopo di me :-)

**Comment by damikael** [comment]
Grazie per le tue osservazioni @mauromol, le prenderemo in considerazione internamente.

**Comment by AntonioGiovanniSchiavone** [comment]
Dagli interventi precedenti state supponendo che la mancata indicazione del valore di un attributo SPID (ad es. la PEC) sia un no value. Io credo che, vista l'obbligatorietà degli attributi primari nella definizione di una identità digitale, essa sia stata operativamente e semanticamente intesa come un valore "null", con conseguente obbligatorietà dell'AttributeValue .

A prescindere da ciò, secondo me va considerato un aspetto: al contrario degli ambiti dove solitamente si utilizza il SAML (dove spesso IDP e SP fanno capo allo stesso soggetto, ed utilizzano le stesse soluzioni implementative), la federazione SPID è una federazione estremamente eterogenea , sia dal punto tecnico-implementativo che da quello della tipologia dei soggetti che vi aderiscono.  In base a ciò, credo che un generale ulteriore rafforzamento dei requisiti SAML sia a totale vantaggio della robustezza del sistema.

Nel caso specifico segnalato, come SP mi sento più garantito e facilitato ad avere un match 1:1 fra attributi richiesti e quelli ottenuti (alcuni dei quali eventualmente vuoti), che ottenerne un sottoinsieme senza avere la certezza di un eventuale malfunzionamento dell'IDP, un errato riferimento del set di attributi richiesti o qualunque potenziale problema possa avere causato la ricezione di un set di attributi più ristretto di quello atteso.

**Comment by mauromol** [comment]
> Nel caso specifico segnalato, come SP mi sento più garantito e facilitato ad avere un match 1:1 fra attributi richiesti e quelli ottenuti (alcuni dei quali eventualmente vuoti), che ottenerne un sottoinsieme senza avere la certezza di un eventuale malfunzionamento dell'IDP, un errato riferimento del set di attributi richiesti o qualunque potenziale problema possa avere causato la ricezione di un set di attributi più ristretto di quello atteso.

Ma qui non si tratta di confrontare il set di attributi richiesti rispetto a quelli ottenuti: qui stiamo tagliando in due il capello per stabilire se il valore "assente" (o null, che dir si voglia... anche qui, possiamo filosofeggiare sul significato di null, ma all'atto pratico non c'è grande differenza) possa essere rappresentato mediante l'omissione del tag `<AttributeValue>` oppure obbligatoriamente mediante l'uso di un tag `<AttributeValue>` vuoto. Quale sarebbe il vero vantaggio?
Io vedo solo lo svantaggio di dover andare ad aggiungere un controllo di forma in più sul messaggio in ingresso, che se fosse messo nell'una o nell'altra forma mi starebbe comunque dicendo che il valore per un determinato attributo non c'è (è sconosciuto, è mancante, come preferite).

Sul discorso invece del fatto che l'IdP mi mandi o meno tutti gli attributi richiesti (che è un argomento diverso da quello trattato su questa issue), posto che anche qui SAML prevede l'attributo "required" per specificare se per me (me inteso come SP) un attributo è richiesto obbligatoriamente o meno, perché non concedere all'SP di decidere se essere comunque lenient oppure no? Gli attributi alla fine sono ad uso e consumo dell'SP: il processo di autenticazione ormai è già concluso ed è stato fatto con tutti i sacri crismi. Se poi l'IdP non mi manda, chessò, il numero di cellulare, che io avevo richiesto come opzionale, perché il mio SP non può andare avanti lo stesso, accettando di buon grado? Se poi il cellulare mi serve per forza, allora sarà l'SP a scegliere di notificare all'utente: "senti ciccio, qui a me il cellulare serve, per cui se non mi arriva non posso procedere, eventualmente contatta il tuo IdP"... che poi trattasi dell'esito che adesso sono OBBLIGATO a dare, anche se magari del cellulare potrei eventualmente farne a meno.
