### ISSUE TITLE
Invalid response generated if no attribute is requested

### ISSUE THREAD

**Issue by mauromol** [italia/spid-saml-check#139]
If you try to generate a "correct" `Response` but you don't check any SPID attribute to be returned to the SP (for instance because the original SP request did not specify any `AttributeConsumingServiceIndex`), the generated `Response` is invalid, violating the SAML 2.0 schema, because an empty `<saml:AttributeStatement>` element is included.

If no attribute are to be returned, no `<saml:AttributeStatement>` element should be included in the `Response`.

**Comment by damikael** [comment]
The fix is here: https://github.com/italia/spid-saml-check/commit/9b29f2bc4c4d7959b6c0cbb8d492d5ca3d609796
