### ISSUE TITLE
AuthnContextClassRef can not be null mentre eseguo la validazione delle response

### ISSUE THREAD

**Issue by francescoscialacqua** [italia/spid-saml-check#140]
Nonostante riesca a fare chiamate ed ottenere risposte con l'idt ho problemi con il validatore. Tutti i precedenti test vanno a buon fine ma ho problemi con le response. Tutte mi rispondono questa eccezione ma response inviata dal validatore la proprietà è correttamente popolata.

SimpleSAML\Error\Error: UNHANDLEDEXCEPTION

Backtrace:
1 www/_include.php:17 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: Exception: Request AuthnContextClassRef can not be null. 
Backtrace:
5 /var/www/html/spid-php-master/setup/simplesamlphp/saml2/src/SAML2/Response.php:122 (SAML2\Response::__construct)
4 /var/www/html/spid-php-master/setup/simplesamlphp/saml2/src/SAML2/Message.php:584 (SAML2\Message::fromXML)
3 /var/www/html/spid-php-master/setup/simplesamlphp/saml2/src/SAML2/HTTPPost.php:90 (SAML2\HTTPPost::receive)
2 modules/saml/www/sp/saml2-acs.php:35 (require)
1 lib/SimpleSAML/Module.php:266 (SimpleSAML\Module::process)
0 www/module.php:10 (N/A)

**Comment by damikael** [comment]
Buonasera @francescoscialacqua ,
puoi aprire la presente issue sul repository di spid-php.

 Grazie

**Comment by francescoscialacqua** [comment]
Ok grazie
