### ISSUE TITLE
Response corretta con Spid-Saml-Check - Test 01

### ISSUE THREAD

**Issue by StefanoDevPro** [italia/spid-saml-check#144]
Buongiorno a tutti, durante l'ultima validazione di SPID mi è stato segnalato un problema sull'invio della response corretta (test 01 di Spid-Saml-Check). 
L'utente con il quale dovrei essere autenticato, ha i seguenti dati:

Name: SpidValidator
Family name: AgID
SpidCode: AGID-001
FiscalNumber: TINIT-GDASDV00A01H501J
Email: spid.tech@agid.gov.it

Come mai non mi autentica?

Grazie in anticipo.

**Comment by damikael** [comment]
Buonasera @StefanoDevPro ,
se l'utente non risulta autenticato sul Service Provider, a seguito dell'invio della Response n.1 da spid-saml-check, è un problema relativo al Service Provider. Occorre quindi indagare sul codice del Service Provider che riceve la Response e decodifica il messaggio SAML.

**Comment by StefanoDevPro** [comment]
Grazie @damikael, sto cercando di indagare, ho aperto un issue su italia/spid-php-lib.
