### ISSUE TITLE
spid idp demo: mancano le dichiarazioni dei namespace nel metadata?

### ISSUE THREAD

**Issue by francescm** [italia/spid-saml-check#150]
Il metadata del demo IdP ha come tag di apertura:
```
<md:EntityDescriptor ID="_88611176123669560af9f6c143c1990f9adc5be838" entityID="http://localhost:8080/demo">
[...]
</md:EntityDescriptor>
```
Se faccio il download e lo carico su uno shibboleth-sp-3.2.2 ho `XML error(s) during parsing` fino a che non aggiungo le definizioni dei namespace:
```
<md:EntityDescriptor ID="_8b5f65e6c4e8e02cf584a942fbaf2bdcfdf9773fe2" entityID="http://localhost:8080/demo" xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
[...]
</md:EntityDescriptor>
```

**Comment by damikael** [comment]
Il metadata disponibile in /demo/metadata.xml risulta generato correttamente:

![image](https://user-images.githubusercontent.com/31276401/122639071-13f19b80-d0f8-11eb-8358-c672a8b28e18.png)

Se il problema dovesse persistere, verificare se su linea di comando vengono mostrati errori di runtime.
