### ISSUE TITLE
Formato richiesta non corretto in ambiente demo

### ISSUE THREAD

**Issue by nicolastorgato** [italia/spid-saml-check#160]
Buongiorno,
ho utilizzato lo script spid-php (https://github.com/italia/spid-php) per l'installazione e configurazione di SimpleSAMLphp. Successivamente, ho seguito tutti i passi indicati nell'ambiente demo (https://demo.spid.gov.it/), ma quando tento di inviare una AuthnRequest all' IdP di test, mi viene tornato questo errore: 
```
Formato richiesta non corretto. La AuthnRequest non supera i controlli strict.
Verificare la AuthnRequest tramite uno strumento di validazione.
```

Preciso che nello Spid Validator tutti i controlli vengono superati correttamente. Come posso fare?

**Comment by damikael** [comment]
Buongiorno @nicolastorgato ,
hai eseguito la validazione tramite il validator su https://demo.spid.gov.it/validator?

**Comment by nicolastorgato** [comment]
Certo! Tutti i controlli sono andati a buon fine

**Comment by damikael** [comment]
Per capire meglio mi occorre verificare direttamente sul servizio esposto, contattami su slack oppure inviami per email i riferimenti del service provider.

**Comment by nicolastorgato** [comment]
Va bene, ti ho inviato una mail a michele.damico@linfaservice.it. 
Grazie.

**Comment by damikael** [comment]
Probabilmente l'IdP di test al quale facevi riferimento era l'ambiente deprecato idp.spid.gov.it.
spid-php è stato ora aggiornato per configurare in fase di setup i riferimenti a demo.spid.gov.it.
Riesegui la procedura di installazione e verifica se ora la request funziona correttamente.

**Comment by almaxstudio** [comment]
@damikael  e @nicolastorgato, il problema è stato risolto?

**Comment by simonescalaGT** [comment]
Avete risolto questo problema?

**Comment by alessandro-chiodaroli** [comment]
Mi trovo nella stessa situazione con la libreria [spid-php-lib](https://github.com/italia/spid-php-lib). 
Ho eseguito con successo le validazioni ma all'atto di eseguire la richiesta ottengo il medesimo errore.

E' stata individuata l'origine del problema?
Grazie.

**Comment by nicolastorgato** [comment]
Ciao a tutti! 

Il problema relativo a questo issue l'ho risolto installando l'ultima release della libreria spid-php. 
Inoltre, l'errore mi veniva dato tentando di fare il login attraverso l'interfaccia di SimpleSamlPhp, mentre per fare le prove a quanto pare bisogna fare il login attraverso l'apposito bottone che viene fornito già con l'installazione della libreria (la pagina è "https://yoursite/login-spid.php").

Nonostante questo, continuo ad avere problemi di gestione delle sessioni/cookie (errore: State not found).

**Comment by damikael** [comment]
Confermo, come verificato con @nicolastorgato, che è stato sufficiente aggiornare l'installazione di spid-php.
Come indicato nel README, spid-php può generare automaticamente, se selezionato in fase di installazione, il file login-spid.php che contiene il codice di esempio per l'integrazione del bottone SPID. 
Occorre fare riferimento a tale file per utilizzare spid-php come SDK in quanto spid-php oltre al processo di installazione, introduce, rispetto a simpleSAMLphp, tutte le patch che garantiscono il rispetto dei requisiti SPID. 
Inoltre, aggiunge ulteriori funzionalità ai metodi di login, come, ad esempio, l'autenticazione con identità SPID uso professionale.

Il problema indicato da @nicolastorgato, invece, si verifica al termine del processo di autenticazione verso l'IdP ed è correlato alla perdita della sessione sul SP. Tuttavia non è relativo a questa issue, pertanto la presente può essere considerata risolta.
