### ISSUE TITLE
Attributo fiscalNumber senza prefisso TINIT-

### ISSUE THREAD

**Issue by paoloconti-webloomit** [italia/spid-saml-check#161]
Buongiorno, segnalo che https://demo.spid.gov.it invia Response con l'attributo fiscalNumber senza il prefisso TINIT-

**Comment by damikael** [comment]
Corretto con le ultime commit.
Ambiente online https://demo.spid.gov.it aggiornato

**Comment by MTurraPpa** [comment]
Ma qual'è il significato e l'utilità del prefisso `TINIT-` ?

**Comment by damikael** [comment]
Taxpayer Identification Number: Codice di identificazione fiscale utilizzato a livello internazionale 
In Italia corrisponde al codice fiscale anticipato dal prefisso TINIT- (Taxpayer Identification Number Italy)

Rif. https://ec.europa.eu/taxation_customs/online-services/online-services-and-databases-taxation/tin-taxpayer-identification-number_en
