### ISSUE TITLE
Errore nella validazione della AuthnRequest - Check Strict - Test if the XSD validates and if the signature is valid

### ISSUE THREAD

**Issue by davidegallesio** [italia/spid-saml-check#163]
Ciao,
ho riscontrato questo errore che sembra legato il codice utilizzato dallo spid-saml-check nell'ultima validazione _Check Strict_ - 
_Test if the XSD validates and if the signature is valid_ della request

The AuthnRequest must validate against XSD and must have a valid signature stderr: ./script/check-request-xsd-and-signature.sh: line 17: $’\r’: command not found stderr: ./script/check-request-xsd-and-signature.sh: line 19: $’\r’: command not found stderr: ./script/check-request-xsd-and-signature.sh: line 22: $’\r’: command not found stderr: ./script/check-request-xsd-and-signature.sh: line 25: $’\r’: command not found stderr: cat: ‘./data/https___paghepa_alma_spa_it’$’\r’’/SAMLRequest.authn’$’\r’’.request.txt’: No such file or directory stderr: ./script/check-request-xsd-and-signature.sh: line 70: syntax error near unexpected token elif' stderr: ./script/check-request-xsd-and-signature.sh: line 70: elif [ “${CTX}” == “logout” ]; then ’

![image](https://user-images.githubusercontent.com/76485843/127295338-0f2e7ce5-40f5-4dd8-9676-a8e8568b1033.png)

questa è la mia request
`<?xml version="1.0" encoding="UTF-8"?>
<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" AssertionConsumerServiceIndex="0" AttributeConsumingServiceIndex="1" Destination="https://localhost:8080/samlsso" ForceAuthn="true" ID="_7599e532-f284-430c-869a-0c0f49192522" IssueInstant="2021-07-28T09:02:27.185Z" Version="2.0">
    <saml2:Issuer xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" NameQualifier="http://pc94">
        http://pc94
    </saml2:Issuer>
    <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:SignedInfo>
            <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
            <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
            <ds:Reference URI="#_7599e532-f284-430c-869a-0c0f49192522">
                <ds:Transforms>
                    <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                    <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
                </ds:Transforms>
                <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
                <ds:DigestValue>
                    14sf5d4WXCdxcJLMdCUvFbRkYUNFzVJbrw37YakRAI0=
                </ds:DigestValue>
            </ds:Reference>
        </ds:SignedInfo>
        <ds:SignatureValue>
            xdiA+9x23evSrImRomwH/9ZmWXQqupQaqxAocdxH9KNNw8VXik9BUzwBC85jvqqW6IZ1T64gyVVhOP+NDCMXEh5e3VWq1GV1jUmvvna+1rMFlJ2gqBV4iYrGS6ayI8/sQ8zC6IdceYCnU0h25AHLbRbZkJamodET/qtlcLd2YmmINHtf0KvPgOebUJPUt0VWbcHc5b3X2XQaLtHbZwGbJ6CBA6wFNen5eidJ0pSaKVZs/c0oeE6vNKm2mZz0tPgy9f7pLHaFw+iDJgycCilMV22Sc0WVa5/jNHy2yJTYaMo4+LvVe5GyxPi5CPkBWtzg/jxU7IwPS2vROSIDpKz/mQ==
        </ds:SignatureValue>
        <ds:KeyInfo>
            <ds:KeyValue>
                <ds:RSAKeyValue>
                    <ds:Modulus>
                        zAfQ3Hi3tnQd9iz/qGz4zl5YZxbc59AwQAKF5gRswOltY34vBuI6RuM9stshFB2rnVMtKHh4EDou
uEaa73A5VqtrPnIZws56Zy5wkDzDskrSzqeqmK9fSCFvqL/5c+EE2VDNMLBGmV6mC/UNA+qIFY7/
LetE73yNzh4ospvfuEq9JLA2x8Sw09bBHS2SrfT/CvRPpAgcdONEaS1BPz6EeITMTb7nVUklxT+3
4yyJmH/54I3m2Bb+R4ZAq18Jy99kSyjBHAE/ms86Q0lEQ3SpsFpHjo/SVVIPp3/zet0zyBz7v4Pw
I/Lb2wVkL4BTSsAw5e3NDcSBvHAuKiu0MDM/fQ==
                    </ds:Modulus>
                    <ds:Exponent>
                        AQAB
                    </ds:Exponent>
                </ds:RSAKeyValue>
            </ds:KeyValue>
            <ds:X509Data>
                <ds:X509Certificate>
                    MIIIIzCCBgugAwIBAgIIARlR2HSoFqcwDQYJKoZIhvcNAQENBQAwgegxCzAJBgNVBAYTAklUMQ0w
CwYDVQQHDARSb21lMSYwJAYDVQQKDB1BZ2VuemlhIHBlciBsJ0l0YWxpYSBEaWdpdGFsZTEwMC4G
A1UECwwnU2Vydml6aW8gQWNjcmVkaXRhbWVudG8gZSBwcm9nZXR0byBTUElEMSkwJwYDVQQDDCBQ
cm9nZXR0byBTUElEIC0gU29nZ2V0dGkgcHJpdmF0aTEpMCcGCSqGSIb3DQEJARYacHJvdG9jb2xs
b0BwZWMuYWdpZC5nb3YuaXQxGjAYBgNVBAUTEVZBVElULTk3NzM1MDIwNTg0MB4XDTIxMDcxNTAw
MDAwMFoXDTM2MDcxNDIzNTk1OVowgc8xHDAaBgNVBAMME0FsbWEgQ2VudHJvIFNlcnZpemkxCzAJ
BgNVBAYTAklUMRswGQYDVQQHDBJWaWxsYW5vdmEgTW9uZG92w6wxCzAJBgNVBAgMAkNOMRQwEgYD
VQQKDAtBbG1hIFMucC5BLjEaMBgGA1UEYQwRVkFUSVQtMDA1NzIyOTAwNDcxJDAiBgNVBFMMG2h0
dHBzOi8vcGFnaGVwYS5hbG1hLXNwYS5pdDEgMB4GCSqGSIb3DQEJARYRcG9zdGFAYWxtYS1zcGEu
aXQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDMB9DceLe2dB32LP+obPjOXlhnFtzn
0DBAAoXmBGzA6W1jfi8G4jpG4z2y2yEUHaudUy0oeHgQOi64RprvcDlWq2s+chnCznpnLnCQPMOy
StLOp6qYr19IIW+ov/lz4QTZUM0wsEaZXqYL9Q0D6ogVjv8t60TvfI3OHiiym9+4Sr0ksDbHxLDT
1sEdLZKt9P8K9E+kCBx040RpLUE/PoR4hMxNvudVSSXFP7fjLImYf/ngjebYFv5HhkCrXwnL32RL
KMEcAT+azzpDSURDdKmwWkeOj9JVUg+nf/N63TPIHPu/g/Aj8tvbBWQvgFNKwDDl7c0NxIG8cC4q
K7QwMz99AgMBAAGjggLmMIIC4jAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBSQmj6H3o5Pr/dOdjPh
FBx4+RZ7gDAfBgNVHSMEGDAWgBScRTDETQ+g+iYPqdb8INYHbM5kVjAOBgNVHQ8BAf8EBAMCBsAw
FgYDVR0SBA8wDYILc3BpZC5nb3YuaXQwQwYDVR0fBDwwOjA4oDagNIYyaHR0cHM6Ly9laWRhcy5h
Z2lkLmdvdi5pdC9jcmwvY3JsX1NQSURfcHJpdl9TQS5jcmwwNwYIKwYBBQUHAQEEKzApMCcGCCsG
AQUFBzABhhtodHRwczovL29jc3BfU0EuYWdpZC5nb3YuaXQwggHXBgNVHSAEggHOMIIByjAJBgcE
AI5GAQYCMIGVBgQrTBAGMIGMMEQGCCsGAQUFBwICMDgaNkVsZWN0cm9uaWMgY2VydGlmaWNhdGUg
Y29uZm9ybWluZyB3aXRoIEFHSUQgR3VpZGVsaW5lczBEBggrBgEFBQcCAjA4GjZDZXJ0aWZpY2F0
byBlbGV0dHJvbmljbyBjb25mb3JtZSBhbGxlIExpbmVlIGd1aWRhIEFnSUQwewYGK0wQBAMBMHEw
NQYIKwYBBQUHAgIwKRonU1BJRDogZm9ybml0b3JlIGRpIHNlcnZpemkgKFNQKSBwcml2YXRvMDgG
CCsGAQUFBwICMCwaKlNQSUQ6IHByaXZhdGUtc2VjdG9yIFNlcnZpY2UgUHJvdmlkZXIgKFNQKTAI
BgYEAI96AQMwTQYEK0wQBDBFMEMGCCsGAQUFBwIBFjdodHRwczovL2VpZGFzLmFnaWQuZ292Lml0
L2Nwcy9BZ0lEX2VJREFTX3Jvb3RDQV9jcHMucGRmME8GBgQAjkYBBTBFMEMGCCsGAQUFBwIBFjdo
dHRwczovL2VpZGFzLmFnaWQuZ292Lml0L2Nwcy9BZ0lEX2VJREFTX3Jvb3RDQV9jcHMucGRmMBEG
CWCGSAGG+EIBAQQEAwIABzANBgkqhkiG9w0BAQ0FAAOCAgEAeKrSVRZwTA89YGLq2Brat+KhNSGy
yW92Ty1naZEY6wbGZy5hJ3t34XQfyf9fwWmTneuJhRgwd0BY17pAbJxRP1qMtHBa4xuxH9S3qxQZ
SYd72oY8sIeuxvgrW/18AtCJliYFF45r0OhhhJLQncketP1oFnQH19ImFuxPQGEEk7NKKt4jGxDs
vximNucnvTeFAvjHpKOEDn+rao6koGdXVfQ6jP3j94YNrUlK7Qg2awxJd3LhDVpcXVQZUSGGvEnD
oVtdfNjV/esD2r8cA58x95tcPgx/tBtJnB9A9I4ggEbrQK9iVaOsDPjvN9EJqnO9iLqje5RzXkla
oHi2lCws0Jfp4tj/vNHgbQtOKdnlmN2fh0MrizLHZjBcQEju0Rc585LoazafNpp6vocs/WfD6tKp
Z5HxXWc+ZyKlAMD5aTnPvlAd5wHLWPtwnrGTFe9NYH0Vqr//5+TZ0Q3shMQ8lxrFhCBeSotw7NwA
/ytvpDLqfRsAs6ODxMivs5mjrMfP/1JLfT0LTdtAhyrAALESSdoea2f9uiqsyu+d1w5QqpbpqeQ9
xRskmXzeHmWQzNfx61ayfZwH93ZanrOv/iizNljILfrCwdWTwjhdpg/H9PwojWPRC2r42kn4o61O
5DfOVJmDNzOlc80YPNoaAuS7Uioj//H7LaATLoGiF+2wnwg=
                </ds:X509Certificate>
            </ds:X509Data>
        </ds:KeyInfo>
    </ds:Signature>
    <saml2p:NameIDPolicy xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient"/>
    <saml2p:RequestedAuthnContext xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" Comparison="minimum">
        <saml:AuthnContextClassRef xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">
            https://www.spid.gov.it/SpidL1
        </saml:AuthnContextClassRef>
    </saml2p:RequestedAuthnContext>
</samlp:AuthnRequest>`

Inoltre nell'ultima versione utilizzando lo spid-saml-check  come IDP demo, questo errore è bloccante.

Il metadata è stato comunque validato correttamente dall'AGID.

Grazie,

Davide Gallesio

**Comment by simonescalaGT** [comment]
Ho lo stesso identico errore. 
Non riesco per questo a usare correttamente l'ambiente demo

**Comment by davidegallesio** [comment]
Nella nuova versione 1.80 il problema non c'è più.
