### ISSUE TITLE
Tag 1.8.0 su Docker Hub

### ISSUE THREAD

**Issue by ilgrosso** [italia/spid-saml-check#169]
Controllando su [Docker Hub](https://hub.docker.com/r/italia/spid-saml-check/tags?page=1&ordering=last_updated) sembra che l'ultima release disponibile sia la 1.7.1 mentre qui su GitHub c'è https://github.com/italia/spid-saml-check/releases/tag/v.1.8.0

**Comment by peppelinux** [comment]
aggiornato
https://hub.docker.com/r/italia/spid-saml-check

d'ora in poi ogni qualvolta @damikael taggerà una nuova release in automatico verrà pubblicata l'immagine docker su dcker hub
