### ISSUE TITLE
Login con ambiente demo

### ISSUE THREAD

**Issue by Antonyclar** [italia/spid-saml-check#171]
Ciao,
ho un dubbio per quanto riguarda la procedura di Login in ambiente demo. 
Ho validato correttamente sia il metadata del mio SP che la request tramite il Validator nel mio ambiente locale. A questo punto volevo testare la mia implementazione inserendo nella schermata di login uno fra gli utenti previsti dall'ambiente (ad esempio: cesare - password123) cliccando poi su Entra con SPID.
A quel punto dovrei rimandare ad una pagina web (quella indicata anche nel metadata). A questo punto la mia domanda è: l'ambiente Demo prevede già una pagina da specificare che segue la fase di login?

Grazie.
Antonio.

**Comment by peppelinux** [comment]
Ciao Antonio,
fai un esempio, non ho capito perdonami

**Comment by Antonyclar** [comment]
Certo Giuseppe, ci provo.
Al momento sto lavorando con l'ambiente Demo ed ho validato con successo il mio metadata e la request ma adesso vorrei validare la response per verificarne la correttezza.
Al momento per effettuare il login eseguo queste operazioni:
- accedo sulla pagina https://localhost:8080/demo/start 
- inserisco le credenziali cesare/password123 
- confermo l'invio dei dati alla pagina https://localhost:8080/demo/login

Nel momento in cui il login ha un qualche tipo di fallimento ho un errore visibile sulla pagina delle credenziali. Cosa succede invece quando il login ha successo? L'ambiente demo ha una pagina a cui rimanda quando l'esito del login ha avuto successo o dovrò crearne una io per il test?
Questa informazione la chiedo anche perchè dovendo testare la response, l'ambiente demo mi chiede di innviare la request al SP (tasto verde sulla barra laterale a dx) e lì dovrò fornire l'indirizzo che accoglie l'operazione HTTP-POST che al momento non ho.

Grazie,
Antonio.

**Comment by peppelinux** [comment]
Demo non è molto eloquente, autenticati su https://localhost:8080 e i metadata li trovi su /metadata.xml

Accederai all'interfaccia/idp di collaudo e avrai tutto più chiaro

**Comment by Antonyclar** [comment]
Scusami Giuseppe ma continuo a non capire perciò provo a porre la domanda diversamente.
Io uso già l'ambiente demo (è l'unico che mi permette di testare metadata/request/response).

Obiettivo attuale: **testare la response**. 
Per fare questo vi è la sezione apposita dell'ambiente demo che genera un SAML ricavandone i vari parametri necessari. A questo punto l'ambiente ha un pulsante che dice "Invia response al Service Provider" ossia la URL che dovrà ricevere la risposta dall'IdP e ciò implica che debba specificare un indirizzo. 
Domanda: quale è l'inidirizzo corretto da specificare quando si utilizza questo tipo di ambiente? E' per caso https://demo.spid.gov.it/samlsso ?

Antonio.

**Comment by damikael** [comment]
Buonasera @Antonyclar ,
cerco di disambiguare la questione. L'applicativo spid-saml-check può operare in due modalità: Demo e Vaidator.

La modalità **Demo** si comporta come un IdP e consente di effettuare l'autenticazione con utenti fittizi come nella schermata seguente:

![image](https://user-images.githubusercontent.com/31276401/133300129-25ae6358-c3b9-442c-8dd9-328ea22cb256.png)

La modalità **Validator**, invece, offre un maggiore controllo, permettendo di impostare ogni singolo parametro della Response che si sta inviando e offre una interfaccia come nella seguente schermata:

![image](https://user-images.githubusercontent.com/31276401/133300352-39e2c309-e4f8-4e1d-8c80-be27ab7108f2.png)

L'applicativo spid-saml-check è installato per l'utilizzo pubblico su https://demo.spid.gov.it
In particolare configurando sul proprio SP il metadata disponibile su https://demo.spid.gov.it/metadata.xml si può utilizzare la modalità Demo;
mentre configurando sul proprio SP il metadata disponibile su https://demo.spid.gov.it/validator/metadata.xml si può utilizzare la modalità Validator.

In entrambi i casi, la location (indirizzo) alla quale viene spedita la Response sul SP è definita nel metadata del SP all'elemento AssertionConsumerService (il cui index o la cui location deve essere specificata poi sulla AuthnRequest inviata dal SP).

Il metadata del SP deve essere configurato su https://demo.spid.gov.it/validator nella sezione metadata.

Michele
