### ISSUE TITLE
Error: ENOENT: no such file or directory, open '../data/https___spid_*****_it/sp-authn-request-strict.json'

### ISSUE THREAD

**Issue by Andrea-Perelli** [italia/spid-saml-check#175]
Sto implementando l'accesso con SPID, attraverso l'`sdk` per `AspNetCore`. Ho scaricato l'ambiente demo tramite il container Docker e sono riuscito a validare i matadati del Service Provider correttamente con il validator.

Nel momento in cui cerco di **validare la richiesta di auth**, l'interfaccia va il loop:

![image_2021_08_26T12_43_16_317Z](https://user-images.githubusercontent.com/26798984/130988142-e33cce78-6081-4032-bb52-e0f23a2c2942.png)

Nella CLI di Docker c'è lo stack trace dell'errore:

![image_2021_08_26T13_26_05_884Z](https://user-images.githubusercontent.com/26798984/130987921-87b97b19-7ad0-4fa7-b07a-2a01f2ac0bf3.png)

Inoltre, se provo a testare l'accesso, attraverso gli account fittizi di login ottengo:

![image_2021_08_26T12_42_36_245Z](https://user-images.githubusercontent.com/26798984/130987371-d5f94442-3da3-4b4d-ac8b-6c405ca6ac3a.png)

**SDK di sviluppo**: [link](https://github.com/italia/spid-aspnetcore)
**Versione SPID Saml Check**: 1.8

**Comment by damikael** [comment]
Il problema potrebbe essere correlato al metadata. 
Potreste inviarmi i metadata all'indirizzo michele.damico@agid.gov.it in modo tale da analizzare meglio il problema.
Grazie

**Comment by damikael** [comment]
Provate a ricaricare il metadata nella sezione del validator,
quindi rieseguire i test.

**Comment by damikael** [comment]
Probabilmente correlato a:
https://github.com/italia/spid-sp-test/issues/102
https://github.com/italia/spid-sp-test/issues/104

Occorre aggiornare all'ultima versione e ricompilare l'immagine docker.

**Comment by santesem-links** [comment]
come mai è segnato come chiuso?
Io ho esattamente lo stesso problema pur avendo scaricato l'ultima versione (sia la 1.8.1 che direttamente il ramo master)

**Comment by NandoMuttley** [comment]
Editando il docker file e forzando alla versione v0.9.19 la issue segnalata non si presenta più

```
# Install spid-sp-test
RUN apt-get install -y \
        libxml2-dev \
        libxmlsec1-dev \
        libxmlsec1-openssl \
        xmlsec1 \
        python3-pip

RUN pip3 install spid-sp-test==v0.9.19 --upgrade --no-cache

# Node.js
```
