### ISSUE TITLE
GUI: TypeError: Cannot read property 'entityType' of undefined 

### ISSUE THREAD

**Issue by amusarra** [italia/spid-saml-check#183]
Con riferimento all'ultima versione dell'ambiente (v1.8.1), segnalo che il caricamento del file di Metadata SPID di Banca d'Italia (https://www.bancaditalia.it/footer/servizispid/metadata-spid-signed.xml) e successivo check, generano l'errore in oggetto, di cui a seguire è mostrato lo screenshot (lo stesso errore avviene anche sull'attuale ambiente di live di demo https://demo.spid.gov.it/).

<img width="807" alt="Schermata 2021-09-28 alle 17 31 47" src="https://user-images.githubusercontent.com/708110/135121898-65c64e96-cebf-4d70-8e1e-3bdac2beee68.png">

Parto anche dal presupposto che so che il file di Metadata non è effettivamente valido, e lo si può vedere eseguendo il comando a seguire (direttamente dal container docker) `spid_sp_test --metadata-url https://www.bancaditalia.it/footer/servizispid/metadata-spid-signed.xml --debug ERROR` di cui a seguire riporto l'output

```
ERROR:spid_sp_test.metadata:SpidSpMetadataCheck.test_contactperson_email: The //ContactPerson/EmailAddress element MUST be present
ERROR:spid_sp_test.metadata:The //ContactPerson/EmailAddress element MUST be present
ERROR:spid_sp_test.metadata:SpidSpMetadataCheck.test_Contacts_PubPriv: ContactPerson MUST be present
ERROR:spid_sp_test.metadata:ContactPerson MUST be present
ERROR:spid_sp_test.metadata:SpidSpMetadataCheck.test_Contacts_PubPriv: Only one ContactPerson element of contactType "other" MUST be present
ERROR:spid_sp_test.metadata:Only one ContactPerson element of contactType "other" MUST be present
ERROR:spid_sp_test.metadata:SpidSpMetadataCheck.test_extensions_public_private: Missing ContactPerson/Extensions/Public, this element MUST be present
ERROR:spid_sp_test.metadata:Missing ContactPerson/Extensions/Public, this element MUST be present
Spid QA: executed 226 tests, 4 failed. 0 warnings.
```

Il comportamento corretto delle GUI, dovrebbe essere quello di visualizzare il report dei test di validazione, al contrario, si ottiene l'errore descritto.

Segnalo inoltre che lo stesso problema accade anche con altri metadata, come per esempio questo https://dichiarazioneprecompilatafe.agenziaentrate.gov.it/metadata

**Comment by plunix** [comment]
Nel mio caso il problema era dovuto ad una discrepanza tra il valore dell'attributo "Location" del field "AssertionConsumerService" nel metadata.xml e il valore di AssertionConsumerServiceURL inviato in authrequest. Corretto il valore nel metadata.xml, la UI parsava correttamente il metadata.xml

**Comment by damikael** [comment]
Vedi #236
