### ISSUE TITLE
Banner Container Docker: Versione di progetto/prodotto errata

### ISSUE THREAD

**Issue by amusarra** [italia/spid-saml-check#184]
Per segnalare che la versione di progetto indicata sul banner del container riporta una versione errata. Al momento l'ultima release è la versione 1.8.1, mentre il banner mostra versione 1.8.0, come indicato dalla figura a seguire.

<img width="1439" alt="Schermata 2021-09-28 alle 18 05 33" src="https://user-images.githubusercontent.com/708110/135124717-49c91a43-fddc-486f-9fd4-84d276e725a2.png">

Come feature sarebbe utile che sul banner venisse indicata anche la versione del componente spid-sp-test

**Comment by peppelinux** [comment]
vedi qui
https://github.com/italia/spid-saml-check/issues/174

**Comment by amusarra** [comment]
> vedi qui
> 
> https://github.com/italia/spid-saml-check/issues/174

Grazie per quanto riguarda la feature.
In ogni caso la versione mostrata è errata.

**Comment by amusarra** [comment]
@peppelinux questa issue è risolta dalla PR #189 per cui chiudo questa issue.
