### ISSUE TITLE
Cambiare host idp

### ISSUE THREAD

**Issue by lespaul121** [italia/spid-saml-check#188]
Salve,

ho instllato spid-saml-check su una macchina linuix remota. Come faccio a cambiare l'ip che compare nel metadata con l'indirizzo ip della macchina? Quali file bisogna modificare? Ho modificato idp.json, idp-demo.json e server.json ma nel metadata continua a comparire localhost.

Grazie a ch mi da una mano

**Comment by foxbit19** [comment]
Ciao, i file sono corretti. Prova a rieseguire il build del progetto e dovrebbe funzionare.
