### ISSUE TITLE
Immagine docker ultima versione non funzionante

### ISSUE THREAD

**Issue by Almax84** [italia/spid-saml-check#196]
Buongiorno,
a seguito dell'aggiornamento del tool di test di qualche giorno fa si riscontra
1) Il docker run dell'immagine presente su docker.io ha problemi di startup. Il container infatti fallisce con errore:
Error: Cannot find module 'express'
(Allego errore completo)
![99](https://user-images.githubusercontent.com/5910516/140912854-2f442134-5cc5-45db-92c1-714ec520ed4b.png)

Il test è stato effettuato su:
Linux / Windows -> Docker

**Comment by pampua84** [comment]
Riscontro lo stesso problema.

**Comment by maxi-bnd** [comment]
Stesso problema su Windows con Docker Desktop 4.2.0 (70708)

**Comment by lussoluca** [comment]
Sembra che il problema sia dovuto al fatto che la v.1.8.2 usa erroneamente node 8 come immagine Docker di base (invece v1.8.1 usava node12), però vedo che è stato risolto in master. Andrebbe fatta una nuova release :-)

**Comment by Baldoma** [comment]
+1

**Comment by sisinio** [comment]
Il problema si risolve aggiungendo alcuni pacchetti mancanti, soprattutto serve il compilatore per Rust:

`
# Update and install utilities
RUN apt-get update && apt-get install -y \
        wget \
        curl \
        unzip \
        libxml2-utils \
        libxml2-dev \
        libxmlsec1-dev \
        libxmlsec1-openssl \
        xmlsec1 \
        openssl \
        python3 \
        python3-pip \
        libffi-dev \
        python3-virtualenv \
        build-essential  \
        python3-dev cargo

RUN pip3 install setuptools_rust cryptography
`

**Comment by sebbalex** [comment]
+1

**Comment by damikael** [comment]
Il problema è risolto con le ultime versioni
