### ISSUE TITLE
 Cannot find module 'express' - immagine tag latest (2db48cca577afe15617948ab6525dcf72ef96f)

### ISSUE THREAD

**Issue by dynamicaict** [italia/spid-saml-check#198]
Buongiorno, ho provato a lanciare l'immagine direttamente a partire da quella presente su DockerHub con il tag latest. Ho provato inoltre ad eseguire la build e poi a lanciare l'immaagine ma ricevo sempre l'errore riportato di seguito in fase di run. L'errore sembra riguardare l'assenza del modulo express tra i moduli installati. Controllando però il file package.json del modulo server all'indirizzo https://github.com/italia/spid-saml-check/blob/master/spid-validator/server/package.json vedo che la dipendenza è dichiarata.

Di seguito l'istruzione eseguita l'errore corrispondente:

 docker run -t -i -p 8443:8443 italia/spid-saml-check

> spid-validator@1.0.0 start-prod /spid-saml-check/spid-validator
> node server/spid-validator.js

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'express'
Require stack:
- /spid-saml-check/spid-validator/server/spid-validator.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/spid-saml-check/spid-validator/server/spid-validator.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/spid-saml-check/spid-validator/server/spid-validator.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! spid-validator@1.0.0 start-prod: `node server/spid-validator.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the spid-validator@1.0.0 start-prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-12T14_41_45_786Z-debug.log

**Comment by lscorcia** [comment]
+1 per questo errore.

**Comment by svilsoftwarescf** [comment]
+1

**Comment by pampua84** [comment]
+1

**Comment by pampua84** [comment]
+1

**Comment by maxi-bnd** [comment]
stessa segnalazione del #196. riporto lo stesso errore: Windows con Docker Desktop 4.2.0 (70708)

**Comment by Baldoma** [comment]
+1

**Comment by lpradovera** [comment]
+1

**Comment by damikael** [comment]
Il problema è risolto con le ultime versioni
