### ISSUE TITLE
SAML response not aligned to AttributeConsumingServiceIndex

### ISSUE THREAD

**Issue by psmiraglia** [italia/spid-saml-check#21]
When the SP metadata declares multiple `AttributeConsumingService` elements, the generated SAML responses contain an attributes set that is not aligned with the requested `AttributeConsumingServiceIndex`.

**Comment by damikael** [comment]
Already fixed:
https://github.com/italia/spid-saml-check/blob/04fe06aed3e548617560050e2cba03ec00d0a784/spid-validator/server/api/response.js#L62
