### ISSUE TITLE
Error: Cannot find module 'express'

### ISSUE THREAD

**Issue by mperudirectio** [italia/spid-saml-check#211]
Salve,
stiamo provando ad avviare localmente spid-saml-check tramite Docker.
seguendo la documentazione nel readme, lanciando semplicemente la prima linea di comando:
`docker run -t -i -p 8443:8443 italia/spid-saml-check` va subito in errore l'installazione dando il seguente messaggio:

```
> spid-validator@1.0.0 start-prod /spid-saml-check/spid-validator
> node server/spid-validator.js

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'express'
Require stack:
- /spid-saml-check/spid-validator/server/spid-validator.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/spid-saml-check/spid-validator/server/spid-validator.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/spid-saml-check/spid-validator/server/spid-validator.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! spid-validator@1.0.0 start-prod: `node server/spid-validator.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the spid-validator@1.0.0 start-prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-11T14_10_11_953Z-debug.log
```
sembra che quando viene lanciata l'istanza manchi express nel package.json, ma la configurazione sta nel dockerfile e istanziando il container tramite `italia/spid-saml-check` non saprei come andare a cambiare configurazione.
Ho anche visto le altre issue inerenti a questo argomento, e volevo sapere se ci sono possibilità di fixare la cosa anche nella versione 1.8.2. (ho forzato la pull dell'immagine nella versione 1.8.1 e funziona)

Grazie mille

**Comment by sebbalex** [comment]
+1

**Comment by spokke** [comment]
ho clonato il repo e rebuildato l'image mettendo nel docker file 
FROM node:latest
al posto di 
FROM node:12-bullseye-slim


una volta buildata l'img avviala con  
docker run -t -i -p 8443:8443 spid-saml-check

**Comment by damikael** [comment]
Il problema è risolto con le ultime versioni
