### ISSUE TITLE
Mancata presenza menu validazione della richiesta AuthRequest

### ISSUE THREAD

**Issue by cretara** [italia/spid-saml-check#231]
Buongiorno.
segnalo la mancanza della voce di menu della validazione della AuthRequest (sia locale che remoto) come da screenshot seguente
![image](https://user-images.githubusercontent.com/13657261/192724976-5128f4ee-9de7-4f02-8347-ded0bdd084fb.png)

Tuttavia nella documentazione tale voce di menu risulta essere presente (voce secondo livello nel menu "Check request"):
https://github.com/italia/spid-saml-check/blob/master/doc/img/2.png

**Comment by davide1945** [comment]
+1

**Comment by mbuferli** [comment]
+1, purtroppo siamo fermi a quest'ultimo passaggio

**Comment by nunzionapoli** [comment]
Questa voce si abilita quando il validator viene "invocato" attraverso una request SAML. Quindi bisogna configurare i metadata del validator nel proprio IDP e inviare una request all'endpoint del validator

**Comment by damikael** [comment]
Buongiorno @cretara ,
sul README, è già indicato come utilizzare il tool:

> The application spid-validator, if invoked as a web application as is, provides "basic", formal validation of a Service Provider's SAML metadata.
> 
> In order to unleash the full set of SPID compliance tests (the proper SPID Validator), **retrieve the metadata of SPID Validator at https://localhost:8443/metadata.xml and configure it on as a new Identity Provider (IdP) under your Service Provider (SP) implementation. [...] To use the SPID Validator the AuthnRequest are thus sent from your SP**

https://github.com/italia/spid-saml-check#how-to-use-it-as-a-spid-validator
https://github.com/italia/spid-saml-check/blob/master/README.it.md#come-usare-spid-validator

In ogni caso, è sempre ben accetto qualsiasi contributo proposto come pull request, che può rendere di più facile lettura la documentazione e l'utilizzo dello strumento.

Grazie
