### ISSUE TITLE
Validation test #25

### ISSUE THREAD

**Issue by repsem** [italia/spid-saml-check#237]
Ciao,
il test di validazione 25 sembrerebbe generare la stessa Response del test numero 22. Infatti, sia per simulare "Elemento Status non specificato", che per simulare "Elemento StatusCode mancante" il tag Status è così generato:

<samlp:Status/>

Questo non permette di distinguere le due differenti casistiche di errore.

Come ovviare a questo problema? Dove stiamo sbagliando?

Grazie

**Comment by damikael** [comment]
Ciao @repsem ,
i due test riferiscono effettivamente alla stessa response. Sul SP, al fine di facilitare il debug, il messaggio rilevato potrebbe essere del tipo "Status non specificato o StatusCode mancante". In ogni caso in ambiente di produzione, per evitare information disclosure, tutti gli errori possono essere indicati come errori generici, ad eccezione delle **anomalie derivanti dall'utente** per le quali occorre esplicitare la causa di errore ritornata dall'IdP secondo quanto previsto dalla [Tabella anomalie SPID](https://www.agid.gov.it/sites/default/files/repository_files/tabella-messaggi-spid-v1.4.pdf).

**Comment by damikael** [comment]
Ciao @repsem, 
sì, ti confermo, per il superamento del collaudo, che per il test 25 della Response, il SP non deve consentire l'accesso al servizio rilevando l'errore che può essere indicato come "Status non specificato o StatusCode mancante".

**Comment by repsem** [comment]
Ciao @damikael,
perfetto, tratteremo in maniera analoga tutte le coppie di saml error simili (51-56, 73-84, 83-86, 88-91).
Procedo con la chiusura della issue.
Grazie!
