### ISSUE TITLE
Problemi check codice  ipa per Metadata Service Provider Pubblico

### ISSUE THREAD

**Issue by sil-vio** [italia/spid-saml-check#240]
Buongiorno,

dobbiamo sviluppare un Service Provider Pubblico per l'ente "Cassa Nazionale di Previdenza e Assistenza Forense" censito su IPA con tipologia "Enti Nazionali di Previdenza ed Assistenza Sociale in Conto Economico Consolidato"
e con categoria "Enti di Previdenza ed Assistenza Sociale in Conto Economico Consolidato privati" ([pagina dettaglio ipa](https://www.indicepa.gov.it/ipa-portale/consultazione/indirizzo-sede/ricerca-ente/elenco-unita-organizzative/2577/ente/scheda-ente/2577)).

Incontriamo delle difficoltà nella validazione del metadato da noi generato, in particolare non viene superato il check strict di produzione "test 80" che verifica la validità del codice IPA all'interno del metadata.
Questo test otteniamo come messaggio di errore "The IPACode element MUST have a valid value present on IPA".  Tutti gli altri controlli vengono superati con successo.

Di seguito l'estratto del metadata di tipo Service Provider Pubblico da noi generato in cui è presente il codice IPA dell'ente:

...
<md:Organization>
<md:OrganizationName xml:lang="it">Cassa nazionale di previdenza e assistenza forense</md:OrganizationName>
<md:OrganizationDisplayName xml:lang="it">Cassa nazionale di previdenza e assistenza forense</md:OrganizationDisplayName>
<md:OrganizationURL xml:lang="it">....</md:OrganizationURL>
</md:Organization>
<md:ContactPerson contactType="other">
<md:Extensions>
<spid:IPACode>PA:IT-cnpaf_0</spid:IPACode>
<spidublic/>
</md:Extensions>
...

Chiediamo quindi delle delucidazioni in merito a questo errore e come poterlo superare e generare un metadato per Service Provider Pubblico in linea con le specifiche.
Da quello che abbiamo visto sembra che per validare il codice IPA dell'ente venga fatto una chiamata verso i servizi esposti dall'indice IPA effettuando la ricerca delle AOO per codice Ente. Questo servizio però non restituisce nessuna AOO in quanto gli Enti con categoria  "Enti di Previdenza ed Assistenza Sociale in Conto Economico Consolidato privati"  per normativa non possono censire le AOO su IPA, come descritto dal seguente spaccato di documentazione IPA che potete trovare su [IpaPortale](https://indicepa.gov.it/ipa-portale/documenti) nella sezione Varie nel documento Categorie Enti.

Verificando però nell’elenco dei service provider pubblici [Registro SPID - Service Providers 2](https://registry.spid.gov.it/service-providers) è possibile trovare enti della categoria Enti di Previdenza ed Assistenza Sociale in Conto Economico Consolidato privati presenti in elenco, ad esempio la Cassa Nazionale del Notariato.

Chiediamo quindi se voi avete delle informazioni che ci possono chiarire lo scenario e come superare questa problema.

Grazie mille

**Comment by damikael** [comment]
Buongiorno, a differenza del valore da indicare all'interno del certificato, nel metadata deve essere indicato esclusivamente il codice IPA. Il metadata deve pertanto presentarsi come nel seguente esempio:

```
<md:Extensions>
    <spid:IPACode>cnpaf_0</spid:IPACode>
    ...
</md:Extensions>
```

**Comment by sil-vio** [comment]
Buongiorno,

ti ringrazio per la rapida risposta, si è corretto quello che dici ma avevamo già provato senza prefisso, impostando il metadata nel seguente modo  :

`<md:Organization>
        <md:OrganizationName xml:lang="it">Cassa nazionale di previdenza e assistenza forense</md:OrganizationName>
        <md:OrganizationDisplayName xml:lang="it">Cassa nazionale di previdenza e assistenza forense</md:OrganizationDisplayName>
        <md:OrganizationURL xml:lang="it">...</md:OrganizationURL>
    </md:Organization>
    <md:ContactPerson contactType="other">
        <md:Extensions>
            <spid:IPACode>cnpaf_0</spid:IPACode>
            <spid:Public />
        </md:Extensions>`


Ma il validatore ci fornisce lo stesso errore:

![image](https://user-images.githubusercontent.com/31255493/215053613-77ba7d49-a2bb-4211-8e20-6e615b529dcc.png)


Provando ad esempio però con il codice IPA del  "Comune di Roma" (c_h501) il validatore non ci mostra l'errore come per il caso di cnpaf_0.

Grazie in anticipo

**Comment by damikael** [comment]
Occorre allora segnalare la problematica sul repository https://github.com/italia/spid-sp-test
spid-sp-test è il tool utilizzato internamente da spid-saml-check per i test automatici su metadata e request.

**Comment by sil-vio** [comment]
Grazie abbiamo aperto l'issue qui https://github.com/italia/spid-sp-test/issues/156
