### ISSUE TITLE
Logout  collaudo Spid Livello 2

### ISSUE THREAD

**Issue by aLorenzo1** [italia/spid-saml-check#241]
Ciao a tutti,

per  effettuare il collaudo Agid per ottenere la certificazione come SP per utlizzare  lo SPID livello 2 come ente  privato è necessario implementare anche il flusso di Logout ? Nel caso la risposta fosse positiva, stiamo avendo problemi con il validatore a replicare una casistica di logout in HTTP-POST, il validatore processa la request e invia una response di tipo HTTP-GET ignorando il metadata.xml che indica come metodo di logout una response in HTTP-POST. Sapete come risolvere?

Grazie  mille.

**Comment by damikael** [comment]
Per superare il collaudo è necessario implementare il flusso di logout. 
Suggerisco di notificare a spid.tech@agid.gov.it al momento della richiesta di collaudo che il logout è implementato, come da metadata, su HTTP-POST.
