### ISSUE TITLE
Attribute idCard mancante

### ISSUE THREAD

**Issue by boschettiivan95** [italia/spid-saml-check#25]
Buongiorno,
Sto utilizzando la versione 1.1.0 di spid-auth-docker ed ho installato e configurato spid-saml-check per effettuare dei test sulla response.
Nel metadata richiedo i seguenti campi:
```
<md:RequestedAttribute Name="spidCode"/>
<md:RequestedAttribute Name="name"/>
<md:RequestedAttribute Name="familyName"/>
<md:RequestedAttribute Name="placeOfBirth"/>
<md:RequestedAttribute Name="dateOfBirth"/>
<md:RequestedAttribute Name="gender"/>
<md:RequestedAttribute Name="fiscalNumber"/>
<md:RequestedAttribute Name="email"/>
<md:RequestedAttribute Name="idCard"/>
<md:RequestedAttribute Name="mobilePhone"/>
<md:RequestedAttribute Name="address"/>
<md:RequestedAttribute Name="digitalAddress"/>
```
Ho riscontrato un problema relativo all'attributo idCard che nella form dello spid validator compare solo quando viene testata la casistica di "Response corretta", in tutti gli altri casi questo elemento non è presente e di conseguenza mi viene segnalato un errore relativo alla mancanza di questo attributo da parte del docker (questo errore è corretto in quanto non c'è corrispondenza tra gli attributi richiesti e quelli ritornati)

Come mai si verifica questo comportamento? 
Come posso testare correttamente tutte le varie casistiche lasciando inalterato il metadata del service provider?

**Comment by damikael** [comment]
Buongiorno @boschettiivan95 ,
gli attributi, compreso idCard, dovrebbero essere inseriti nella response, se richiesti nel metadata, per tutti i casi di test tranne i seguenti: 
31, 32, 89, 98 (per i quali è giusto che non ci siano)
99, 109 (che erano stati inseriti per verificare casi particolari e saranno corretti)

Su quali casi di test in particolare riscontri il problema? Potresti allegare esempio di metadata, request e response generata dal validator?

Grazie

**Comment by boschettiivan95** [comment]
Buonasera,
Ho risolto il problema aggiungendo l'attributo idCard ad ogni casistica del file test.json ad esclusione di quelle da te indicate.
Ho inoltre aggiunto l'attributo digitalAddress a tutte le casistiche ad esclusione di quelle che non presentano nemmeno un attributo.
Sapresti indicarmi se c'è qualche caso in cui digitalAddress è giusto che non ci sia?

Grazie.

**Comment by damikael** [comment]
Buonasera, 
tutti gli attributi spid devono essere presenti in tutte le casistiche ad eccezione di quelli indicati.
Sto preparando la commit che risolve tali configurazioni.

**Comment by damikael** [comment]
Aggiornate configurazioni casi di test con tutti gi attributi spid  (Rif. https://github.com/italia/spid-saml-check/commit/0058bfe4188cf544b0d41d2e9b903ca8a643eab9)

**Comment by boschettiivan95** [comment]
Problema risolto, grazie!
Unico accorgimento: nel commento seguente https://github.com/italia/spid-saml-check/issues/25#issuecomment-480198751 sono stati indicati i casi di test in cui idCard non va aggiunto.
Nel commit riportato nel commento https://github.com/italia/spid-saml-check/issues/25#issuecomment-480342075 vedo però che per i casi 31, 32 e 89 l'attributo idCard è presente.

**Comment by damikael** [comment]
Grazie per le indicazioni, 
da considerare comunque che se nel relativo template xml del test (in /test) non è presente il parametro {{Attributes}} gli attributi eventualmente indicati nella configurazione del test nel file test.json non si applicano.

**Comment by boschettiivan95** [comment]
Buongiorno @damikael, ho riguardato il commit che hai fatto per questa issue e ho notato che il test numero 109 recante il nome "Attributi senza NameFormat" con risultato atteso "OK", al posto di togliere solo il NameFormat, toglie tutti gli attributi ad eccezione del fiscalCode.

**Comment by damikael** [comment]
Buongiorno @boschettiivan95 ,
ho aperto la issue #29 per il caso specifico del test 109.

**Comment by boschettiivan95** [comment]
Grazie, nel frattempo ho modificato il file spid-validator/config/case-109.xml inserendo tutti gli attributi che mi servivano senza il relativo NameFormat e l'esito del test è risultato positivo.
