### ISSUE TITLE
Test n° 100: firma diversa

### ISSUE THREAD

**Issue by boschettiivan95** [italia/spid-saml-check#26]
Buongiorno,
In riferimento al caso di test n° 100 (firma diversa) per implementare correttamente i controlli, vorrei capire lo scopo di questa casistica.
In particolare, con cosa viene confrontata la firma per stabilire se è diversa?
La suddetta firma è il SignatureValue presente nell'elemento Assertion?
Grazie.

**Comment by damikael** [comment]
Il test n° 100 permette di inviare al SP una response la cui è assertion è firmata con un certificato diverso da quello la cui chiave pubblica è dichiarata nel metadata del validator (http://localhost:8080/metadata.xml).

Il SP deve verificare la firma dell'assertion con tale chiave pubblica e, se la firma non è valida, non deve permettere l'accesso.

Tuttavia, attualmente, occorre modificare certificate e privatekey nella configurazione del test n°100. Infatti, nella configurazione attuale, riportano gli stessi certificate e privatekey configurati come default per il validator (/config/idp.json) rendendo di fatto il test non corretto.

Lascio aperta la presente issue come promemoria per correggere la configurazione.
