### ISSUE TITLE
Chiarimenti su esecuzione test

### ISSUE THREAD

**Issue by pmosini** [italia/spid-saml-check#27]
Salve, 
avrei necessità di capire meglio come eseguire i test di validazione:
a) Le spiegazioni contenute nel readme indicano che è disponibile una interfaccia facile per configurare lo validator ma non specificano come accedervi, qual'è l'URL? 
b) non viene indicato come caricare il metadata dell'SP nel validator
c)  nel readme si indica di eseguire il comando docker run -t -i -p 8080:8080 spid-saml-check . e di inviare una AuthnRequest  dal SP, è questa la sequenza esatta di esecuzione del test? Come verificare l'esito del test?

Grazie in anticipo

**Comment by damikael** [comment]
Buonasera @pmosini ,

il validator si comporta come un IdP, ovvero riceve AuthnRequest e invia Response, con la differenza che è possibile osservare i messaggi SAML del flusso, eseguire verifiche automatiche sul Metadata e sulla Request, e inviare Response, corrette o malformate al SP al fine di verificare il comportamento del SP rispetto al comportamento atteso.

Per accedere all'ambiente occorre configurare il validator sul proprio SP, in maniera analoga ad un IdP (Il metadata di configurazione è disponibile all'url http://localhost:8080/metadata.xml) e inviare dall'SP una richiesta di autenticazione. Alla schermata di login del Validator è possibile accedere con le credenziali indicate nel readme e configurate in /spid-validator/config/idp.json

Il Validator è composto dalle sezioni Metadata, Request, Response. Dopo aver eseguito l'accesso è necessario innanzitutto caricare il Metadata del SP all'interno della relativa sezione. Quindi sarà possibile eseguire le verifiche sul Metadata, eseguire le verifiche sulla Request e selezionare le Response da inviare all'SP. Dopo aver inviato una response al SP la sessione sul validator resta attiva esclusivamente per salvare l'esito della response. Quindi, per testare altre response, bisognerà reinviare una nuova request dal SP.

Resto a disposizione se occorrono ulteriori informazioni.

**Comment by pmosini** [comment]
Grazie per la risposta, ora mi è chiaro come procedere per fare i test. Ho notato però che l'IDP metadata  definisce come SingleLogoutService e  SingleSignOnService https://localhost:8080/samlsso, ma il validator risponde a http://localhost:8080/samlsso. Come poter abilitare il validator a rispondere effettivamente in SSL invece che in TCP, o in alternativa modificare il metadata affinche contenga come SingleLogoutService e SingleSignOnService http://localhost:8080/samlsso? Grazie ancora.

**Comment by pmosini** [comment]
Trovato come forzare l'idp a rispondere in HTTP, grazie lo stesso!

**Comment by damikael** [comment]
Endpoint corretti in http, come l'entity. 
E' possibile modificare le configurazioni nel file /spid-validator/config/idp.json.
