### ISSUE TITLE
Login con ambiente demo in sottodomini di uno stesso dominio principale

### ISSUE THREAD

**Issue by alessandro2024** [italia/spid-saml-check#274]
Gent.mi,
sto lavorando nella gestione del sito di alcuni ENTI e sto riscontrando un problema nella response/redirect della procedura
di accesso in area riservata tramite SPID secondo le specifiche degli ambienti DEMO e DEMO Validator all'url https://demo.spid.gov.it/

Le fasi implementate sono state:
1) ho creato il metadata specifico per ciascun ENTE e configurato sul proprio Service Provider;
2) validato correttamente il metadata relativo degli ENTI tramite il "Metadata Service Provider" alle voci "Check Strict" e "Check Extra" ;
3) invitata una AuthnRequest dal proprio Service Provider all'IdP dell'ambiente Demo SPID.

Il problema che sto riscontrando è al punto 3 di cui sopra.
Se accedo dal sito ENTE1 tutto funziona correttamente.
Se invece accedo dal sito ENTE2  e invio la richiesta dopo aver inserito un utente fittizio di primo livello tra quelli presenti all'url https://demo.spid.gov.it/users (ad es. cesare/password123) NON si accede correttamente in area riservata in quanto viene fatta una "redirect" nella LOCATION ENTE1, nonostante la proprietà LOCATION nel file metadata ENTE2 sia inserita correttamente.

Chiedevo quale possa essere il legame tra essi.
Essendo la procedura di SPID dell'ENTE1 la prima temporalmente creata, può essere che con l'ENTE2 siamo redirect su ENTE1 perchè appartenenti allo stesso dominio principale ma su sottodomini differenti?
In questo caso è possibile avere una soluzione alternativa oppure sto sbagliando ancora qualcosa?

Grazie anticipatamente.

**Comment by damikael** [comment]
Buonasera @alessandro2024 , 
assicurati che i metadata non abbiano lo stesso EntityID.
Per approfondire meglio avrei necessità di verificare i metadata e il flusso di autenticazione, se vuoi puoi scrivermi su michele.damico@linfaservice.it

Cordiali saluti.
Michele

**Comment by damikael** [comment]
Il problema è stato risolto.
Occorre assicurare anche che l'Issuer della AuthnRequest corrisponda all'EntityID del relativo metadata.

https://www.damikael.dev
