### ISSUE TITLE
certicato idp expired

### ISSUE THREAD

**Issue by pmosini** [italia/spid-saml-check#28]
Salve ho notato che il certificato presente nel metadata nell'idpdel validator  è expired, pertanto non posso eseguire i test. Come posso fare per importare un nuovo certificato valido? dove trovo il keystore nel validator?
Grazie in anticipo
![spidvalidator-Certificate](https://user-images.githubusercontent.com/29142447/55887061-27665b00-5bad-11e9-8c26-a316cc41eb4b.png)

**Comment by gigderoma** [comment]
Ciao pmosini 
ho avuto lo stesso problema, con openssl ho creato una nuova key/cert e trasformate entrambe in PEM format e rimpiazzato nel idp.json

**Comment by pmosini** [comment]
si è quello che stavo provando a fare, grazie!

**Comment by damikael** [comment]
Certificato di default aggiornato.
Il certificato può essere configurato in /spid-validator/config/idp.json.
