### ISSUE TITLE
Test 109 does not take the attributes from metadata

### ISSUE THREAD

**Issue by damikael** [italia/spid-saml-check#29]
Attributes defined into the AttributeStatement element of the Response should be compiled from the related AttributeConsumingService.

**Comment by pmosini** [comment]
Hello, when I run the test 109, it fails because the controls added at SP Side for test 103. Indeed, test 109 only send 
 <saml:Attribute Name="fiscalCode">
                                                                
                
                <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">
                    
                    TINIT-SCHNNG77M06H224U
                
                </saml:AttributeValue>
                                                     
            
            </saml:Attribute>

So it fails because test 103 "Set di attributi inviato diverso da quello richiesto"
Could you please verify?
Thanks in advance
