### ISSUE TITLE
veritfica test 43 

### ISSUE THREAD

**Issue by pmosini** [italia/spid-saml-check#30]
Salve, il test 43 "Assertion - Elemento NameID non specificato" credo vada rivisto in quanto l'elemento NameID risulta invece essere presente, potreste gentilemente controllare? Inoltre il test 31 " Response - Autenticazione annullata da IdP" invia come codice di errore 23 invece di 25, secondo le regole tecniche.
Grazie mille

**Comment by damikael** [comment]
Risolto,
il test 31 "Autenticazione annullata da IdP" è stato cancellato in quanto presente al num. 111

Grazie per la segnalazione.

**Comment by pmosini** [comment]
Ok, grazie per il test 31, avete invece riscontri per il test n° 43 che risulta comunque inviare l'elemento NameID in maniera corretta? Grazie ancora

**Comment by damikael** [comment]
L'ultima commit risolve anche la segnalazione sul test 43 che riporta ora valore vuoto per l'attributo NameQualifier.

**Comment by pmosini** [comment]
Perfetto grazie mille
