### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by angeloimm** [italia/spid-saml-check#31]
Salve

Abbiamo scaricato lo spid-saml-check. Abbiamo configurato il nostro server WSO2 (versione 5.7.0) affinché fungesse da SP verso l'IdP spid-saml-validator; pertanto abbiamo scaricato il metadata.xml del validator e lo abbiamo importato nella configurazione di WSO2. Tutto il processo di configurazione parrebbe essere OK.
Abbiamo, poi, tentato di accedere con questo IdP (spid-validator). In base alle info del metadata.xml importato in WSO2 veniamo rediretti all'URL http://localhost:8080/samlsso ma qui  otteniamo il seguente errore
"
_Error: ENOENT: no such file or directory, open '/spid-validator/client/view/layouts/main.handlebars'_
"
Effettivamente, controllando nei sorgenti, tale file non è presente.
L'errore è mostrato nell'immagine allegata.
![Screenshot from 2019-06-18 12-54-29](https://user-images.githubusercontent.com/6228922/59676620-3af2fb00-91c8-11e9-8401-f656f1d2c8e3.png)

Come possiamo risolvere?
Abbiamo necessità di rendere compliant WSO2 a SPID.

**Comment by damikael** [comment]
Salve,
gli ultimi aggiornamenti dovrebbero risolvere il problema riscontrato.

Forse l'ambiente spid-saml-check è stato installato e avviato direttamente dai sorgenti e non tramite docker? In tal caso potrebbe essere necessario anche creare la directory _data_ in _/spec-compliance-tests_.

Si consiglia comunque l'installazione tramite docker.

**Comment by angeloimm** [comment]
Salve
Avevamo scaricato il repository GIT e utilizzato docker per la creazione e lo start dell'ambiente.
Ad ogni modo abbiamo scaricato i nuovi sorgenti e proveremo ASAP.
