### ISSUE TITLE
Snellire il workflow di reportistica

### ISSUE THREAD

**Issue by walter-arrighetti** [italia/spid-saml-check#45]
Il workflow di reportistica dovrebbe prevedere che le 7 famiglie di controlli
`[metadata|request]-[strict|cert|extra] | response`
vengano salvati per poter estrarre un report PDF in un secondo momento. La data dell'ultima convalida va inclusa nel report (web e PDF).
Com'è attualmente, ogni volta che si clicca su una delle 7 sezioni si rilancia la famiglia di controlli corrispondente da capo. In pratica, dopo aver termiato la famiglia di controlli, si ha una sola opportunità di salvare il report.

**Comment by damikael** [comment]
Dalla release 1.1.1, per ogni famiglia di controlli, viene salvata l'ultima validazione eseguita.
È possibile successivamente stampare il report dell'ultima validazione eseguita oppure eseguire una nuova validazione.
Il report, così come l'interfaccia, presenta la data/ora dell'ultima validazione eseguita.
