### ISSUE TITLE
Dopo il download del Metadata Service Provider non succede nulla

### ISSUE THREAD

**Issue by sintetico82** [italia/spid-saml-check#46]
Eseguita l'applicazione all'interno in un container Docker, dopo aver eseguito l'accesso con l'utente  **validator**, a seguito del download del Metadata Service Provider, non succede nulla. Viene visualizzato l'XML dell'endpoint specificato ma poi non è possibile eseguire nessuna delle azioni di verifica.

![spid-validator-bug](https://user-images.githubusercontent.com/4086973/68403416-3205c480-017d-11ea-998d-7216b7d3d32a.JPG)

**Comment by damikael** [comment]
Come indicato ne README occorre configurare il metadata del validator, recuperabile all'indirizzo /metadata.xml, sul proprio Service Provider; quindi inviare una AuthnRequest dal Service Provider al Validator.

**Comment by sintetico82** [comment]
Ho capito. Chiudo la segnalazione allora, grazie.

**Comment by sintetico82** [comment]
Scusami però qualcosa non mi torna. Perchè allora mettere a disposizione il download dei metadata se non riesco  fare le verifiche che trovo qui nel menù?

![sp-test-metadata](https://user-images.githubusercontent.com/4086973/68596827-29bec980-049c-11ea-84ce-0ffc965c5721.JPG)

**Comment by damikael** [comment]
Il tool spid-saml-check può essere integrato in altri applicativi e la funzionalità di acquisizione del metadata è utile a tale integrazione. Comunque è vero che, rendendo disponibile la funzionalità di acquisizione del metadata, esternamente all'authnrequest, potrebbe essere utile avere già disponibili anche le funzionalità per la sua validazione.
Lo inserisco tra le cose da fare. Grazie.
