### ISSUE TITLE
Configurazione dietro proxy aziendale

### ISSUE THREAD

**Issue by angeloimm** [italia/spid-saml-check#47]
Salve
**Il problema**: dietro proxy aziendale il validatore sembra non funzionare.
**step riproduzione problema**:

1. scaricare repository GIT del validatore
2. costruire l'immagine del validatore passando le configurazioni del proxy a docker con il comando --build_args
3. avviare il validatore
4. effettuare un test

I punti 1,2,3 sono OK ma al punto 4, una volta effettuato il download del metadata non si riesce a proseguire in quanto il SW tenta una connessione HTTP verso qualche URL non indicata (o almeno che io non riesco ad identificare) e, dopo molto tempo, va in errore.
Per ovviare fatto i passi precedenti sino al 4 poi, una volta effettuato il download del metadata da rete interna ho collegato il mio PC al mio hotspot del cellulare (senza proxy) e tutto è andato correttamente.
Ovviamente su macchine server interne alla mia rete aziendale non posso adottare il workaround indicato in precedenza.
Come posso risolvere il problema?

**Comment by damikael** [comment]
Salve,
il problema potrebbe dipendere dalla verifica TLS che viene effettuata, per alcuni test, utilizzando le API di SSL Labs (https://api.ssllabs.com).
Occorre verificare se il firewall blocca le richieste verso ssllabs e, nel caso, configurare opportune regole.

**Comment by angeloimm** [comment]
OK
Provo a sentire i sistemisti (dalla nostra sede non gestiamo il proxy aziendale) sperando che accettino la configurazione di tali regole (probabilmente inserire un file di configurazione per abilitare il proxy per le chiamate HTTP sarebbe comodo)

Mi servirebbe, però, avere un elenco dei domini da far abilitare.
Uno dovrebbe essere apit.sslabs.com. Ce ne sono altri da considerare?

Grazie 1000
Angelo

**Comment by damikael** [comment]
SPID Validator utilizza le api https://api.ssllabs.com,
e invia Response alle URL degli AssertionConsumerService dichiarati nel metadata del servizio che si sta testando.
Anche questi ultimi, quindi, devono essere raggiungibili al fine di verificare le Response.
