### ISSUE TITLE
Rimuovere l'obbligatorietà del RelayState

### ISSUE THREAD

**Issue by walter-arrighetti** [italia/spid-saml-check#54]
La presenza del RelayState nella richiesta non andrebbe considerato obbligatorio; stiamo vedendo diversi SP che non adottano il RelayState, infatti, senza per questo produrre request invalide.
Andrebbe alleggerito il controllo alla linea 84 di https://github.com/italia/spid-saml-check/blob/master/specs-compliance-tests/test/sp/authn_request_strict.py e, conseguentemente un simile comportamento nel componente Validator

**Comment by damikael** [comment]
La presenza del parametro RelayState è prevista dalle regole tecniche SPID (Rif. Regole Tecniche 1.2.2).
Il controllo, pertanto, è normativo. Tuttavia, è stato corretto il comportamento sul Validator, affinchè la mancata presenza del parametro non sia bloccante per il test Request Strict (precedentemente, infatti, la mancata presenza del parametro era la causa per cui tutti i test del set Request Strict risultassero vuoti).
