### ISSUE TITLE
Abilitazione accesso spid-saml-check pubblico

### ISSUE THREAD

**Issue by xripax** [italia/spid-saml-check#57]
Buongiorno,
sarebbe possibile per un'azienda che fornisce soluzioni alla pubblica amministrazione richiedere l'accesso all'ambiente pubblico di SPID Validator raggiungibile all'indirizzo https://login.agid.gov.it/ in modo da poter verificare l'integrazione con SPID installata presso uno specifico cliente laddove non sia possible utilizzare il container messo a disposizione per uso interno?

Ho fatto medesima richiesta sul progetto generico spid (https://github.com/italia/spid/issues/1281)

Grazie in anticipo.

**Comment by damikael** [comment]
Salve,
l'accesso all'ambiente di validazione disponibile online all'indirizzo https://validator.spid.gov.it/
è riservato esclusivamente al personale AgID. 
Confermo, tuttavia, che l'ambiente online è un'installazione del codice presente su questo repository (https://github.com/italia/spid-saml-check).
