### ISSUE TITLE
FileNotFoundError su Check Strict

### ISSUE THREAD

**Issue by pagemate** [italia/spid-saml-check#61]
Buongiorno,
ho lanciato l'applicativo tramite Docker e configurato l'IDP di test sul mio SP, ho effettuato l'accesso tramite le credenziali fornite.
Una volta autenticato, ho effettuato il download del Metadata inserendo l'URL (su localhost) nella pagina Metadata SP > Download  dove poi viene effettivamente caricato a video dopo il click sul relativo pulsante.
Quando però poi vado in Check Strict per eseguire la validazione, i test non vengono eseguiti, e la console del Docker riporta questo errore:
Traceback (most recent call last):
  File "/spid-saml-check/specs-compliance-tests/test/sp/metadata_strict.py", line 123, in setUp
    with open(METADATA, 'rb') as md_file:
FileNotFoundError: [Errno 2] No such file or directory: './data/SPID_DOMAIN_VALUE /sp-metadata.xml'

Se carica inizialmente il metadata, perché poi dice non trovare il file?

**Comment by damikael** [comment]
Verificare se il problema si verifica ancora dopo gli ultimi aggiornamenti. Nel caso si prega di aprire una nuova issue.
