### ISSUE TITLE
sha256 not found on authentication form

### ISSUE THREAD

**Issue by carminero** [italia/spid-saml-check#63]
Hello, 
on the authentication form after insert correct credentials appears a message that inform that sha256 is not found.

spid-saml-check/spid-validator/server/app/auth.js
```
let resobj = {
                    apikey: sha256(config_idp.localloginUser + config_idp.localloginPasswordHash).toString()
                }	
```

But after adding the module required with 

`const sha256 = require("sha256");`

and rebuilding docker the authentication works.

**Comment by damikael** [comment]
Thanks
