### ISSUE TITLE
Procedura per modificare certificato e chiave privata in idp.json

### ISSUE THREAD

**Issue by carminero** [italia/spid-saml-check#64]
Ciao, ho bisogno di un piccolo supporto per quanto riguarda la procedura di generazione di certificati e chiave privata.
Modificando entityId e endpoint login logout (per farli puntare verso il mio idp di validazione) in fase di response ottengo signature invalid (validando la risposta con un tool online). 
Sul mio SP da validare (shibboleth) ottengo invece un errore di tipo: xmltooling::XMLParserException. Da notare che uso anche https://github.com/italia/spid-testenv2 su cui l'autenticazione funziona.

Ho pensato che potrebbe dipendere ovviamente dal certificato e la chiave privata di default.

Comunque provando a generare il certificato e la chiave allineandoli al mio entityId ho qualche problema.

La procedura che uso è la seguente 

`openssl req -config openssl.cnf -newkey rsa:2048 -sha256 -nodes -keyout key.pem -x509 -days 365 -out certificate.pem`

dopodicché se ho ben capito il contenuto va "linearizzato" per inserirli in un unica riga in idp.json
rispettivamente in certificate e privateKey.

Sulla privateKey in particolare, linearizzando rimuovendo i newline, oppure effettuando un encode base64 (ho notato che la chiave privata termina con il simbolo "=") e puntando su /metadata.xml ottengo un messaggio di errore di questo tipo

`
Error: error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag
    at Sign.sign (internal/crypto/sig.js:105:29)
    at RSASHA256.getSignature (/spid-saml-check/spid-validator/server/lib/xml-crypto/lib/signed-xml.js:126:22)
    at SignedXml.createSignature (/spid-saml-check/spid-validator/server/lib/xml-crypto/lib/signed-xml.js:719:44)
    at SignedXml.computeSignature (/spid-saml-check/spid-validator/server/lib/xml-crypto/lib/signed-xml.js:510:29)
    at Object.signXML (/spid-saml-check/spid-validator/server/lib/saml-protocol/util/signing.js:100:12)
    at Object.buildIDPMetadata (/spid-saml-check/spid-validator/server/lib/saml-protocol/metadata.js:54:28)
    at IdentityProvider.produceIDPMetadata (/spid-saml-check/spid-validator/server/lib/saml-protocol/index.js:68:21)
    at IdP.getMetadata (/spid-saml-check/spid-validator/server/lib/saml-utils.js:314:25)
    at /spid-saml-check/spid-validator/server/app/idp.js:51:62
    at Layer.handle [as handle_request] (/spid-saml-check/spid-validator/server/node_modules/express/lib/router/layer.js:95:5)
`

Ti chiederei gentilmente di fornirmi la modalità correttà di inserimento di questi due parametri o eventualmente la procedura standard che utilizzate per la generazione degli stessi.

Grazie anticipatamente per il supporto.

**Comment by damikael** [comment]
Ciao @carminero ,
puoi provare ad utilizzare il seguente comando:

`openssl req -newkey rsa:2048 -new -x509 -days 365 -nodes -keyout key.pem -out certificate.pem`

Il contenuto dei file va "linearizzato" e inserito senza ulteriore modifica in privateKey e certificate rispettivamente.

In ogni caso, a meno di non voler esporre il proprio SPID Validator su un dominio pubblico, utilizzandolo solo in locale, non dovrebbe esserci necessità di modificare le configurazioni in idp.json

**Comment by carminero** [comment]
Ciao @damikael stesso errore, ho verificato che chiave privata e certificato siano compatibili anche con un tool online ecco il contenuto di test

`
"credentials": [{
		"signatureAlgorithm": "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256",
		"certificate": "MIID5zCCAs+gAwIBAgIUGkDh1pXqONxpVsQi7x14MZSesz0wDQYJKoZIhvcNAQELBQAwgYIxCzAJBgNVBAYTAklUMQ4wDAYDVQQIDAVJdGFseTEPMA0GA1UEBwwGTm92b2xpMRQwEgYDVQQKDAtDUlMgU2VydmljZTELMAkGA1UECwwCSVQxLzAtBgNVBAMMJmh0dHA6Ly9jcnNzZXJ2aWNlLm15cW5hcGNsb3VkLmNvbTo5MDk1MB4XDTIwMDUxMTA4MDIyM1oXDTIxMDUxMTA4MDIyM1owgYIxCzAJBgNVBAYTAklUMQ4wDAYDVQQIDAVJdGFseTEPMA0GA1UEBwwGTm92b2xpMRQwEgYDVQQKDAtDUlMgU2VydmljZTELMAkGA1UECwwCSVQxLzAtBgNVBAMMJmh0dHA6Ly9jcnNzZXJ2aWNlLm15cW5hcGNsb3VkLmNvbTo5MDk1MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuocnvZXAiseLgeGj0f2BPUD07EFPRqityterzZW2RjvTBMnr/LQENXeLjl0zxX2DQ5sSwXYaI5+ylDCXyI/cN1g2J0bpnGIAQCN0MXvWKVXyvj4CtjMzkedng7sebSyMXUB2jXHRrfUB/W2r7PRTS5b/fpjkByeGACJwLW5ccWP4LYDhks96UI8mn+EtlLerFzBK0rglE8m4VtSJH6uHLi0/kC+tiS9RK356HT6/K/00eA+kBa84oH/sf9U9TNBY+P0qHqYjaEqT7YXiaBzsymhhR9w9ZEf91yHm3eosmTPCuGJptWU4mIkfXY744KOmDFFMwy528gGJ5YP02tDk4QIDAQABo1MwUTAdBgNVHQ4EFgQUKNbSHVNy9t3Iix2AB5ltCsRZfzMwHwYDVR0jBBgwFoAUKNbSHVNy9t3Iix2AB5ltCsRZfzMwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAR3zzvMt7xP5X+ZjPyC7IjcV2R6vYKl1zu7J2L4a+QGIAElrz6aU4VkfhE78GVgTOuw0O1/w9uypfdkyT7U4YAtIBgFzG+KPuP7+5X3PHJcsfgiS5RHw3MMx5wMsbux0XjEIaXldnroAmecV96krzKjbk+RoOwUtEt1TbTvjFfiKVDH32zQnJececptYvObvjFY5vkUK216veAdwcsXAGU0FrT8cYjilG/8MKs/Jinq/A8u1VDM9vCPAXtkV2cGrBnJ7WcAtGtqLKmN1LpwXb5gFcGD4w99dWHc+CGXDbb8vQyA7Yw/TT3qGf+/2qkmYt4DufkR8tFq7M5rJbKzLW7A==",
		"privateKey": "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC6hye9lcCKx4uB4aPR/YE9QPTsQU9GqK3K16vNlbZGO9MEyev8tAQ1d4uOXTPFfYNDmxLBdhojn7KUMJfIj9w3WDYnRumcYgBAI3Qxe9YpVfK+PgK2MzOR52eDux5tLIxdQHaNcdGt9QH9bavs9FNLlv9+mOQHJ4YAInAtblxxY/gtgOGSz3pQjyaf4S2Ut6sXMErSuCUTybhW1Ikfq4cuLT+QL62JL1ErfnodPr8r/TR4D6QFrzigf+x/1T1M0Fj4/SoepiNoSpPtheJoHOzKaGFH3D1kR/3XIebd6iyZM8K4Ymm1ZTiYiR9djvjgo6YMUUzDLnbyAYnlg/Ta0OThAgMBAAECggEAJ1HMT8ucjeSohNWCygZNUxM5TgAqbPOrxwGVpr2zcbS0s+K4y0lLRdYQZg9BlZTysbKjzoJN2kqUw2ZG6LFis4v1xmvNXPjPorWWjcPUDlye0fmSasP6T/xetscgD9V/NT0cgI6Iq8nlBH406rtKP7nx28bw8o0jUy3vRbRo6kHTV/vZz2L2iNoZ5NBeMv65XhBuP37m8LhqarMyLoaX5QdzieqlD9Nrp7petD5g8A4UOIAD0pREH1YxdsVUqncThkzWyEONOpxB++TCsTifvwGY6jicJuY5G0rq2vcJhO4iuyll/fBPHLlPb/yFjIpfB9zofeC7iTf2XKTjcjnAzQKBgQDlRqGoIJl/QoZwJk7ei2rmUrkgd784AS2YYmQB2AEeEql3SnQRyu+rd5DHE+P5oM4GHr+Jy+7NpRm2tnmWDUbou3mSDfj4mx91bVc11HAMeQcrA+TYawkxxcw7dKxUPLj2Nra+s0xc3SnKv90uYhshlsNi9IGxcyfEUQ5A+tMiiwKBgQDQRPd3WjfMUvl8QNzzHi9tkQKCeDq4V3aBVLaOxX4T37EPf0RT0TcKSLqHRkNYe7FCuMcxSQArK4kuVoJfx45eJcBHtvH2TSGx0OgBk7TdEDhHhVUiPEzvlM8GC94zKWWy5Em2ZfPtCfPn339SgfHCsvdAyzla9s71LHrjuARfwwKBgECRG4VVaOTFv0ZmA1/4syoZsbjLADatXkHDs5YxVl85si+97+Hy3HvVOBhYKaNq/ZoLnrUXkTCohg1GZgczxfxUj2/qL2sThFB1clHeeY+JpdMfTZsEyZoSseksejtevlfYIK6jn6WnQtWuIoOlbS6QXoXHhZ6LZ2+JxBHYkQzxAoGAMS/4mhGOmA0IqxXOmQSKAwB6bUHj7GGLtWPCcdmmux7bfGN8SadhrmYa15P6l80uwilNshAhoBB6J5160RAaSZX04XsNjjQNPyetg6HU11jbUdjlkF5ZdUPZ2P24jrC6OhO8bP2LLHJrTln0ghH6fRczWfQlKZycqD7HDz0Im20CgYEAxvM7qYSvoDFz5Kwfj1jGw+2mHP4QZr3shn7bTSTgDuNRkxHHLa8qdkRci/qG3coAYl8lxhvo81m8SScqvBjHM3NgS6QccB7YilJ7rcSEFmHjJYhjd9bbiN5v9hzG8rMNm3+87szc/sR59AYBJmt7JpC6RnlFN213rBj6AZVH4wU="
	}],
`

**Comment by carminero** [comment]
openssl pkey -in key.pem -pubout -outform pem | sha256sum
93fb6ced219eeb83fc2926fb9b573873eb17d743c6610c7591ceffe0e3b28d7a  -
openssl x509 -in certificate.pem -pubkey -noout -outform pem | sha256sum
93fb6ced219eeb83fc2926fb9b573873eb17d743c6610c7591ceffe0e3b28d7a  -

**Comment by damikael** [comment]
openssl genrsa -out key.pem 2048
openssl req -new -x509 -key key.pem -out certificate.pem -days 365

**Comment by carminero** [comment]
Grazie mille!!!!  Così funziona.

PS: Credo dipenda da i caratteri newline: ho fatto qualche test con cryptojs e lo stesso certificato "malfunzionante"  viene utilizzato correttamente se letto in questo modo

`
var crypto = require('crypto');
var fs = require('fs');
var privatePem = fs.readFileSync('key.pem');
console.log("--KEY PEM--");
console.log(privatePem);
var key = privatePem.toString('ascii');
console.log("--ASCII-KEY--");
console.log(key);
var signer = crypto.createSign("RSA-SHA256");
var signedInfo = "Bla Bla Bla";
signer.update(signedInfo);
var res = signer.sign(key, 'base64');
console.log("--SIGNED--");
console.log(res);
`

--SIGNED--
c3LjPn7oEGUvYSOi+QoJJ9iN61oH0pVwo9GEBX2U/T0GxjqhjkuYcj0g0tib4+ab0/mqFvkn5DdZ9v7WD6NH5XxksRc39o5lBuwlXThOkQolIJHMYhgREMsypB8njfV2vQLHmXp2zexXjVsfEpphfnQBHuBl2xkJhrbmvXQXdHJ/G51kIgkFS386JISDZb2debONlQ2CUwOp151WerIUq5xGLgA5BfbPAG9L3Hpzgetuw6YcHLnrmFdG5sgJlYoO8zycX+Gs6XXw9EUo1yFHidaN/CF0n5pM99wYcj+wbsoLHPuhxBuLcDXz2tAwBlYZZ9ZTFLrVAjEqFX5AVZyxOw==


Grazie ancora @damikael
