### ISSUE TITLE
Caso di test n.73 Assertion - Elemento Conditions non specificato

### ISSUE THREAD

**Issue by carminero** [italia/spid-saml-check#65]
Ciao @damikael,

per quanto riguarda il caso in questione si chiede di verificare la presenza dell'elemento Conditions o la sua validità?

Ti chiedo perché nel formato template xml di spid-validator/test/case-73.xml l'elemento
è presente e valorizzato come 
....
<saml:Conditions 
            NotBefore="{{IssueInstant}}" 
            NotOnOrAfter="{{NotOnOrAfter}}" >

        </saml:Conditions>
....

Ti ringrazio

**Comment by damikael** [comment]
Ciao @carminero,
le regole tecniche SPID specificano:

> deve essere presente l’elemento Conditions in cui devono essere presenti gli attributi:
> - NotBefore,
> - NotOnOrAfter;
> 
> e l’elemento:
> - AudienceRestriction riportante a sua volta l’elemento Audience
> attualizzato con l’entityID del ServiceProvider per il quale l’asserzione è emessa;

_(Rif. Regole tecniche SPID § 1.2.1)_

Pertanto va inteso come "mancante del sottoelemento AudienceRestriction"

**Comment by carminero** [comment]
Perfetto grazie. 

Ciao

**Comment by carminero** [comment]
Scusa se ti "martello" :), 
il test case 109 a livello di descrizione dovrebbe essere un errore e non un success

"name": "109. Attributi senza NameFormat",
"description": "Response corretta. Risultato atteso: Ok",

**Comment by carminero** [comment]
Come non detto...

**Comment by damikael** [comment]
È corretto che il risultato atteso sia OK.
Le regole tecniche SPID non specificano nulla a riguardo mentre, per SAML, l'attributo NameFormat è opzionale. Per compatibilità con alcuni IdP, pertanto, l'attributo NameFormat può essere presente o meno e il SP deve consentire entrambi i casi.
