### ISSUE TITLE
Le request SAML non sono collaudabili dallo SPID Validator

### ISSUE THREAD

**Issue by danielebonfatti** [italia/spid-saml-check#66]
Eseguendo i test sulla request non appare il risultato (né positivo né negativo), ma solo l'elenco dei test effettuati. La cosa rende impossibile il collaudo richiesto da AGID. Il log dell'SP non presenta niente di anomalo, a cosa può essere dovuto questo fenomeno?
[Request Check Strict.pdf](https://github.com/italia/spid-saml-check/files/4729144/Request.Check.Strict.pdf)
[Request Chech Certificates.pdf](https://github.com/italia/spid-saml-check/files/4729145/Request.Chech.Certificates.pdf)
[Request Check Extra.pdf](https://github.com/italia/spid-saml-check/files/4729146/Request.Check.Extra.pdf)

**Comment by damikael** [comment]
Controllare che l'Issuer con il quale viene inviata la Request corrisponda esattamente al valore dell'EntityID dichiarato nel metadata.

**Comment by damikael** [comment]
Inoltre verificare la presenza dell'attributo RelayState, eventualmente vuoto, sulla Request

**Comment by danielebonfatti** [comment]
Grazie delle informazioni. L'Issuer risulta corretto, mentre in effetti credo che manchi l'attributo RelayState, del quale però non trovo riferimento nello schema di AuthnRequest. Mi può gentilmente fornire qualche dettaglio su come inserirlo nella request?
Grazie in anticipo

**Comment by damikael** [comment]
Se il binding è in HTTP-Redirect l'attributo deve essere inviato sulla querystring. 
Se, invece, è in HTTP-POST deve essere inviato come parametro nel body. 
Rimando alle regole tecniche SPID, paragrafo 1.2.2 per dettagli.
(Rif. https://www.agid.gov.it/sites/default/files/repository_files/circolari/spid-regole_tecniche_v1.pdf).

Saluti

**Comment by danielebonfatti** [comment]
Grazie mille.
