### ISSUE TITLE
Request - Check Strict: errore nella sezione "Test if the XSD validates and if the signature is valid"

### ISSUE THREAD

**Issue by danielebonfatti** [italia/spid-saml-check#67]
Salve,
nell'ultima sezione appare un errore che sembra originarsi all'interno di uno o più script di validazione, causando "failure" come risultato.
![image](https://user-images.githubusercontent.com/62336036/83778555-2898f800-a68b-11ea-9d7c-086249c10876.png)
In allegato il report completo.
[Request Check Strict.pdf](https://github.com/italia/spid-saml-check/files/4731153/Request.Check.Strict.pdf)

**Comment by damikael** [comment]
Buongiorno @danielebonfatti ,
l'ambiente è stato eseguito tramite docker o installato manualmente?

Michele D'Amico

**Comment by danielebonfatti** [comment]
Buongiorno @damikael ,
l'ambiente è stato eseguito tramite Docker. Avevo una versione vecchia di qualche mese, quindi ho scaricato la nuova versione da Git (Git clone).
Grazie

**Comment by danielebonfatti** [comment]
Buongiorno @damikael ,
volevo sapere se è confermato che sia un errore dello strumento di validazione e, nel caso affermativo, se ci sono previsioni circa la sua risoluzione.
In alternativa, chiedo se la validazione possa comunque considerarsi conclusa positivamente anche in presenza di questa "failure".

Grazie

**Comment by damikael** [comment]
Verificare se con l'ultima versione il problema si presenta ancora. In tal caso aprire una nuova issue.
Grazie
