### ISSUE TITLE
Request - Check Extra

### ISSUE THREAD

**Issue by danielebonfatti** [italia/spid-saml-check#68]
Salve,
il test in oggetto termina, secondo i log del validatore, con successo, ma il report che viene generato non mostra il risultato. E' corretto che sia così?
![image](https://user-images.githubusercontent.com/62336036/83779887-ca6d1480-a68c-11ea-8f48-b18b7086784f.png)
[Request Check Extra.pdf](https://github.com/italia/spid-saml-check/files/4731239/Request.Check.Extra.pdf)

Grazie

**Comment by damikael** [comment]
È corretto, in relazione alla request non c'è nessun test che si applica.

**Comment by danielebonfatti** [comment]
Grazie mille
