### ISSUE TITLE
Errori Check Extra : Test the TLS configuration of Locations URL

### ISSUE THREAD

**Issue by haunted2** [italia/spid-saml-check#69]
Salve
Ho testato l'implementazione del nostro service provider spid usando lo spid-saml-check e tutti i test risultano passati con successo, tranne l'ultimo punto della sezione "Check Extra", ovvero:
"Test the TLS configuration of Locations URL"
nel quale le url dell' AssertionConsumerService  e del SingleLogoutService vengono testate per verificare se sono raggiungibili e se hanno una "strong TLS configuration".

Guardando al codice dello spid-saml-check, ho visto che tramite API, interroga il servizio www.ssllabs.com e si aspetta di ricevere un grade tra A+, A o A-.

Il nostro certificato ottiene infatti una B e i test risultano falliti.

Vorrei intanto sapere se questo punto è vincolante per la validazione. 
Inoltre, il motivo per cui ottiene una B, è:  "This server supports TLS 1.0 and TLS 1.1. Grade capped to B."

Guardando al link che riporta informazioni riguardo all'esito, https://blog.qualys.com/ssllabs/2018/11/19/grade-change-for-tls-1-0-and-tls-1-1-protocols?_ga=2.68055700.425621922.1592905425-1024498678.1588087530 ,
si vede che questo è un cambiamento introdotto di recente:
"Update 1/31/2020: The grade change is now live on www.ssllabs.com. Servers that support TLS 1.0 or TLS 1.1 are capped to B grade."

Mi chiedevo quindi se siete a conoscenza della cosa e se la validazione ne terrà conto (o se il tool verrà aggiornato di conseguenza).

Grazie.

**Comment by damikael** [comment]
Salve @haunted2 ,
il test non è vincolante per il superamento della validazione ed è accettato anche il grade B ottenuto su ssllabs.
A breve sarà aggiornato anche il controllo su spid-saml-check.
In ogni caso va tenuto presente che le regole tecniche SPID stabiliscono esplicitamente che:

_"è obbligatorio l'impiego di TLS nella versione più recente disponibile" (Rif. Regole tecniche 1.2.2.3)_

Saluti,
Michele D'Amico
