### ISSUE TITLE
Test 39 e 40

### ISSUE THREAD

**Issue by espositofulvio** [italia/spid-saml-check#73]
Salve,
ho qualche difficoltà con la validazione per i test 39 e 40:

39 . Assertion - Attributo IssueInstant precedente a IssueInstant della della request
40 . Assertion - Attributo IssueInstant successivo a IssueInstant della della request

Se ho ben compreso l'IssueInstant dell'Assertion nella response è uguale all'IssueInstant della Request ed infatti entrambi i test prevedono KO come risultato atteso. spid-validator però genera l'IssueInstant dell'Assertion come uguale al valore dell'IssueInstant della Response ed è possibile modificarlo solo se si modifica l'IssueInstant della Response. Se cambio questo valore però, fallisce poi il test 15:

15. Response - IssueInstant successivo request

poiché l'IssueInstant della Response diviene **non successivo** all'IssueInstant della Request.

Inoltre, dando uno sguardo ai sorgenti dell'ambiente https://github.com/italia/spid-testenv2 messo a disposizione per test locali ho visto che l'IssueInstant dell'Assertion viene calcolato come datetime.now() all'atto della generazione della Response.

A questo punto non so se è un problema del validator e dell'altro ambiente di test oppure ho capito male la specifica.
Qualcuno mi può aiutare a capire come venirne a capo? Come posso procedere?

**Comment by damikael** [comment]
Buonasera,

l'IssueInstant, sia della Response, che dell'Assertion, devono essere sicuramente successivi all'IssueInstant della Request, tuttavia non devono essere "troppo successivi", ovvero non devono eccedere un determinato limite di tempo (considerate le diverse implementazioni degli IdP può essere ritenuto valido un distanziamento massimo di 3min dalla Request).

Quindi i test n. 40 / n. 15 sono da intendersi come:
L'attributo IssueInstant dell'Assertion / Response non possono essere successivi all'IssueInstant della Request di oltre 3min.

**Comment by espositofulvio** [comment]
> Buonasera,
> 
> l'IssueInstant, sia della Response, che dell'Assertion, devono essere sicuramente successivi all'IssueInstant della Request, tuttavia non devono essere "troppo successivi", ovvero non devono eccedere un determinato limite di tempo (considerate le diverse implementazioni degli IdP può essere ritenuto valido un distanziamento massimo di 3min dalla Request).
> 
> Quindi i test n. 40 / n. 15 sono da intendersi come:
> L'attributo IssueInstant dell'Assertion / Response non possono essere successivi all'IssueInstant della Request di oltre 3min.

Buongiorno Michele,
in questo caso sarebbe utile precisare questo dettaglio nella documentazione. Ad esempio, con riferimento a https://docs.italia.it/italia/spid/spid-regole-tecniche/it/stabile/single-sign-on.html#assertion:

- Nell’elemento <Assertion> devono essere presenti i seguenti attributi:

  - l’attributo ID univoco, per esempio basato su un Universally Unique Identifier (UUID) o su una combinazione origine + timestamp (quest’ultimo generato con una precisione di almeno un millesimo di secondo per garantire l’univocità);
  - l’attributo Version, che deve valere sempre 2.0, coerentemente con la versione della specifica SAML adottata;
  - *l’attributo IssueInstant a indicare l’istante di emissione della richiesta, in formato UTC (esempio: 2017-03-01T15:05:10.531Z);*

Nell'ultimo punto si dice che l'IssueInstant deve indicare l'istante della richiesta, non un momento successivo. 

Anche la definizione del test inoltre andrebbe cambiata in quanto richiede esito negativo ma se la definizione è:

40 . Assertion - Attributo IssueInstant successivo a IssueInstant della della request

Si deduce che l'IssueInstant deve essere pari o inferiore all'IssueInstant della request (poi per il test 39 diviene sono pari e non inferiore).

Grazie mille.

**Comment by mauromol** [comment]
Scusatemi, ma questo discorso dell'`IssueInstant` dell'`Assertion` mi sembra un po' confuso...

Da specifiche SAML 2.0 (e in modo assolutamente ragionevole ed ovvio...), l'`IssueInstant` dell'`Assertion` è l'istante in cui l'asserzione è stata emessa: per questo motivo dev'essere necessariamente >= dell'`IssueInstant' della richiesta (`AuthnRequest`)... Sarà ragionevolmente uguale alla `IssueInstant` della `Response`, dato che l'asserzione viene emessa assieme alla risposta.

Il fatto che nelle specifiche tecniche originali di SPID ci sia scritto che, per l'`Assertion`, l'`IssueInstant` sia l'istante di emissione della "richiesta", è secondo me un banale errore di copia-incolla... perché altrimenti non ha molto senso, soprattutto nel momento in cui invece per la `Response` le stesse specifiche parlano di istante di emissione della risposta (e non di nuovo della richiesta).
Detto questo, è ragionevole pensare che l'`IssueInstant` dell'`Assertion`, così come quello della `Response`, non debbano essere nel futuro, per cui a mio parere l'errore 40 dovrebbe essere indicato come "Assertion - Attributo IssueInstant nel futuro" (con la già citata tolleranza dei 3 minuti, che mi sembra più convenzionale che normata, correggetemi se sbaglio).

Se poi l'intento della specifica era quello di non concedere troppo tempo tra richiesta e risposta/asserzione (posto che fatico a capire l'utilità di questo requisito), allora la cosa dovrebbe essere resa più esplicita sia dalle specifiche che dal validatore...

Cosa ne pensi @damikael? C'è qualcosa che mi sfugge?

**Comment by damikael** [comment]
Esattamente @mauromol, nulla da aggiungere.
Sono d'accordo nel rinominare il test come suggerisci "Attributo IssueInstant nel futuro"
