### ISSUE TITLE
Request strict - RequestedAuthnContext #4 incorrectly requires a single AuthnContextClassRef

### ISSUE THREAD

**Issue by lscorcia** [italia/spid-saml-check#75]
Hi,
I haven't been able to find in the tech rules ( https://docs.italia.it/italia/spid/spid-regole-tecniche/it/stabile/single-sign-on.html#authnrequest ) the paragraph corresponding to Test 4) in the `RequestedAuthnContext` section of the `Request` `Strict` tests.

I kind of agree that in the SPID context it doesn't really make sense supplying more than one ClassRef, given there's just three classes and we can use the Comparison element to allow higher levels, but the check looks wrong and should probably be removed.

**Comment by AntonioGiovanniSchiavone** [comment]
From SPID Tech Rules:

> nell’elemento `<AuthnRequest>` devono essere presenti i seguenti attributi:
> [omissis]
> deve essere presente l’elemento `<RequestedAuthnContext>` (SAMLCore, sez. 3.3.2.2.1) ad indicare il contesto di autenticazione atteso, ossia la «robustezza» delle credenziali richieste. Allo scopo sono definite le seguenti «authentication context class» estese (SAMLAuthContext, sez. 3) in riferimento SPID:

>* https://www.spid.gov.it/SpidL1
>* https://www.spid.gov.it/SpidL2
>* https://www.spid.gov.it/SpidL3
> referenziate dagli elementi `<AuthnContextClassRef>`

> Ciascuna di queste classi indica in ordine di preferenza il contesto di autenticazione (atteso o effettivo) secondo alcune dimensioni di riferimento, quali per esempio i meccanismi di autenticazione con cui l’Identity Provider può identificare l’utente. L’elemento `<RequestedAuthnContext>` prevede un attributo Comparison con il quale indicare il metodo per stabilire il rispetto del vincolo sul contesto di abilitazione: i valori ammessi per questo attributo sono:

>* exact
>* minimum
>* better
>* maximum
> Nel caso dell’elemento `<RequestedAuthnContext>`, questa informazione si riflette sulle tipologie di meccanismi utilizzabili dall’Identity Provider ai fini dell’autenticazione dell’utente. 



The plural in "referenziate dagli elementi `<AuthnContextClassRef>`" should not be intended as the possibility to have one or more `<AuthnContextClassRef>` inside a single AuthnRequest, but that  the «authentication context class» are referred by "the various `<AuthnContextClassRef>` tags in the various AuthnRequest messages".

In fact, later on:  

> Nel caso dell’elemento `<RequestedAuthnContext>`

Inside all the document,  the usage of singular definite article (il, lo, la) implies the presence of one and only one tag/attribute.
If one or more tag/attribute is allowed, it's explicitly indicated; for instance: 

> Può essere presente l’elemento <AttributeStatement> riportante gli attributi identificativi certificati dall’Identity Provider. Tale elemento se presente dovrà comprendere:

>* **uno o più elementi** di tipo <Attribute> relativi ad attributi che l’Identity Provider può rilasciare [omissis]
