### ISSUE TITLE
Metadata Strict - AssertionConsumerService test 8) is obsolete

### ISSUE THREAD

**Issue by lscorcia** [italia/spid-saml-check#76]
Hi,
I haven't been able to find in the tech rules ( https://docs.italia.it/italia/spid/spid-regole-tecniche/it/stabile/single-sign-on.html#authnrequest ) the paragraph corresponding to Test 8) in the `AssertionConsumerService` section of the `Metadata` `Strict` tests.

The constraint that requires the first element to have `index=0` and `default="true"` was indeed included in version 1 of the Tech Rules, but has been removed in the current stable version. Probably the test should be removed.

**Comment by damikael** [comment]
Hi,
from technical rules (Rif. https://www.agid.gov.it/sites/default/files/repository_files/circolari/spid-regole_tecniche_v1.pdf §1.3.2):

> deve essere presente almeno un elemento <AssertionConsumerService> indicante il servizio...
> In particolare il primo di questi elementi (o l’unico elemento riportato) deve obbligatoriamente riportare:
> - l’attributo index posto al valore 0;
> - l’attributo isDefault posto al valore true;

**Comment by lscorcia** [comment]
Thanks, I found the correct reference at https://docs.italia.it/italia/spid/spid-regole-tecniche/it/stabile/metadata.html#service-provider .
