### ISSUE TITLE
"Service not available" durante l'esecuzione di un test

### ISSUE THREAD

**Issue by PardeepOne** [italia/spid-saml-check#77]
Ciao, seguendo il Readme ho mandato in esecuzione il tool e in seguito l'ho configurato come un IDP nella applicazione SP.
Quindi ho lanciato una richiesta di autenticazione verso questo nuovo IDP ed effettivamente vedo che arriva al validatore dove riesco a fare login con utente/password "validatore".

Tuttavia se in seguito provo a lanciare un qualsiasi test vedo che il test viene iniziato ma dopo qualche minuto vedo il pop-up `Service unavailable` e non vedo nessun report del test appena andato in fallimento.
Ho dimenticato di configurare qualcosa?
Grazie.

**Comment by damikael** [comment]
Probabilmente la request o il metadata sono malformati.
Occorre in ogni caso avere maggiori dettagli in merito all'errore riscontrato dal Validator oppure riferimenti di metadata e request per replicare il problema.

**Comment by PardeepOne** [comment]
Incollo il mio metadata così come lo rendo disponibile dal mio SP (con URL `http://localhost:8091/DM-WEB/saml/metadata`):
```
<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" ID="co" entityID="com:example:sp"><ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#"><ds:SignedInfo><ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/><ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/><ds:Reference URI="#com_example_sp"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/><ds:DigestValue>/QmMQDbIO4oX7V9FTXePBXitJD1+L5fZs/qUtKreMHs=</ds:DigestValue></ds:Reference></ds:SignedInfo><ds:SignatureValue>[ ... ]</ds:SignatureValue><ds:KeyInfo><ds:X509Data><ds:X509Certificate>[ ... ]</ds:X509Certificate></ds:X509Data></ds:KeyInfo></ds:Signature><md:SPSSODescriptor AuthnRequestsSigned="true" WantAssertionsSigned="true" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol"><md:KeyDescriptor use="signing"><ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#"><ds:X509Data><ds:X509Certificate>[ ... ]</ds:X509Certificate></ds:X509Data></ds:KeyInfo></md:KeyDescriptor><md:KeyDescriptor use="encryption"><ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#"><ds:X509Data><ds:X509Certificate> [ ... ]</ds:X509Certificate></ds:X509Data></ds:KeyInfo></md:KeyDescriptor><md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://localhost:8091/DM-WEB/saml/SingleLogout"/><md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="http://localhost:8091/DM-WEB/saml/SingleLogout"/><md:NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:transient</md:NameIDFormat><md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="http://localhost:8091/DM-WEB/saml/SSO" index="0" isDefault="true"/><md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact" Location="http://localhost:8091/DM-WEB/saml/SSO" index="1"/><md:AttributeConsumingService index="0"><md:ServiceName xmlns:xml="http://www.w3.org/XML/1998/namespace" xml:lang="en">SP test</md:ServiceName><md:ServiceDescription xmlns:xml="http://www.w3.org/XML/1998/namespace" xml:lang="en">Test Service</md:ServiceDescription><md:RequestedAttribute FriendlyName="name" Name="name" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic" isRequired="true"/><md:RequestedAttribute FriendlyName="fiscalNumber" Name="fiscalNumber" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic" isRequired="true"/></md:AttributeConsumingService></md:SPSSODescriptor></md:EntityDescriptor>
```

**Comment by damikael** [comment]
Il Validator rileva il seguente errore al download del metadata:

`Si è verificato un errore durante il parsing del file xml. Error: Organization non definito`

**Comment by PardeepOne** [comment]
Grazie, ho aggiunto la parte di `Organization` e `ContactPerson` nella generazione del metadata, e questo nuovo metadata l'ho provato anche su Spid Test IDP che non mi ha dato problemi.
Tuttavia tornando al validatore ho ancora qualcosa che si rompe come in figura.
![tempScreen](https://user-images.githubusercontent.com/18119667/92720650-31bdf300-f365-11ea-9611-a2ee2167b5fb.png)

**Comment by PardeepOne** [comment]
Ho risolto l'ultimo errore indicato *non usando* l'url `http://localhost:8091/DM-WEB/saml/metadata` ma quello con l'indirizzo IP locale effettivo della macchina host (quindi nel mio caso era `http://192.168.1.242:8091/DM-WEB/saml/metadata`).
