### ISSUE TITLE
Confronto con entityID precedente

### ISSUE THREAD

**Issue by walter-arrighetti** [italia/spid-saml-check#78]
Il sistema dovrebbe verificare, incrociando il database SPID tramite il codice IPA o la P.IVA del SP pubblico/privato (così come dichiarato nel `<ContactPerson>` di rilievo del metadata in fase di collaudo) e, da li, con il precedente metadata presente nel registro SPID, che l'EntityID non stia cambiando tra le successive versioni del metadata.
Il sistema, riconoscendo la tipologia di metadata (e l'eventuale codice attività ex Avviso SPID №19), dovrebbe anche essere in grado di gestire i casi di un soggetto che, a seguito della stipula di più Convenzioni diverse:

- SP pubblico,
- SP privato,
- Aggregatore di SP pubblici (incluso il Gestore di pubblico servizio),
- Aggregatore di SP privati,
- soggetto aggregato da uno o più Aggregatori diversi;

può presentarsi nella federazione SPID con più metadata diversi, come unica eccezione al vincolo di immutabilità dell'EntityID di cui sopra. Si consultino in proposito gli Avvisi SPID №29 (per SP pubblici e privati) e №19 (per Aggregatori, Gestori e aggregati).

**Comment by damikael** [comment]
Tale vincolo è già presente a livello di integrità relazionale sul database SPID. 
Il controllo esula dal funzionamento del tool spid-saml-check il cui scopo è esclusivamente verificare la conformità di metadata, request ed esito alle response rispetto alle specifiche SPID.
