### ISSUE TITLE
Response test 103 sends empty AttributeStatement

### ISSUE THREAD

**Issue by PardeepOne** [italia/spid-saml-check#80]
Ciao, sto provando con i test per la `Response` e ho notato che il test `n° 103` dovrebbe fare la cosa di inviare un _"set di attributi inviato diverso da quello richiesto"_, ma per ora vedo che mi manda un `Response` con il seguente `AttributeStatement`:

```
<saml:AttributeStatement>

</saml:AttributeStatement>
```

Così mi sembra uguale al test `n° 98` che fa la cosa di _"Elemento AttributeStatement presente, ma sottoelemento Attribute mancante"_ oppure mi sbaglio?

Grazie.

**Comment by damikael** [comment]
Ciao @PardeepOne ,
probabilmente il metadata contiene un AttributeConsumingService vuoto.
Per verificare correttamente il test #103:

- utilizza un AttributeConsumingService che specifica diversi attributi spid, tra cui almeno _spidCode_ e _address_. 
- invia la request richiedendo tale AttributeConsumingService 

la response #103, quindi, dovrebbe selezionare per l'invio, non tutti gli attributi presenti nel test, ma solo _spidCode_ e _address_ configurandosi pertanto come set di attributi diverso, in quanto mancante degli altri attributi inseriti nel set

**Comment by PardeepOne** [comment]
Grazie @damikael .. confermo che inserendo i due attributi `spidCode` e `address` nel metadata il test `#103` funziona come dovrebbe. Chiudo la issue.
Grazie.

**Comment by mauromol** [comment]
Ciao @damikael,
scusa l'intrusione, ma a me non è chiaro quale dovrebbe essere il risultato atteso per questo test 103: OK o KO?
Nel validatore non c'è scritto (a mio parere andrebbe indicato): l'SP dovrebbe "arrabbiarsi" ed andare in errore oppure dovrebbe cercare di gestire in modo lenient l'assenza di alcuni degli attributi che aveva richiesto? Anche perché in teoria ci sarebbe di mezzo il discorso degli attributi "required" o non "required", che non mi sembra affrontato da SPID.
Le regole tecniche non sono d'aiuto, perché dicono che l'assertion deve comprendere "uno o più elementi di tipo `<Attribute>` relativi ad attributi che l’_Identity Provider_ **può** rilasciare (cfr. Tabella attributi SPID) su richiesta del _Service Provider_ espressa attraverso l’attributo **_AttributeConsumingServiceIndex_** quando presente nella _authnrequest_": quel "può" lascia quasi intendere che potrebbe anche non rilasciarne alcuni (anche se non è chiarito in che termini)...

Grazie!

**Comment by damikael** [comment]
Ciao @mauromol ,
la tabella attributi SPID specifica quali attributi l'IdP può rilasciare, ovvero l'IdP non può rilasciare ulteriori attributi o attributi diversi da quelli indicati nella tabella attributi e s.m.i. indicate da AgID (es. [Avviso 25](https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n25-nuova-codifica-domicilio_fisico.pdf))
La response dell'IdP deve contenere gli attributi dell'identità richiesti dal SP con lo specifico AttributeConsumingServiceIndex, eventualmente vuoti se per l'identità l'attributo non è presente (L'elemento AttributeValue deve essere sempre presente eventualmente vuoto).
Il test 103 "Set di attributi inviato diverso da quello richiesto", pertanto, è da leggere in relazione alla request inviata. Se il SP invia una Request con un AttributeConsumingServiceIndex per il quale è atteso un determinato set di attributi, e l'IdP restituisce un set di attributi diverso, il SP deve accorgersi dell'errore e saperlo gestire. Ciò significa che, in fase di collaudo dell'implementazione, in relazione al test occorre dare evidenza della capacità del SP di riconoscere tale situazione.

**Comment by mauromol** [comment]
Grazie @damikael, però ancora non mi è chiaro come l'SP dovrebbe riconoscere questa situazione. Intendo dire:
- deve dare OK, ergo: l'utente viene autenticato, ed in qualche modo il servizio finale deve gestire (se può) l'eventuale mancata specifica di uno (o più) degli attributi che ha richiesto ma che non gli sono stati inviati
- oppure deve dare KO, ergo: l'utente NON viene autenticato, ma viene riportato un messaggio d'errore che indica la presenza di un problema (ed eventualmente: "contattare il gestore dell'identità")

Quale delle due?

Per quanto riguarda il discorso della presenza o meno dell'`AttributeValue`, questo è un altro argomento controverso per il quale ti ho scritto qui: https://github.com/italia/spid-saml-check/issues/137#issuecomment-819676374
Di fatto, questi due sono gli ultimi controlli che mi mancano da smarcare.

**Comment by damikael** [comment]
Ciao @mauromol , il test 103 deve dare KO.

**Comment by mauromol** [comment]
D'accordo, grazie @damikael! Se posso dare un suggerimento, sarebbe utile aggiungere il risultato atteso anche sulla UI del validatore.

**Comment by damikael** [comment]
Ok, grazie del suggerimento.
