### ISSUE TITLE
Valore Issue della Response

### ISSUE THREAD

**Issue by danielebonfatti** [italia/spid-saml-check#81]
Salve,
nella validazione della Response mi sono reso conto che il valore del campo Issuer è errato: infatti non coincide con entityId dell'IDP (si veda in figura).
Ho installato l'IDP di test dietro ad un web server Apache, in che modo posso modificare quel valore?

Cordiali saluti

![image](https://user-images.githubusercontent.com/62336036/95182103-79993400-07c4-11eb-84a5-ba679d60a76e.png)

**Comment by damikael** [comment]
Salve @danielebonfatti ,
è possibile modificare la configurazione nel file:

/spid-validator/config/idp.json

Saluti,
Michele D'Amico

**Comment by danielebonfatti** [comment]
Grazie mille
