### ISSUE TITLE
Error Organization non definito

### ISSUE THREAD

**Issue by codeweb** [italia/spid-saml-check#83]
Ciao,

> va scaricato il metadata SAML disponibile all'indirizzo http://localhost:8080/metadata.xml installandolo come un nuovo IdP presso la propria implementazione di SP. 

Quando clicco download ho l'errore di parsing xml: "Organization non definito". Cosa significa "installandolo"?
Inoltre potete spiegare meglio le operazioni da compiere per installare il file metadata.xml come nuovo IdP presso il proprio SP?
Ho modificato nell'app di test .Net Global.asax e Index della View.

**Comment by damikael** [comment]
Salve,
il metadata del Validator, disponibile all'indirizzo http://localhost:8080/metadata.xml, deve essere "installato" ovvero configurato sul proprio Service Provider, in modo da essere presente sul bottone "Entra con SPID" alla stregua di un normale Identity Provider. Tale configurazione dipende dalla specifica implementazione.

La funzionalità di download del Validator serve, invece, a caricare il metadata del Service Provider all'interno dell'ambiente da Identity Provider del Validator.

**Comment by codeweb** [comment]
Forse mi sfugge qualcosa. Sto usando sdk .Net con le app di test.
`il metadata del Service Provider` si tratta di un metadata.xml che io inserisco nella directory dell'applicazione e configuro con certificato, url ed entityId del saml-check. L'url che inserisco nella sezione del download è in 
http://localhost:<porta>/metadata.xml
L'applicativo non fa nulla e non genera errori.

**Comment by damikael** [comment]
Il metadata del Service Provider è il metadata descrittivo del proprio Service Provider contenente certificato, endpoint ed EntityID del SP e va configurato presso gli Identity Provider (ovvero sul Validator di spid-saml-check).
Specularmente, il metadata del Validator, come i metadata degli Identity Provider, contengono i rispettivi certificati, endpoint ed EntityID degli IdP e vanno configurati presso l'SP. La configurazione del metadata da IdP presso l'SP permette di "attivare" il relativo link sul bottone Entra con SPID, sul SP, per l'autenticazione presso lo specifico provider.
Per indicazioni su come configurare il metadata del Validator (http://localhost:8080/metadata.xml) sul proprio SP, consiglio di chiedere sul repository dello specifico SDK.

**Comment by codeweb** [comment]
`Il metadata del Service Provider è il metadata descrittivo del proprio Service Provider contenente certificato, endpoint ed EntityID del SP e va configurato presso gli Identity Provider (ovvero sul Validator di spid-saml-check).`
Questo dovrebbe farlo il tasto "Download" di spid-saml-check (che attualmente non mi dà alcun responso).
Non è necessario che l'url sia in https, vero?

**Comment by damikael** [comment]
Questo dovrebbe farlo il tasto "Download" di spid-saml-check (che attualmente non mi dà alcun responso).
Esatto. Se il metadata non viene caricato è possibile che l'xml non sia formattato nel modo corretto.

Non è necessario che l'url sia in https, vero?
Non è necessario

**Comment by codeweb** [comment]
> Per indicazioni su come configurare il metadata del Validator (http://localhost:8080/metadata.xml) sul proprio SP, consiglio di chiedere sul repository dello specifico SDK.
Volevo solo segnalare che sul repository specifico non risponde nessuno
