### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined

### ISSUE THREAD

**Issue by youthzu** [italia/spid-saml-check#84]
Provando a verificare la conformità alle regole SPID sulle request ricevo questo errore:

`
>>> DATABASE EXCEPTION (setMetadataValidation)
"TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined"
(node:18) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (buffer.js:329:9)
    at Function.btoa (/spid-saml-check/spid-validator/server/lib/utils.js:120:23)
    at Database.saveStore (/spid-saml-check/spid-validator/server/lib/database.js:98:45)
    at Database.setRequestValidation (/spid-saml-check/spid-validator/server/lib/database.js:387:18)
    at /spid-saml-check/spid-validator/server/api/request.js:118:34
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)

`

**Comment by damikael** [comment]
Occorre verificare che il metadata del SP sia correttamente caricato nella relativa sezione e che l'Issuer della Request corrisponda esattamente all'EntityID dichiarato nel metadata.
