### ISSUE TITLE
Aggiungere supporto https

### ISSUE THREAD

**Issue by fume** [italia/spid-saml-check#86]
L'applicazione node.js è in ascolto solo ed esclusivamente su porta 8080 per il protocollo http. Sarebbe decisamente utile fosse in ascolto anche su altra porta per il protocollo https (anche con certificati self-signed, configurabili o no).
Alcune librerie/prodotti non consentono di utilizzare idp che non supportano il protocollo https.

**Comment by damikael** [comment]
Buonasera @fume ,
consiglio di esporre l'applicativo in https tramite un reverse proxy. Di seguito una configurazione di esempio per Nginx:

```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://localhost:8080/;
        proxy_ssl_session_reuse off;
        proxy_set_header Host $http_host;
        proxy_cache_bypass $http_upgrade;
    }
}
```

**Comment by fume** [comment]
ciao @damikael ,
mi rendo conto di essere stato poco preciso nella descrizione dell'issue.
Personalmente, sto già utilizzando nginx come reverse proxy per avere un endpoint https (con cert self-signed).

Quello che volevo proporre (decisamente non chiaro nel mio primo messaggio, mea culpa), era di integrare la cosa nel readme per chi ne avesse bisogno. Per chi usa il tool containerizzato, potrebbe essere utile avere anche un docker-compose-yml. Se lo gradite, posso condividere il mio, corredato anche dal nginx.conf corrispondente.

In ogni caso, nella config nginx da te condivisa mancano i parametri ssl_certificate e ssl_certificate_key, ovviamente obbligatori se si usa https/ssl.

saluti,

**Comment by damikael** [comment]
Grazie @fume, ogni contributo è ben accetto.

**Comment by fume** [comment]
ciao @damikael , appena possibile faccio una PR.

saluti
