### ISSUE TITLE
Domanda - Avviso n.29/2020

### ISSUE THREAD

**Issue by GeorgeBortov** [italia/spid-saml-check#88]
Buonasera,

Seguendo l'Avviso n.29/2020 ho aggiunto per il tag ContactPerson con attributo “billing” le informazioni di fatturazione elettronica.
```
<md:ContactPerson contactType="billing">
    <md:Extensions xmlns:fpa="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2">
      <fpa:CessionarioCommittente>
        <fpa:DatiAnagrafici>
          <fpa:IdFiscaleIVA>
            <fpa:IdPaese>IT</fpa:IdPaese>
            <fpa:IdCodice>11111111111</fpa:IdCodice>
          </fpa:IdFiscaleIVA>
          <fpa:Anagrafica>
            <fpa:Denominazione>Test S.r.l.</fpa:Denominazione>
          </fpa:Anagrafica>
        </fpa:DatiAnagrafici>
        <fpa:Sede>
          <fpa:Indirizzo>Via test</fpa:Indirizzo>
          <fpa:NumeroCivico>11/11</fpa:NumeroCivico>
          <fpa:CAP>00000</fpa:CAP>
          <fpa:Comune>Roma</fpa:Comune>
          <fpa:Provincia>RM</fpa:Provincia>
          <fpa:Nazione>IT</fpa:Nazione>
        </fpa:Sede>
      </fpa:CessionarioCommittente>
    </md:Extensions>
    <md:Company>Test S.r.l.</md:Company>
    <md:EmailAddress>email@pec.it</md:EmailAddress>
    <md:TelephoneNumber>+3911111111111</md:TelephoneNumber>
</md:ContactPerson>
```
Ho provato di passare la validazione con lo SPID Validator  (l'ultima versione v.1.4.1) e ricevo sempre l'errore:` "Element '{http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2}CessionarioCommittente': This element is not expected.” 
`(vedi screenshot-1 in allegato).
screenshot-1
![screenshot-1](https://user-images.githubusercontent.com/41924906/96900050-f51c0600-1491-11eb-9423-524cc87a1141.png)
Secondo me il namespace `xmlns:spid=“https://spid.gov.it/saml-extensions”` dichiarato nel EntityDescriptor non accetta i tag dentro ‘Extensions’ diversi dall ‘IPACode’, ‘VATNumber’, ‘FiscalCode’, ‘Public’, ‘Private’, anche se dentro tag Extensions ha un altro namespace dichiarato.
Se invece tolgo namespace `xmlns:spid=“https://spid.gov.it/saml-extensions”` dall’EntityDescriptor il test ‘Check XSD’ sarà sempre skippato da validator. (vedi screenshot-2 in allegato).
screenshot-2
![screenshot-2](https://user-images.githubusercontent.com/41924906/96900046-f3524280-1491-11eb-84d9-90672e85aa86.png)
La mia domanda è: come devo generare il mio metadata per passare il test ‘Check XSD’? Con namespace `xmlns:spid=“https://spid.gov.it/saml-extensions”` dichiarato nel EntityDescriptor o senza?

Grazie, in anticipo

**Comment by damikael** [comment]
Buongiorno @GeorgeBortov ,
SPID SAML Check ancora non supporta la validazione di metadata per SP privati.
A breve saranno rilasciati alcuni chiarimenti in merito ai metadata per SP privati e sarà rilasciata la nuova versione di spid-saml-check.

**Comment by damikael** [comment]
La versione 1.5.2 implementa la validazione dell'elemento CessionarioCommitente
