### ISSUE TITLE
Metadata check strict: only one SPSSODescriptor must be present

### ISSUE THREAD

**Issue by lscorcia** [italia/spid-saml-check#90]
Buongiorno, nella mia amministrazione (PA Centrale) stiamo razionalizzando i metadati SPID per essere compliant con l'avviso pubblico n. 29 e stiamo cogliendo l'occasione per accorpare i diversi metadati creati negli anni per scopi e da soggetti differenti.
L'accorpamento richiederebbe di includere più tag SPSSODescriptor all'interno dello stesso metadato (i metadati condivideranno lo stesso entityID).

Il tool spid-saml-check al momento verifica che il metadato contenga esplicitamente un solo SPSSODescriptor:

![immagine](https://user-images.githubusercontent.com/16761934/97057347-4cea6800-158b-11eb-9c43-9bc8b15fcb4c.png)

Tuttavia non vedo nulla nelle regole tecniche che imponga che di questo tag ve ne sia al più uno. Tra l'altro da alcuni post sul forum Italia, pare che questa sia la soluzione ufficialmente consigliata dal team SPID: https://forum.italia.it/t/diversi-sp-per-un-singolo-ente/916/10 .

Si tratta di un bug del validatore o effettivamente questa tecnica non è consentita in produzione?
Grazie e buona giornata

**Comment by lscorcia** [comment]
Chiudo questa issue perché a quanto pare è proprio così: è un'altra non-conformità di SPID rispetto a SAML2.
https://forum.italia.it/t/un-ente-un-metadato-piu-spssodescriptor/17228/3

Ho aperto una pull request sul repo delle regole tecniche per documentare meglio questa ennesima eccezione.

**Comment by lscorcia** [comment]
In realtà probabilmente la issue è valida: nell'XSD relativo all'avviso 29, l'elemento è dichiarato unbounded:
https://github.com/italia/spid-saml-check/blob/8c1b7169f40325984ef80c320d7a1148d490d5ef/specs-compliance-tests/xsd/saml-schema-metadata-sp-spid-av29.xsd#L114-L116

Aspettiamo quindi una risposta ufficiale al dubbio...

**Comment by damikael** [comment]
Confermo quanto indicato nelle regole tecniche che è previsto un solo elemento SPSSODescritptor per metadata. 
Per accorpare più metadata occorre, pertanto, inserire nell'unico SPSSODescriptor i certificati e gli endpoint dei diversi servizi.
L'XSD su spid-saml-check, invece, sarà corretto.

Saluti,
Michele
