### ISSUE TITLE
Errori validazione Request

### ISSUE THREAD

**Issue by fume** [italia/spid-saml-check#91]
Salve,
di seguito alcuni errori riportati dal tool che però sembrano essere incorretti o che richiedono aggiornamento/precisazioni delle regole tecniche:

- **Check Strict n7: The IssueInstant attribute must be a valid UTC string**
  - L'IssueIstant presente nella request è nel seguente formato: 2020-10-24T09:11:16.861873Z
  - L'unica diffrenza rispetto all'esempio contenuto nelle regole tecniche è il numero di cifre decimali dopo i secondi.
    *L'AuthnRequest deve avere le seguenti caratteristiche: [...] l’attributo IssueInstant a indicare l’istante di emissione della richiesta, in formato UTC (esempio: “2008-03-13T18:04:15.**531**Z”)*
  - La RegEx applicata dal tool di validazione verifica la presenza ESATTA di sole 3 cifre decimali o nessuna cifra decimale dopo i secondi
    *^\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}:\d{2}(\.\d{3})?Z$*
     il concetto di "formato UTC" è lasciato all'interpretazione. Se parliamo di standard ISO8601, esistono decisamente altre modalità per rappresentare uno stesso instant (ad esempio, senza i due punti, senza la T, etc.) che non sono contemplate in questa RegEx
- **Check Strict n10: The Destination attribute must be a valid HTTPS url**
  - La Destination presente nella request è: https://localhost/samlsso
  - Non è un problema bloccante, in quanto l'url in produzione sarà sicuramente diversa (https://validator.spid.gov.it/samlsso)
- **Check Extra n1: The ForceAuthn attribute must be True because of minimum/SpidL1**
  - Nella request è specificato un AuthnContextClassRef pari a https://www.spid.gov.it/SpidL1
  - ForceAuthn=true non è richiesto SOLO per SpidL2 e superiori?
    *nell’elemento AuthnRequest devono essere presenti i seguenti attributi: [...] l’attributo ForceAuthn nel caso in cui si richieda livelli di autenticazione superiori a SpidL1 (SpidL2 o SpidL3)*

**Comment by fume** [comment]
ping

**Comment by fume** [comment]
salve,
il check strict n7 continua ad affliggere le richieste di accreditamento... è palesemente un errore!
saluti,

**Comment by piglione73** [comment]
Ping

**Comment by piglione73** [comment]
Anche il punto 1

**Comment by damikael** [comment]
Il codice relativo ai controlli sarà spostato sul seguente repository.
Le segnalazioni saranno prese in considerazione sulla issue:
https://github.com/italia/spid-sp-test/issues/24

Grazie

**Comment by AntonioGiovanniSchiavone** [comment]
Vado a memoria, ma se non sbaglio è il SAML che stabilisce che la precisione delle date deve essere al secondo o al millesimo di secondo. Non sarebbero quindi ammesse precisioni maggiori (ad es. al milionesimo di secondo) o intermedie (ad es. al decimo di secondo).

**Comment by peppelinux** [comment]
Per IssueInstant (fonte: https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf)

````
1.3.3 Time Values

All SAML time values have the type xs:dateTime, which is built in to the W3C XML Schema Datatypes
specification [Schema2], and MUST be expressed in UTC form, with no time zone component.
SAML system entities SHOULD NOT rely on time resolution finer than milliseconds. Implementations
MUST NOT generate time instants that specify leap seconds.
````

questo è il riferimento a W3C: https://www.w3.org/TR/xmlschema-2/#isoformats
e questa è la regex del test che faceva il match sul valore iso8601:
r'^\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}:\d{2}(\.\d{3})?Z$'

Questa è la nuova regex completamente conforme a iso8601, appena introdotta in spid-sp-test (https://github.com/italia/spid-sp-test/commit/4e1e814b73479b87535d5a0f0515cfc1234eae89)
r'^(-?(?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9])T(2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9])(\.[0-9]+)?(Z|[+-](?:2[0-3]|[01][0-9]):[0-5][0-9])?$'

Grazie a tutti per la preziosa analisi e condivisione
