### ISSUE TITLE
Immagine Docker ufficiale?

### ISSUE THREAD

**Issue by ilgrosso** [italia/spid-saml-check#96]
Sarebbe possibile avere una immagine Docker ufficiale del presente repository pubblicata su Docker Hub?

Al momento ne esistono diverse, ma tutte più o meno obsolete.

FYI ne ho appena pubblicata una basata sull'ultimo tag disponibile v.1.5.2.: https://hub.docker.com/r/tirasa/spid-saml-check

**Comment by damikael** [comment]
L'immagine ufficiale è stata pubblicata:
https://hub.docker.com/r/italia/spid-saml-check
