### ISSUE TITLE
error in 'verify the SP metadata signature' test

### ISSUE THREAD

**Issue by gabrimonfa** [italia/spid-saml-check#97]
In parameters passed to xmlsec1 to verify SP signature, I think EntityDescription should not be separated from previous parameter.
Patch attached

[sp_signature.zip](https://github.com/italia/spid-saml-check/files/5732629/sp_signature.zip)

**Comment by damikael** [comment]
@psmiraglia can you review, please

**Comment by damikael** [comment]
Moved to https://github.com/italia/spid-sp-test/issues/51
