### ISSUE TITLE
Errore di validazione XSD utilizzando Extensions per altri elementi che non siano ContactPerson

### ISSUE THREAD

**Issue by ilgrosso** [italia/spid-saml-check#98]
L'elemento `md:Extensions` definito come figlio di `md:EntityDescriptor`:

```xml
<md:EntityDescriptor ...>
  <md:Extensions xmlns:alg="urn:oasis:names:tc:SAML:metadata:algsupport">
    <alg:SigningMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
    <alg:SigningMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha384"/>
    <alg:SigningMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha512"/>
    <alg:SigningMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
    <alg:SigningMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256"/>
    <alg:SigningMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha384"/>
    <alg:SigningMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha512"/>
    <alg:SigningMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha1"/>
    <alg:SigningMethod Algorithm="http://www.w3.org/2000/09/xmldsig#dsa-sha1"/>
    <alg:SigningMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#hmac-sha256"/>
    <alg:SigningMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#hmac-sha384"/>
    <alg:SigningMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#hmac-sha512"/>
    <alg:SigningMethod Algorithm="http://www.w3.org/2000/09/xmldsig#hmac-sha1"/>
    <alg:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
    <alg:DigestMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#sha384"/>
    <alg:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
  </md:Extensions>
```

oppure l'elemento  `md:Extensions` definito come figlio di `md:SPSSODescriptor`:

```xml
  <md:SPSSODescriptor ...>
    <md:Extensions xmlns:init="urn:oasis:names:tc:SAML:profiles:SSO:request-init">
      <init:RequestInitiator Binding="urn:oasis:names:tc:SAML:profiles:SSO:request-init" Location="XXX"/>
    </md:Extensions>
```

generano il seguente errore di validazione rispetto a `saml-schema-metadata-2.0.xsd`:

```
[FAIL] the metadata must validate against the XSD
stderr: ./data/https___spid_gdf_gov_it_8443/sp-metadata.xml:56: element SigningMethod: Schemas validity error : Element '{urn:oasis:names:tc:SAML:metadata:algsupport}SigningMethod': This element is not expected. Expected is one of ( {https://spid.gov.it/saml-extensions}IPACode, {https://spid.gov.it/saml-extensions}VATNumber, {https://spid.gov.it/saml-extensions}FiscalCode, {https://spid.gov.it/saml-extensions}Public, {https://spid.gov.it/saml-extensions}Private, {https://spid.gov.it/invoicing-extensions}CessionarioCommittente ).
stderr: ./data/https___spid_gdf_gov_it_8443/sp-metadata.xml:75: element RequestInitiator: Schemas validity error : Element '{urn:oasis:names:tc:SAML:profiles:SSO:request-init}RequestInitiator': This element is not expected. Expected is one of ( {https://spid.gov.it/saml-extensions}IPACode, {https://spid.gov.it/saml-extensions}VATNumber, {https://spid.gov.it/saml-extensions}FiscalCode, {https://spid.gov.it/saml-extensions}Public, {https://spid.gov.it/saml-extensions}Private, {https://spid.gov.it/invoicing-extensions}CessionarioCommittente ).
stderr: ./data/https___spid_gdf_gov_it_8443/sp-metadata.xml fails to validate
```

perché ogni elemento `Extensions` viene trattato come se fosse figlio di `md:ContactPerson`.

**Comment by salvi75** [comment]
Si sta presentando questo problema perchè è stato modificato il type dell'elemento `md:Extensions` nell'xsd utilizzato per la validazione del metadata, da

`<element name="Extensions" type="md:ExtensionsType"/>`
in
`<element name="Extensions" type="md:ContactPersonExtensionType"/>`

In particolare nei seguenti schema:

- saml-schema-metadata-aggregated-spid.xsd
- saml-schema-metadata-sp-spid-av29.xsd

Forse bisognava lavorare nella definizione del nuovo tipo appartenente al namespace `https://spid.gov.it/saml-extensions` e utilizzarlo all'interno dell'elemento ` md:Extensions`  non modificandone il tipo.

Per esempio : 

`<element name="ContactPersonExtension" type="spid:ContactPersonExtensionType"/>`

**Comment by peppelinux** [comment]
In effetti questo problema parrebbe persistere.
Nel mio esempio abbiamo  un elemento `<md:Extension` come segue

![immagine](https://user-images.githubusercontent.com/1297620/106248567-77defa80-6211-11eb-8906-1eca5c09a883.png)

E di fatto la validazione fa un po confusione

![immagine](https://user-images.githubusercontent.com/1297620/106248631-8c22f780-6211-11eb-8144-866f2371effb.png)

**Comment by AlessandraB19** [comment]
L'esito dello stesso test nel mio caso è il seguente

the metadata must validate against the XSD stderr: ./data/https___spid_composingstudio_com/sp-metadata.xml:63: element CessionarioCommittente: Schemas validity error : Element '{https://spid.gov.it/invoicing-extensions}CessionarioCommittente': This element is not expected. Expected is one of ( {https://spid.gov.it/saml-extensions}IPACode, {https://spid.gov.it/saml-extensions}VATNumber, {https://spid.gov.it/saml-extensions}FiscalCode, {https://spid.gov.it/saml-extensions}Public, {https://spid.gov.it/saml-extensions}Private ). stderr: ./data/https___spid_composingstudio_com/sp-metadata.xml fails to validate

E' stata trovata una soluzione?

**Comment by peppelinux** [comment]
Ciao @AlessandraB19,
è solo questione di tempo per me, troverò il modo di aggiornare spid-django così da superare questa anomalia.
E' possibile che con @damikael decideremo anche di aggiornare il controllo di spid-saml-check su questo aspetto.
Grazie per la pazienza e a presto su questo thread

**Comment by AlessandraB19** [comment]
Quindi si può bypassare il relativo test Check XSD?

**Comment by peppelinux** [comment]
Bypassare non credo che sia corretto, 
devo tornare su questo progetto per la risoluzione di questo problema, non posso neanche escludere che sia spid-saml-check a fare una patch oppure io un workaround. Devo metterci mano

intanto mi confermi che con spid-testenv2 va tutto bene?

**Comment by AlessandraB19** [comment]
Purtroppo no, sia su testenv2 che con il validator riscontro il seguente problema
SimpleSAML_Error_Error: UNHANDLEDEXCEPTION

1 www/_include.php:17 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: SimpleSAML_Error_Exception: State not found for ID spid-php_2b59326503d01b064fb0d6e6f5f4f9a1454f6dd951
2 /home/spid/spid-php/setup/simplesamlphp/simplesamlphp/modules/saml/lib/Message.php:607 (sspmod_saml_Message::processResponse)
1 modules/saml/www/sp/saml2-acs.php:129 (require)
0 www/module.php:135 (N/A)

può esserci un collegamento tra le due situazioni?

**Comment by peppelinux** [comment]
Questa non è una eccezione di spid-saml-check ma della libreria PHP che stai utilizzando. La issue devi istruirla sul repository della libreria PHP e non qui
