### ISSUE TITLE
SAMLResponse - Digest errato validando la signature

### ISSUE THREAD

**Issue by valentinoavon** [italia/spid-saml-check#99]
Buongiorno,
sto cercando di testare l'implementazione del mio service provider (in node.js) con lo spid validator. Ho caricato lo spid validator tramite docker e tranquillamente riesco ad inviargli una SAML request per effettuare un login.

Il problema sorge quando lo spid validator mi inoltra la risposta SAML. 
In particolare, quando cerco di verificarne la firma (tramite libreria xml crypto, la quale è usata anche dallo spid validator stesso) ho un errore che dice che il digest calcolato non combacia con quello definito nella SAML response.

**La cosa strana è che lo stesso codice testato sull'ambiente spid test env 2 funziona perfettamente.**

Quello che ho fatto è:

- estratto dal body della SAML response l'xml
    ` const rawXml = Buffer.from(req.body.SAMLResponse, 'base64').toString('utf-8');`

- verificato la signature con questa chiamata

```
const responseElement = new DomParser().parseFromString(rawXml);
checkSignature(responseElement, rawXml, idpCertificate);
```
Dove check signature è la seguente

```
public checkSignature(element: Element, rawXml: string, certificate: string): boolean {
        const signature = element.getElementsByTagName('ds:Signature').item(0);
        const sig = new SignedXml();
        const cert = this.certToPEM(certificate);
        const formattedCertificate = Buffer.from(cert);
        sig.keyInfoProvider = {
            getKey() {
                return formattedCertificate;
            }
        } as any as FileKeyInfo;
        sig.loadSignature(signature.toString());
        const valid = sig.checkSignature(rawXml);
        return valid;
    }

   certToPEM(cert: string): string {
        cert = cert.match(/.{1,64}/g)!.join('\n');

        if (cert.indexOf('-BEGIN CERTIFICATE-') === -1)
            cert = "-----BEGIN CERTIFICATE-----\n" + cert;
        if (cert.indexOf('-END CERTIFICATE-') === -1)
            cert = cert + "\n-----END CERTIFICATE-----\n";

        return cert;
    }
```

L'errore che ricevo è:
```
invalid signature: for uri #_e01c6de8-a1f6-4e78-8c7d-a8cbc146d99d calculated digest is afljnSRglGdi5UrGT7xZ7E+xwc1i1gXicwBtdpNrRBc= but the xml to validate supplies digest MaUY1kN4Pbyx4+9NcEkpmKHLs5h4ZWfGNygPx64t22M=
```

Allego la risposta dello spid validator:
[idp-response.zip](https://github.com/italia/spid-saml-check/files/5776787/idp-response.zip)

Potreste aiutarmi? Non capisco cosa sto sbagliando

Grazie,
Valentino

**Comment by damikael** [comment]
A seguito di ulteriore verifica, confermo che la Response inviata dal Validator risulta corretta.
Se si dovesse riscontrare nuovamente il problema suggerisco di aprire una nuova issue.

Grazie
